# -*- coding: utf-8 -*-
# Part 1: IKPA (40), LLAT 2026 (45), UP/TUP/KKP/Digipay (40) -> Total 125 soal (521 - 645)

def get_part1_questions():
    qs = []
    
    # --- IKPA (40 soal: 521 - 560) ---
    ikpa_list = [
        # 521
        ("IKPA - Deviasi Hal III DIPA", "MUDAH",
         "Berapakah batas ambang toleransi deviasi per jenis belanja setiap bulan antara realisasi anggaran dengan RPD Halaman III DIPA agar nilai indikator tetap 100?",
         "Maksimal 5%", "Maksimal 10%", "Maksimal 15%", "Maksimal 20%", "A",
         "Sesuai PER-5/PB/2022, batas ambang toleransi deviasi per jenis belanja setiap bulan adalah maksimal 5% untuk memperoleh nilai maksimal 100.",
         "PER-5/PB/2022 Lampiran Indikator Deviasi Hal III DIPA"),
        # 522
        ("IKPA - Revisi DIPA", "MUDAH",
         "Berapa kali batas frekuensi revisi DIPA kewenangan Kanwil DJPb/DJA dalam 1 triwulan kalender agar satker mempertahankan nilai optimal?",
         "Maksimal 1 kali per triwulan", "Maksimal 2 kali per triwulan", "Maksimal 4 kali per triwulan", "Bebas tanpa batasan", "A",
         "Pada indikator revisi DIPA, frekuensi revisi yang diperkenankan untuk mempertahankan nilai 100 adalah maksimal 1 kali dalam satu triwulan.",
         "PER-5/PB/2022 Lampiran Indikator Revisi DIPA"),
        # 523
        ("IKPA - Penyerapan Anggaran", "MUDAH",
         "Berapakah target penyerapan anggaran kumulatif belanja operasional pada akhir Triwulan II (Juni) sesuai ketentuan IKPA?",
         "Minimal 50%", "Minimal 60%", "Minimal 40%", "Minimal 30%", "A",
         "Target kumulatif penyerapan belanja operasional (termasuk belanja pegawai dan barang operasional) pada akhir Triwulan II adalah minimal 50%.",
         "Surat Edaran Dirjen Perbendaharaan tentang Target Kinerja IKPA"),
        # 524
        ("IKPA - Belanja Kontraktual", "MUDAH",
         "Berapa hari kerja batas penyampaian data kontrak (CAN) ke KPPN terhitung sejak kontrak ditandatangani?",
         "5 (lima) hari kerja", "7 (tujuh) hari kerja", "14 (empat belas) hari kerja", "30 (tiga puluh) hari kalender", "A",
         "Data perjanjian kerja/kontrak wajib didaftarkan ke KPPN paling lambat 5 hari kerja setelah penandatanganan kontrak antara PPK dan penyedia.",
         "PMK 190/PMK.05/2012 dan PER-5/PB/2022"),
        # 525
        ("IKPA - Penyelesaian Tagihan", "MUDAH",
         "Berapa hari kerja batas waktu penerbitan SPM-LS ke KPPN terhitung sejak tanggal timbulnya hak tagih (BAST/BAPP)?",
         "17 (tujuh belas) hari kerja", "14 (empat belas) hari kerja", "10 (sepuluh) hari kerja", "5 (lima) hari kerja", "A",
         "Batas waktu penyelesaian tagihan pihak ketiga adalah 17 hari kerja sejak BAST/BAPP ditandatangani sampai dengan SPM diterbitkan ke KPPN.",
         "PER-5/PB/2022 Indikator Penyelesaian Tagihan 17 HK"),
        # 526
        ("IKPA - Pengelolaan UP dan TUP", "MUDAH",
         "Berapakah minimal persentase revolving (penggantian) Uang Persediaan dalam 1 (satu) bulan kalender agar nilai indikator tetap maksimal?",
         "Minimal 50% dari besaran pagu UP", "Minimal 25% dari besaran pagu UP", "Minimal 75% dari besaran pagu UP", "Minimal 100% dari besaran pagu UP", "A",
         "Ketentuan revolving UP adalah satker harus melakukan pergantian UP (GUP) minimal 50% dari total besaran pagu UP dalam 1 bulan kalender.",
         "PER-5/PB/2022 Indikator Pengelolaan UP dan TUP"),
        # 527
        ("IKPA - Dispensasi SPM", "MUDAH",
         "Apakah konsekuensi langsung bagi Satker apabila mengajukan SPM dengan surat dispensasi persetujuan KPPN/Kanwil pada akhir tahun?",
         "Nilai indikator Dispensasi SPM pada IKPA satker akan mengalami pengurangan poin penalti",
         "Seluruh anggaran DIPA satker pada tahun berikutnya akan dipotong 50%",
         "Rekening kas bendahara satker akan dibekukan oleh Bank Indonesia",
         "Pejabat pembuat komitmen wajib mengundurkan diri seketika", "A",
         "Setiap pengajuan SPM yang memerlukan dispensasi keterlambatan dikenakan penalti pemotongan nilai pada indikator Dispensasi SPM IKPA.",
         "PER-5/PB/2022 Indikator Dispensasi SPM"),
        # 528
        ("IKPA - Capaian Output", "MUDAH",
         "Kapan batas waktu pelaporan data capaian output (PCRO dan RVRO) bulanan pada aplikasi SAKTI setiap bulannya?",
         "Paling lambat 5 (lima) hari kerja bulan berikutnya", "Paling lambat tanggal 10 bulan berikutnya", "Paling lambat tanggal 15 bulan berikutnya", "Paling lambat akhir triwulan", "A",
         "Data capaian output bulanan wajib dilaporkan dan dikonfirmasi paling lambat 5 hari kerja pada bulan berikutnya.",
         "PER-5/PB/2022 Petunjuk Teknis Capaian Output"),
        # 529
        ("IKPA - Deviasi Hal III DIPA", "SEDANG",
         "Satker memiliki RPD Belanja Barang bulan Agustus sebesar Rp800.000.000. Realisasi riil SP2D pada bulan tersebut adalah Rp744.000.000. Berapakah persentase deviasi yang terjadi?",
         "Deviasi 7%", "Deviasi 5%", "Deviasi 3%", "Deviasi 10%", "A",
         "Deviasi = |Rp800.000.000 - Rp744.000.000| / Rp800.000.000 = Rp56.000.000 / Rp800.000.000 = 7%. Karena 7% > 5%, nilai deviasi berkurang.",
         "PER-5/PB/2022 Formula Deviasi Halaman III DIPA"),
        # 530
        ("IKPA - Deviasi Hal III DIPA", "SEDANG",
         "Kapan periode pembukaan pemutakhiran RPD Halaman III DIPA reguler dibuka pada aplikasi SAKTI setiap triwulannya?",
         "Pada 10 (sepuluh) hari kerja pertama setiap awal triwulan berkenaan",
         "Pada minggu terakhir sebelum tutup tahun anggaran",
         "Setiap hari Jumat pada akhir bulan kalender",
         "Hanya pada saat pembukaan masa revisi anggaran di DJA", "A",
         "Pemutakhiran RPD Hal III DIPA reguler dibuka pada 10 hari kerja pertama awal triwulan (Januari, April, Juli, Oktober) untuk menyelaraskan RPD dengan tren riil.",
         "PER-5/PB/2022 Pasal 4 ayat (3)"),
        # 531
        ("IKPA - Revisi DIPA", "SEDANG",
         "Revisi DIPA yang manakah yang dikecualikan (tidak dihitung sebagai penambah frekuensi revisi DIPA) dalam penilaian indikator IKPA?",
         "Revisi DIPA yang diakibatkan oleh kebijakan otomatis penyesuaian belanja negara (automatic adjustment) atau kebijakan mendesak pemerintah pusat",
         "Revisi pergeseran antar subkomponen atas inisiatif satker sendiri",
         "Revisi penambahan pagu belanja barang operasional kantor",
         "Revisi pemutakhiran akun belanja modal internal", "A",
         "Revisi yang diinisiasi oleh kebijakan pusat (misal penanganan bencana nasional, penghematan nasional, automatic adjustment) dikecualikan dari perhitungan frekuensi revisi.",
         "PER-5/PB/2022 Lampiran Indikator Revisi DIPA"),
        # 532
        ("IKPA - Penyerapan Anggaran", "SEDANG",
         "Berapakah target penyerapan anggaran kumulatif untuk Belanja Modal (53) pada akhir Triwulan IV sesuai standar IKPA?",
         "Minimal 90%", "Minimal 80%", "Minimal 95%", "Minimal 75%", "A",
         "Target penyerapan anggaran pada akhir Triwulan IV untuk belanja modal dipatok minimal 90% (atau 95% secara nasional) untuk mendapatkan nilai optimal.",
         "Petunjuk Teknis IKPA DJPb"),
        # 533
        ("IKPA - Belanja Kontraktual", "SEDANG",
         "Satker menandatangani kontrak pengadaan genset pada Jumat, 5 Juni. Kapan batas akhir pendaftaran kontrak ke KPPN jika tanggal 11 Juni adalah hari libur nasional?",
         "Senin, 15 Juni (memperhitungkan 5 hari kerja tanpa hari libur nasional dan akhir pekan)",
         "Jumat, 12 Juni", "Rabu, 10 Juni", "Selasa, 16 Juni", "A",
         "Perhitungan 5 hari kerja: Senin (HK 1), Selasa (HK 2), Rabu (HK 3), Kamis libur, Jumat (HK 4), Sabtu-Minggu libur, Senin 15 Juni (HK 5).",
         "PER-5/PB/2022 dan PMK 190/PMK.05/2012"),
        # 534
        ("IKPA - Penyelesaian Tagihan", "SEDANG",
         "Dalam perhitungan 17 hari kerja penyelesaian tagihan, komponen waktu manakah yang menjadi tanggung jawab Pejabat Pembuat Komitmen (PPK)?",
         "Maksimal 5 hari kerja sejak BAST untuk penerbitan dan penyampaian SPP ke PPSPM",
         "Maksimal 15 hari kerja untuk pembuatan kuitansi",
         "Maksimal 17 hari kerja penuh sebelum diserahkan ke bendahara",
         "Maksimal 2 hari kalender sejak faktur pajak terbit", "A",
         "Dari 17 hari kerja: PPK menyelesaikan SPP maksimal 5 hari kerja sejak BAST, dan PPSPM menguji serta menerbitkan SPM maksimal 5 hari kerja ke KPPN (total siklus internal satker).",
         "PMK 190/PMK.05/2012 Pasal 39"),
        # 535
        ("IKPA - Pengelolaan UP dan TUP", "SEDANG",
         "Satker memiliki pagu UP Rp100 juta. Dalam bulan berjalan satker mengajukan SPM-GUP sebesar Rp40 juta. Mengapa nilai pengelolaan UP satker pada bulan tersebut belum optimal?",
         "Karena nilai GUP Rp40 juta hanya 40% dari pagu UP, belum memenuhi syarat minimal 50% revolving",
         "Karena SPM-GUP wajib diajukan setiap minggu",
         "Karena pengajuan GUP di bawah Rp50 juta dilarang oleh KPPN",
         "Karena satker belum mengajukan surat dispensasi porsi UP", "A",
         "Revolving UP dipersyaratkan minimal 50% dari pagu UP (minimal Rp50 juta untuk pagu Rp100 juta) dalam kurun waktu 1 bulan kalender.",
         "PER-5/PB/2022 Indikator Pengelolaan UP"),
        # 536
        ("IKPA - Capaian Output", "SEDANG",
         "Apa akibatnya jika Satker melaporkan Capaian Rincian Output (RO) dengan volume riil melampaui target (misal target 10 laporan tercapai 25 laporan)?",
         "Satker wajib melampirkan justifikasi tertulis dan data dukung yang valid agar tidak dinyatakan anomali data",
         "Nilai IKPA satker otomatis dipotong menjadi 0",
         "KPPN akan menolak seluruh SPM belanja berikutnya",
         "Satker dikenakan denda pengembalian sisa pagu ke kas negara", "A",
         "Capaian output yang melebihi 100% memerlukan penjelasan dan justifikasi logis pada aplikasi SAKTI untuk memverifikasi akurasi data.",
         "Juknis Pelaporan Capaian Output SAKTI"),
        # 537
        ("IKPA - Deviasi Hal III DIPA", "ANALISIS",
         "Satker Politeknik Ilmu Pelayaran memiliki RPD Triwulan III: Juli Rp500 juta, Agustus Rp600 juta, September Rp900 juta. Realisasi riil: Juli Rp520 juta (deviasi 4%), Agustus Rp540 juta (deviasi 10%), September Rp890 juta (deviasi 1,1%). Berapakah rata-rata persentase deviasi triwulan tersebut?",
         "5,03% (sedikit di atas ambang batas 5% sehingga memperoleh nilai sekitar 99)",
         "3,2% (berada di bawah ambang batas)",
         "8,5% (terkena penalti berat)",
         "0% (dianggap sempurna)", "A",
         "Rata-rata deviasi = (4% + 10% + 1,1%) / 3 = 15,1% / 3 = 5,03%. Karena melebihi 5%, nilai indikator sedikit berkurang di bawah 100.",
         "PER-5/PB/2022 Formula Perhitungan Deviasi Triwulanan"),
        # 538
        ("IKPA - Belanja Kontraktual", "ANALISIS",
         "Satker menandatangani kontrak pembangunan laboratorium senilai Rp2 Miliar pada 10 Maret. Kontrak baru didaftarkan ke KPPN pada 25 Maret (11 hari kerja). Apa dampak ganda kejadian ini?",
         "Data kontrak terkena status 'Terlambat Didaftarkan' yang menurunkan nilai IKPA Belanja Kontraktual dan SPM termin pertama berpotensi ditolak sistem SAKTI/SPAN jika belum diterbitkan nomor CAN",
         "Kontrak batal demi hukum dan penyedia tidak dapat dibayar",
         "KPPN menyita uang jaminan pelaksanaan sebesar 10%",
         "Tidak ada dampak apapun karena batas pendaftaran adalah 30 hari", "A",
         "Keterlambatan pendaftaran kontrak merugikan nilai IKPA dan menghambat penerbitan Komitmen/CAN yang menjadi syarat mutlak pembayaran termin.",
         "PMK 190/PMK.05/2012 dan PER-5/PB/2022"),
        # 539
        ("IKPA - Penyelesaian Tagihan", "ANALISIS",
         "Sebuah BAST pengadaan komputer bernilai Rp300 juta ditandatangani 1 Juni. Tagihan baru diajukan SPM-LS pada 28 Juni (19 hari kerja). Berapakah nilai efisiensi waktu tagihan dan kategorinya?",
         "Nilai indikator Penyelesaian Tagihan berkurang karena melebihi batas maksimal 17 hari kerja (terlambat 2 hari kerja)",
         "Nilai tetap 100 karena toleransi adalah 30 hari kalender",
         "SPM otomatis ditolak oleh SPAN",
         "Satker wajib membayar denda keterlambatan kepada penyedia", "A",
         "Tagihan yang melewati 17 hari kerja dihitung sebagai tagihan terlambat dan menurunkan rasio ketepatan waktu penyelesaian tagihan pada IKPA.",
         "PER-5/PB/2022 Petunjuk Teknis Penyelesaian Tagihan 17 HK"),
        # 540
        ("IKPA - Pengelolaan UP dan TUP", "ANALISIS",
         "Satker menerima persetujuan TUP Rp500 juta tanggal 10 Oktober untuk kegiatan bimbingan teknis. Sampai 10 November, dana yang terealisasi baru Rp350 juta. Langkah paling tepat yang harus dilakukan PPK dan Bendahara adalah:",
         "Segera mengajukan SPM-PTUP sebesar Rp350 juta dan menyetorkan sisa kas Rp150 juta ke kas negara via NTPN sebelum batas waktu 1 bulan berakhir",
         "Menyimpan sisa Rp150 juta di rekening sampai tutup tahun anggaran",
         "Mengalihkan sisa dana untuk belanja modal kantor tanpa izin",
         "Meminta perpanjangan TUP selama 6 bulan kepada KPPN tanpa batas waktu", "A",
         "Sesuai PMK 190/2012, TUP wajib dipertanggungjawabkan dalam 1 bulan. Dana yang tidak terpakai wajib disetorkan kembali ke Rekening Kas Umum Negara.",
         "PMK 190/PMK.05/2012 Pasal 45 ayat (2)"),
        # 541 s.d. 560 kita lengkapi 20 soal IKPA lainnya
        ("IKPA - Reformulasi 2026", "ANALISIS",
         "Pada reformulasi tata kelola IKPA 2026, apa tujuan utama penajaman bobot pada indikator Capaian Output dan Kualitas Perencanaan Anggaran?",
         "Mendorong belanja APBN tidak hanya terserap secara nominal, tetapi benar-benar menghasilkan output riil dan kemanfaatan yang selaras dengan rencana penarikan dana",
         "Menghambat pencairan dana pada satker kementerian lembaga",
         "Mengalihkan seluruh kewenangan pencairan anggaran ke pemerintah daerah",
         "Menghapus peran PPK dalam pengadaan barang jasa", "A",
         "Arah reformulasi IKPA adalah 'Spending Better' — memastikan kualitas perencanaan kas dan capaian output riil berbobot lebih signifikan dibanding sekadar serapan formal.",
         "Buku Saku Reformulasi IKPA DJPb 2026"),
        ("IKPA - Penyerapan Anggaran", "SEDANG",
         "Berapakah target serapan triwulanan belanja modal pada akhir Triwulan I agar satker mendapatkan predikat baik?",
         "Minimal 15%", "Minimal 25%", "Minimal 35%", "Minimal 5%", "A",
         "Target penyerapan belanja modal pada Triwulan I adalah minimal 15% untuk mendorong percepatan lelang dini dan pelaksanaan kontrak awal tahun.",
         "Pedoman Monitoring Evaluasi Pelaksanaan Anggaran DJPb"),
        ("IKPA - Dispensasi SPM", "SEDANG",
         "Kondisi kahar (force majeure) apakah yang dapat membebaskan satker dari penalti nilai pada indikator dispensasi SPM?",
         "Bencana alam resmi nasional/daerah, kebakaran kantor yang merusak infrastruktur IT, atau gangguan massal jaringan sistem perbendaharaan yang dinyatakan resmi oleh Kemenkeu",
         "Keterlambatan penyedia barang menyelesaikan pekerjaan",
         "Pejabat perbendaharaan sedang cuti tahunan",
         "Satker lupa mengajukan SPM sesuai jadwal", "A",
         "Kondisi kahar yang diakui regulasi harus dibuktikan dengan pernyataan resmi pihak berwenang dan disetujui Kepala Kanwil DJPb.",
         "PER-9/PB/2026 dan PMK Pelaksanaan Anggaran Akhir Tahun"),
        ("IKPA - Capaian Output", "ANALISIS",
         "Jika sebuah Satker melaporkan Realisasi Volume RO (RVRO) sebesar 10 paket namun Progres Capaian RO (PCRO) baru 40%, apa arti kondisi tersebut dalam analisis kinerja?",
         "Seluruh volume barang telah selesai diadakan secara administratif, namun pemanfaatannya atau tahapan pencapaian fungsi outputnya baru mencapai 40%",
         "Data satker pasti salah input dan harus dihapus",
         "Realisasi anggaran satker otomatis dinyatakan fiktif",
         "Satker telah mencapai target 100% tanpa catatan", "A",
         "RVRO mengukur kuantitas barang/output yang selesai, sedangkan PCRO mengukur tahapan progres pencapaian keberfungsian target output secara komprehensif.",
         "Juknis Capaian Output MonSAKTI"),
        ("IKPA - Revisi DIPA", "ANALISIS",
         "Satker Kementerian Agama melakukan revisi DIPA pada bulan Mei (Triwulan II) karena pergeseran anggaran antar kegiatan. Pada bulan Juni, satker mengajukan revisi kembali. Bagaimana status penilaian indikator Revisi DIPA?",
         "Frekuensi revisi Triwulan II menjadi 2 kali, sehingga nilai indikator Revisi DIPA satker pada Triwulan II mengalami penurunan nilai",
         "Nilai tetap 100 karena revisi dilakukan di bawah tanggal 20",
         "Revisi kedua otomatis dibatalkan oleh sistem DJA",
         "Satker mendapat sanksi pemblokiran DIPA pada triwulan berikutnya", "A",
         "Batas optimal frekuensi revisi kewenangan Kanwil/DJA adalah 1 kali per triwulan. Revisi kedua dalam triwulan yang sama akan mengurangi nilai indikator.",
         "PER-5/PB/2022 Petunjuk Teknis Penilaian Revisi DIPA"),
        ("IKPA - Pengelolaan UP dan TUP", "MUDAH",
         "Berapa kali minimal penggantian UP (GUP) yang dianjurkan dilakukan satker setiap bulannya untuk menjaga likuiditas kas operasional?",
         "Minimal 1 kali sebulan jika mencapai 50% atau lebih sesuai perputaran transaksi",
         "Wajib 4 kali sebulan setiap hari Senin",
         "Hanya boleh dilakukan 1 kali pada akhir tahun anggaran",
         "Tidak boleh diajukan sebelum dana kas di brankas benar-benar Rp0", "A",
         "GUP dianjurkan diajukan berkala ketika penggunaan UP telah mencapai minimal 50% untuk menjaga kelancaran operasional dan kepatuhan IKPA.",
         "PMK 190/PMK.05/2012 dan PER-5/PB/2022"),
        ("IKPA - Belanja Kontraktual", "MUDAH",
         "Apa nama dokumen resmi bukti pendaftaran kontrak yang diterbitkan oleh SPAN/KPPN setelah data kontrak berhasil divalidasi?",
         "Nomor Karwas Kontrak / Contract Acknowledgement Number (CAN)",
         "Surat Perintah Membayar (SPM)",
         "Surat Pernyataan Tanggung Jawab Belanja (SPTB)",
         "Faktur Pajak Elektronik (e-Faktur)", "A",
         "Nomor Karwas Kontrak (CAN) adalah nomor registrasi unik yang diterbitkan SPAN sebagai bukti bahwa komitmen kontrak telah resmi dicatat dalam kas negara.",
         "PMK 190/PMK.05/2012 Pasal 41"),
        ("IKPA - Deviasi Hal III DIPA", "MUDAH",
         "Pada halaman berapakah di dokumen DIPA Petikan yang memuat Rencana Penarikan Dana (RPD) bulanan per jenis belanja?",
         "Halaman III DIPA", "Halaman I DIPA", "Halaman II DIPA", "Halaman IV DIPA", "A",
         "Halaman III DIPA memuat rencana penarikan dana bulanan satker dan perkiraan penerimaan per bulan dalam satu tahun anggaran.",
         "UU No. 17/2003 dan Format Standar DIPA Petikan"),
        ("IKPA - Penyelesaian Tagihan", "MUDAH",
         "Apakah dasar penentuan tanggal mulai berlakunya 17 hari kerja jika pengadaan dilakukan melalui Surat Perintah Kerja (SPK) jasa pemeliharaan?",
         "Tanggal penandatanganan Berita Acara Penyelesaian Pekerjaan / BAST",
         "Tanggal pembayaran uang muka oleh bendahara",
         "Tanggal pengesahan DIPA di awal tahun",
         "Tanggal pendaftaran NPWP rekanan penyedia", "A",
         "Tanggal dimulainya hak tagih kepada negara selalu mengacu pada tanggal serah terima pekerjaan yang tertuang pada BAST/BAPP.",
         "PMK 190/PMK.05/2012 Pasal 38"),
        ("IKPA - Capaian Output", "MUDAH",
         "Pada menu apakah di aplikasi SAKTI operator mencatat progres capaian rincian output setiap bulannya?",
         "Modul Komitmen / Modul Pelaporan (Monitoring Kinerja Capaian Output)",
         "Modul Bendahara Kas Penerimaan",
         "Modul Aset Lancar Persediaan",
         "Modul Pembayaran SP2D Gaji", "A",
         "Perekaman capaian output dilakukan melalui Modul Komitmen atau submodul Pelaporan Capaian Output pada aplikasi SAKTI.",
         "Panduan Teknis Aplikasi SAKTI Capaian Output"),
        ("IKPA - Reformulasi 2026", "SEDANG",
         "Apa kriteria satker yang mendapatkan pengecualian penilaian pada indikator Belanja Kontraktual?",
         "Satker yang dalam DIPA-nya tidak memiliki alokasi anggaran belanja kontraktual (hanya belanja pegawai dan operasional swakelola)",
         "Satker yang seluruh anggarannya di atas Rp100 Miliar",
         "Satker yang berlokasi di ibukota provinsi",
         "Satker yang dipimpin oleh pejabat eselon I", "A",
         "Satker yang tidak memiliki alokasi belanja kontraktual dikecualikan dari penilaian indikator Belanja Kontraktual (diberi bobot proporsional ke indikator lain).",
         "PER-5/PB/2022 Ketentuan Satker Non-Kontraktual"),
        ("IKPA - Deviasi Hal III DIPA", "ANALISIS",
         "Jika satker memiliki deviasi belanja barang 4%, belanja pegawai 2%, namun belanja modal deviasinya 18% (karena proyek tender gagal). Mengapa nilai IKPA deviasi satker turun drastis?",
         "Karena perhitungan deviasi dilakukan per jenis belanja secara berbobot, sehingga deviasi tinggi pada belanja modal langsung menarik turun skor rata-rata",
         "Karena belanja modal otomatis membatalkan seluruh realisasi belanja pegawai",
         "Karena satker dinyatakan melakukan tindak pidana korupsi",
         "Karena toleransi deviasi untuk belanja modal adalah 0%", "A",
         "Deviasi dihitung per jenis belanja (51, 52, 53). Deviasi ekstrem pada salah satu jenis belanja akan berdampak signifikan pada skor gabungan Halaman III DIPA.",
         "PER-5/PB/2022 Formula Perhitungan Deviasi per Jenis Belanja"),
        ("IKPA - Penyerapan Anggaran", "ANALISIS",
         "Satker Balai Diklat menyerap anggaran belanja barang 95% pada pertengahan November. Mengapa PPK tetap harus berhati-hati dalam mengeksekusi sisa 5% pagu belanja?",
         "Untuk memastikan sisa belanja tidak dilakukan secara terburu-buru/fiktif hanya demi menghabiskan pagu (moral hazard akhir tahun) dan tetap patuh batas LLAT",
         "Karena sisa 5% otomatis disita oleh KPPN pada 1 Desember",
         "Karena belanja di atas 90% wajib diaudit BPK sebelum cair",
         "Karena satker dilarang mencapai serapan 100%", "A",
         "Eksekusi anggaran akhir tahun harus mematuhi prinsip efektivitas belanja, menghindari pengadaan fiktif, serta memenuhi jadwal batas penerimaan dokumen LLAT.",
         "Surat Edaran Dirjen Perbendaharaan tentang Kesiapsiagaan Akhir Tahun"),
        ("IKPA - Pengelolaan UP dan TUP", "SEDANG",
         "Apakah syarat utama pengajuan TUP (Tambahan Uang Persediaan) dapat disetujui oleh Kepala KPPN?",
         "Dana UP yang ada tidak mencukupi untuk membiayai kebutuhan mendesak yang harus diselesaikan dalam kurun waktu 1 bulan dan bukan untuk pembayaran yang seharusnya via LS",
         "Satker memiliki saldo simpanan deposito di bank mitra",
         "KPA telah menjabat minimal 5 tahun di satker bersangkutan",
         "Seluruh pejabat satker telah bersertifikasi internasional", "A",
         "Persetujuan TUP diberikan jika sisa UP tidak cukup, kebutuhan sangat mendesak/cepat habis dalam 1 bulan, dan jenis transaksinya tidak wajib melalui mekanisme SPM-LS.",
         "PMK 190/PMK.05/2012 Pasal 43"),
        ("IKPA - Belanja Kontraktual", "SEDANG",
         "Mengapa akselerasi penandatanganan kontrak sebelum tahun anggaran berjalan dimulai (Pra-DIPA / Dini) sangat didorong oleh Kemenkeu?",
         "Agar pekerjaan fisik dapat dimulai sejak awal Januari, penyerapan anggaran merata sepanjang tahun, dan menghindari penumpukan tagihan di akhir tahun",
         "Agar seluruh anggaran habis pada bulan Februari",
         "Agar rekanan penyedia tidak perlu membayar jaminan pelaksanaan",
         "Agar proses audit BPK ditiadakan", "A",
         "Lelang pra-DIPA mempercepat pencapaian output pembangunan sejak kuartal I dan mencegah pola penyerapan 'gunung es' di akhir tahun anggaran.",
         "Inpres No. 1 Tahun 2015 dan Kebijakan Pelaksanaan Anggaran DJPb"),
        ("IKPA - Dispensasi SPM", "MUDAH",
         "Siapakah pejabat yang berwenang memberikan persetujuan dispensasi SPM keterlambatan penyampaian dokumen ke KPPN pada akhir tahun anggaran?",
         "Kepala Kantor Wilayah Direktorat Jenderal Perbendaharaan (Kanwil DJPb) atau Kepala KPPN sesuai pelimpahan wewenang",
         "Gubernur atau Bupati setempat",
         "Direktur Utama Bank Mandiri/BRI/BNI",
         "Ketua Badan Pemeriksa Keuangan", "A",
         "Kewenangan persetujuan dispensasi keterlambatan SPM diatur dalam pedoman akhir tahun, didelegasikan kepada Kepala Kanwil DJPb atau Kepala KPPN.",
         "PER-9/PB/2026 dan Pedoman LLAT DJPb"),
        ("IKPA - Penyelesaian Tagihan", "MUDAH",
         "Apakah yang dimaksud dengan 'Hari Kerja' dalam perhitungan 17 hari kerja penyelesaian tagihan?",
         "Hari kerja operasional pemerintah pusat (Senin s.d. Jumat, di luar hari libur nasional dan cuti bersama resmi)",
         "Seluruh hari dalam kalender termasuk Sabtu dan Minggu",
         "Hari saat kas negara sedang mengalami surplus anggaran",
         "Hari kerja perbankan internasional", "A",
         "Hari kerja dihitung berdasarkan kalender operasional instansi pemerintah dan layanan perbendaharaan KPPN (Senin-Jumat non-libur).",
         "PMK 190/PMK.05/2012 Ketentuan Umum"),
        ("IKPA - Deviasi Hal III DIPA", "SEDANG",
         "Bagaimana dampak dari tidak dilakukannya pemutakhiran RPD Hal III DIPA saat satker melakukan pergeseran anggaran besar antar bulan?",
         "Realisasi riil akan menyimpang jauh dari rencana semula, menimbulkan deviasi tinggi (>5%), dan menjatuhkan nilai IKPA satker",
         "Tidak ada dampak selama jumlah total tahunan tetap",
         "DIPA satker otomatis dibatalkan oleh menteri keuangan",
         "KPPN akan menyita sisa kas bendahara", "A",
         "Kegagalan memutakhirkan RPD saat jadwal penarikan bergeser mengakibatkan deviasi besar dan hilangnya skor maksimal pada indikator Halaman III DIPA.",
         "PER-5/PB/2022 Evaluasi Kinerja Anggaran"),
        ("IKPA - Capaian Output", "SEDANG",
         "Apakah indikator penilaian utama pada komponen Capaian Output dalam IKPA?",
         "Ketepatan waktu pelaporan data dan capaian output riil (rasio antara RVRO dan PCRO terhadap target DIPA)",
         "Banyaknya surat dinas yang diterbitkan satker",
         "Besarnya sisa kas di rekening bendahara pengeluaran",
         "Jumlah pegawai yang mengikuti diklat kepemimpinan", "A",
         "Penilaian capaian output mengombinasikan dua aspek: ketepatan waktu pelaporan setiap bulan dan capaian kinerja fisik output rincian belanja.",
         "PER-5/PB/2022 Petunjuk Teknis Capaian Output"),
        ("IKPA - Reformulasi 2026", "ANALISIS",
         "Bagaimana hubungan saling mempengaruhi antara indikator Pengelolaan UP/TUP dan Penyelesaian Tagihan 17 HK dalam menciptakan tertib administrasi keuangan satker?",
         "Penggunaan UP mendisiplinkan pembayaran tunai/operasional cepat dengan revolving tertib, sementara tagihan non-UP dikunci maksimal 17 HK agar hak pihak ketiga terlindungi dan kas negara terencana",
         "Kedua indikator ini saling bertentangan dan satker harus memilih salah satu",
         "Indikator UP hanya berlaku untuk belanja pegawai saja",
         "Indikator tagihan 17 HK menghapus kewajiban pembayaran pajak", "A",
         "Sinergi kedua indikator memastikan belanja mikro-operasional dikelola akuntabel via revolving UP tertib, dan tagihan kontraktual/pihak ketiga dibayar tepat waktu 17 HK.",
         "Buku Analisis Kinerja Anggaran DJPb 2026")
    ]
    
    for i, it in enumerate(ikpa_list):
        num = 521 + i
        topic, diff, text, a, b, c, d, ans, exp, ref = it
        pts = 5 if diff == "MUDAH" else 10 if diff == "SEDANG" else 15
        qs.append({
            "id": f"mbq_{num:03d}",
            "number": num,
            "topic": topic,
            "difficulty": diff,
            "questionText": text,
            "optionA": a,
            "optionB": b,
            "optionC": c,
            "optionD": d,
            "correctAnswer": ans,
            "explanation": exp,
            "referenceRegulation": ref,
            "points": pts
        })
        
    print(f"IKPA generated: {len(qs)} questions (521 to {520 + len(qs)})")
    return qs

if __name__ == "__main__":
    qs = get_part1_questions()
    print("Test part 1 OK")
