# -*- coding: utf-8 -*-
import json

def q(num, topic, diff, q_text, a, b, c, d, ans, exp, reg):
    pts = 5 if diff == 'MUDAH' else (10 if diff == 'SEDANG' else 15)
    return {
        "id": f"mbq_{num}",
        "number": num,
        "topic": topic,
        "difficulty": diff,
        "questionText": q_text,
        "optionA": a,
        "optionB": b,
        "optionC": c,
        "optionD": d,
        "correctAnswer": ans,
        "explanation": exp,
        "referenceRegulation": reg,
        "points": pts
    }

questions = []
cur_num = 1101

# ============================================================================
# TOPIC 2: Aplikasi SAKTI & MonSAKTI Terintegrasi (1101 - 1150)
# ============================================================================
t2 = "Aplikasi SAKTI & MonSAKTI Terintegrasi"
reg2 = "PMK No. 171/PMK.05/2021 tentang Sistem Akuntansi dan Pelaporan Keuangan Instansi jo Modul SAKTI DJPb"

t2_items = [
    # 17 MUDAH
    ("Aplikasi SAKTI mengintegrasikan seluruh proses pengelolaan keuangan negara pada level:", 
     "Kementerian Koordinator", "Satuan Kerja (Satker)", "Pemerintah Daerah", "Badan Usaha Milik Swasta", "B", 
     "SAKTI (Sistem Aplikasi Keuangan Tingkat Instansi) digunakan oleh seluruh Satuan Kerja K/L pengelola APBN.", reg2),
    ("Berapakah jumlah modul utama dalam arsitektur Aplikasi SAKTI?", 
     "5 Modul", "7 Modul", "9 Modul", "12 Modul", "C", 
     "SAKTI memiliki 9 modul utama: Penganggaran, Komitmen, Pembayaran, Bendahara, Persediaan, Aset Tetap, Piutang, Pelaporan/GLP, dan Administrator.", reg2),
    ("Modul pada SAKTI yang digunakan untuk mencatat referensi supplier, PPK, dan karwas kontrak adalah:", 
     "Modul Penganggaran", "Modul Komitmen", "Modul Pelaporan", "Modul Bendahara", "B", 
     "Modul Komitmen bertugas mengelola data supplier, kontrak, SPK, dan BAST untuk pembentukan komitmen anggaran.", reg2),
    ("Peran (role) pengguna SAKTI yang bertugas membuat draft dokumen transaksi belanja adalah:", 
     "Operator", "Validator", "Approver", "Auditor", "A", 
     "Hierarki peran SAKTI: Operator (pembuat draft/perekam), Validator (PPK/verifikator), dan Approver (PPSPM/KPA).", reg2),
    ("Peran Approver pada Modul Pembayaran SAKTI dipegang oleh:", 
     "Staf Pembuat Komitmen", "Pejabat Penandatangan SPM (PPSPM)", "Bendahara Penerimaan", "Petugas Pengantar SPM KPPN", "B", 
     "PPSPM bertindak sebagai Approver Modul Pembayaran yang menyetujui dan menandatangani SPM secara elektronik.", reg2),
    ("Metode pengamanan tanda tangan elektronik pada dokumen SPM di SAKTI menggunakan:", 
     "Tanda tangan basah yang di-scan", "Digital Signature berbasis Sertifikat Elektronik Balai Sertifikasi Elektronik (BSrE)", "Cap stempel dinas berwarna", "Foto selfie pejabat pembuat komitmen", "B", 
     "Persetujuan SPM di SAKTI menggunakan Tanda Tangan Elektronik (TTE) tersertifikasi yang diterbitkan oleh BSrE BSSN.", reg2),
    ("One Time Password (OTP) pada SAKTI dikirimkan kepada pejabat perbendaharaan melalui:", 
     "Email atau SMS/Aplikasi Otentikasi terdaftar", "Surat fisik pos kilat", "Pesan suara telepon rumah", "WhatsApp grup kantor", "A", 
     "Kode OTP SAKTI dikirimkan ke nomor ponsel resmi yang telah terdaftar pada database pengguna Ditjen Perbendaharaan.", reg2),
    ("Portal monitoring terintegrasi berbasis web yang melacak seluruh data transaksi SAKTI adalah:", 
     "DJP Online", "MonSAKTI", "SIMPONI", "SPAN Online Satker", "B", 
     "MonSAKTI adalah portal monitoring dan evaluasi terpusat untuk memantau data transaksi dan LK seluruh satker SAKTI.", reg2),
    ("Modul GLP pada SAKTI adalah singkatan dari:", 
     "Ganti Uang Persediaan Laporan", "General Ledger dan Pelaporan", "Giro Layanan Perbankan", "Good Ledger Practice", "B", 
     "GLP singkatan dari General Ledger dan Pelaporan, yang berfungsi memproses jurnal akuntansi dan laporan keuangan.", reg2),
    ("Untuk mencatat penerimaan barang inventaris kantor yang belum dipakai, SAKTI menggunakan:", 
     "Modul Penganggaran", "Modul Persediaan", "Modul Piutang", "Modul Administrator", "B", 
     "Barang habis pakai dan bahan persediaan dicatat serta dikelola dalam Modul Persediaan SAKTI.", reg2),
    ("Modul Aset Tetap pada SAKTI berfungsi untuk:", 
     "Mencatat transaksi mutasi dan penyusutan Barang Milik Negara (BMN) berupa aset tetap", "Mencairkan SP2D di bank", "Menghitung PPh Pasal 21 pegawai", "Mengajukan revisi pagu DIPA", "A", 
     "Modul Aset Tetap menangani perolehan, pengembangan, penyusutan, pemindahtanganan, dan penghapusan BMN aset tetap.", reg2),
    ("Interkoneksi data transaksi keuangan antara SAKTI satker dan SPAN di KPPN berlangsung secara:", 
     "Manual dengan mengirim file flashdisk", "Otomatis dan realtime via database terpusat Kemenkeu", "Mingguan melalui email dinas", "Bulanan setelah tutup buku", "B", 
     "SAKTI dan SPAN terhubung secara single database terintegrasi di Pusat Sistem Informasi dan Teknologi Keuangan Kemenkeu.", reg2),
    ("Fitur 'To Do List' pada MonSAKTI berfungsi memberikan:", 
     "Pemberitahuan pekerjaan belanja yang tertunda, anomali data jurnal, dan batas waktu pelaporan", "Menu pemesanan tiket perjalanan dinas", "Jadwal cuti tahunan pegawai satker", "Daftar menu kantin Kemenkeu", "A", 
     "To Do List MonSAKTI menyajikan peringatan dini (early warning) atas transaksi pending, pagu minus, unmatch data, dan rekonsiliasi.", reg2),
    ("Pada SAKTI, proses pencatatan Surat Perintah Pencairan Dana (SP2D) yang telah terbit dilakukan melalui:", 
     "Perekaman manual oleh operator", "Penerimaan otomatis (download) data SP2D dari SPAN", "Penginputan oleh pihak bank persepsi", "Pencetakan ulang kertas cek", "B", 
     "Data SP2D masuk ke SAKTI secara otomatis dari SPAN setelah KPPN menerbitkan SP2D elektronik.", reg2),
    ("Fungsi 'Tutup Periode' pada Modul GL dan Pelaporan SAKTI bertujuan untuk:", 
     "Mengunci transaksi keuangan bulanan agar data laporan keuangan tidak berubah", "Menghapus database tahun sebelumnya", "Mematikan server SAKTI di akhir pekan", "Membatalkan seluruh SP2D", "A", 
     "Tutup periode mengunci pencatatan jurnal akuntansi bulan berkenaan guna validitas penyusunan Laporan Keuangan.", reg2),
    ("Untuk membuat Surat Permintaan Pembayaran (SPP), peran pengguna SAKTI yang digunakan adalah:", 
     "Operator Modul Pembayaran", "Approver Modul Komitmen", "Validator Modul Pelaporan", "Administrator Kanwil", "A", 
     "Operator Modul Pembayaran bertugas merekam dan mencetak/memproses draft SPP.", reg2),
    ("Buku Kas Umum (BKU) bendahara pengeluaran dikelola pada modul SAKTI:", 
     "Modul Anggaran", "Modul Bendahara", "Modul Aset Tetap", "Modul Komitmen", "B", 
     "Seluruh penatausahaan kas, kas pembantu, kuitansi UP, LPJ, dan BKU dikelola pada Modul Bendahara SAKTI.", reg2),

    # 17 SEDANG
    ("Bagaimanakah urutan alur pendaftaran supplier tipe 1 (Satker) atau tipe 2 (Penyedia) di SAKTI hingga disetujui KPPN?", 
     "Perekaman Supplier oleh Operator Komitmen -> Persetujuan PPK (TTE/OTP) -> Kirim ADK Supplier ke SPAN -> KPPN menerbitkan Nomor Register Supplier (NRS)", "Perekaman oleh Bendahara -> Langsung kirim SPM ke Bank -> KPPN menerbitkan cek", "Perekaman oleh KPA -> Kirim email ke Kanwil -> Operator menginput NRS", "Vendor mendaftar mandiri di KPPN tanpa melibatkan satker", "A", 
     "Alur supplier: Perekaman di Modul Komitmen -> Validasi PPK -> ADK dikirim ke SPAN KPPN -> SPAN memvalidasi rekening & menerbitkan NRS.", reg2),
    ("Jika terjadi kegagalan pengiriman ADK SPM dari SAKTI ke SPAN dengan notifikasi 'Pagu Minus', langkah koreksi yang benar adalah:", 
     "Memaksa kirim dengan akun lain", "Memeriksa sisa pagu akun berkenaan di SAKTI/MonSAKTI dan melakukan revisi DIPA pergeseran anggaran sebelum SPM diajukan kembali", "Menghapus data DIPA di modul anggaran", "Meminjam pagu belanja modal satker lain tanpa revisi", "B", 
     "Pagu minus menahan proses penerbitan SP2D di SPAN; satker wajib menuntaskan revisi pergeseran anggaran antar-komponen/akun.", reg2),
    ("Apa penyebab munculnya 'Jurnal Tidak Seimbang' (Unbalance Journal) pada modul GLP SAKTI?", 
     "Adanya ketidaksesuaian pencatatan debet dan kredit akibat interkoneksi modul yang terputus di tengah proses transaksi, memerlukan validasi dan posting ulang", "Perbedaan mata uang rupiah dan dolar", "Penyedia barang menolak pembayaran", "KPPN belum menerbitkan SP2D", "A", 
     "Unbalance journal timbul akibat gangguan sinkronisasi antar-subledger modul akuntansi; solusinya adalah re-validasi jurnal dan posting ulang di GLP.", reg2),
    ("Bagaimana tata cara pembatalan SPP yang telah disetujui oleh PPK tetapi belum menjadi SPM di SAKTI?", 
     "PPK melakukan penolakan/pembatalan SPP pada Modul Pembayaran sehingga status SPP kembali ke draft Operator untuk diedit atau dihapus", "Operator langsung menghapus dokumen di menu cetak", "Menghubungi kantor pusat Kemenkeu untuk format ulang", "SPP yang sudah disetujui PPK tidak dapat dibatalkan sama sekali", "A", 
     "PPK memiliki wewenang menolak SPP yang belum di-generate menjadi SPM, mengembalikan dokumen ke antrean operator untuk perbaikan.", reg2),
    ("Pada Modul Persediaan SAKTI, transaksi perolehan barang inventaris melalui mekanisme SP2D LS pihak ketiga dicatat melalui menu:", 
     "Pembelian Langsung Kas UP", "Perolehan Barang dari Pembelian (Pendataan BAST Komitmen)", "Hibah Keluar Pemerintah", "Transfer Keluar Antar-Satker", "B", 
     "Perekaman persediaan dari belanja LS dilakukan dengan menarik referensi BAST yang telah dicatat di Modul Komitmen.", reg2),
    ("Apa yang dimaksud dengan proses 'Rekonsiliasi Internal' di SAKTI?", 
     "Pencocokan saldo kas dan aset antara Modul Subledger (Persediaan, Aset Tetap, Piutang, Kas) dengan Modul Akuntansi GL dan Pelaporan", "Rapat koordinasi antar-pejabat di hotel", "Pencocokan data pegawai dengan BKN", "Pengiriman laporan fisik ke KPK", "A", 
     "Rekonsiliasi internal memastikan bahwa angka transaksi pada buku besar pembantu aset/persediaan sama persis dengan jurnal di Buku Besar GLP.", reg2),
    ("Dalam hal terjadi pergantian pejabat PPK, prosedur administratif penyesuaian akun SAKTI yang wajib ditempuh adalah:", 
     "Menggunakan username dan password PPK lama", "Administrator SAKTI satker merekam SK baru PPK, menonaktifkan user PPK lama, dan mendaftarkan user & sertifikat TTE PPK baru", "Membuat satker baru dengan nomor DIPA berbeda", "Menghapus seluruh transaksi tahun berjalan", "B", 
     "Admin satker menonaktifkan role pejabat lama, menginput user baru berdasarkan SK KPA, dan mengunggah sertifikat digital pejabat pengganti.", reg2),
    ("Apabila pada MonSAKTI terdeteksi selisih saldo 'Kas di Bendahara Pengeluaran' dengan saldo bank, penyebab umumnya adalah:", 
     "Adanya kuitansi UP yang belum di-GUP-kan atau transaksi penarikan tunai bank yang belum dicatat di BKU SAKTI", "Kurs rupiah mengalami penurunan terhadap dolar", "Aplikasi MonSAKTI sedang dalam pemeliharaan server", "KPPN mencairkan SP2D dua kali lipat", "A", 
     "Perbedaan kas kasir dan saldo bank biasanya timbul karena lag pencatatan transaksi kuitansi, mutasi kas tunai, atau potongan pajak yang belum disetor.", reg2),
    ("Bagaimana prosedur penerbitan SPM Ganti Uang Persediaan (GUP) di SAKTI?", 
     "Operator Bendahara input kuitansi -> Rekam SPP GUP -> Validasi PPK -> Approver PPSPM setujui & kirim ADK SPM via TTE ke SPAN", "Perekaman langsung oleh PPSPM tanpa kuitansi", "KPPN menerbitkan SP2D sebelum satker merekam kuitansi", "Pihak penyedia barang mengajukan SPM langsung ke bank", "A", 
     "Alur GUP: Kuitansi dicatat bendahara -> Diambil oleh operator pembayaran untuk SPP GUP -> Disetujui PPK -> PPSPM sahkan SPM dan inject TTE.", reg2),
    ("Fitur 'Migrasi Saldo Awal' di SAKTI digunakan pada saat:", 
     "Awal implementasi SAKTI atau pembukaan tahun anggaran baru untuk membawa saldo akhir neraca auditan tahun lalu menjadi saldo awal", "Satker mengajukan pinjaman bank", "Pemberian dana THR pegawai", "Setiap kali ada pergantian menteri", "A", 
     "Migrasi saldo awal memindahkan saldo penutup audited tahun anggaran sebelumnya ke pembukuan tahun berjalan secara akurat.", reg2),
    ("Mengapa transaksi Transfer Masuk dan Transfer Keluar BMN antar-satker di SAKTI harus menggunakan kode satker mitra yang valid?", 
     "Agar transaksi reciprocal tereliminasi secara sempurna pada proses konsolidasi Laporan Keuangan Tingkat K/L dan LKPP", "Agar barang tidak rusak saat pengiriman fisik", "Supaya vendor mendapat komisi pengiriman", "Untuk menghindari pembayaran pajak bea cukai", "A", 
     "Transaksi reciprocal transfer antar-satker wajib berpasangan agar tidak menimbulkan selisih eliminasi (unmatched transfer) pada LK Konsolidasian.", reg2),
    ("Kapan proses Rekonsiliasi Eksternal antara SAKTI dengan SPAN KPPN dinyatakan 'Selesai' di MonSAKTI?", 
     "Ketika satker mengunduh Surat Keterangan Rekonsiliasi (SKR) terbitan MonSAKTI tanpa menyisakan Transaksi Dalam Konfirmasi (TDK)", "Setelah bendahara menyerahkan print-out buku kas ke KPPN", "Jika nilai belanja mencapai target 100%", "Setelah kepala kantor menandatangani nota dinas", "A", 
     "Rekonsiliasi eksternal sukses ditandai dengan terbitnya Surat Hasil Rekonsiliasi (SHR/SKR) berstatus 'SAMA' tanpa selisih TDK.", reg2),
    ("Menu 'Koreksi SPM' di SAKTI dapat dilakukan apabila:", 
     "Terjadi kesalahan penulisan kode akun atau bagan akun standar (BAS) pada SPM yang telah terbit SP2D-nya, sepanjang tidak mengubah jumlah total uang", "Satker ingin mengganti nama pihak ketiga penerima uang yang sudah lunas", "Uang belanja ingin dialihkan ke rekening pribadi PPK", "Kegiatan fiktif ingin dihapus dari pembukuan", "A", 
     "Koreksi SPM/SP2D diatur dalam PMK 190 untuk perbaikan administratif akun/satker/kewenangan tanpa mengubah total nominal rupiah SP2D.", reg2),
    ("Apabila terjadi insiden 'User Terkunci' (User Locked) pada SAKTI karena 3 kali salah memasukkan password, penyelesaiannya adalah:", 
     "Administrator Satker melakukan reset password pada Modul Administrator SAKTI", "Menghancurkan laptop dinas", "Menunggu selama 1 tahun anggaran", "Membuat surat permohonan ke Presiden", "A", 
     "Admin SAKTI pada level satker memiliki hak akses me-reset status locked akun pengguna internal satker.", reg2),
    ("Pada Modul Komitmen SAKTI, fungsi dari 'Pemisahan Termin Kontrak' adalah:", 
     "Membagi jadwal penarikan dana dan pembayaran tagihan penyedia barang ke dalam tahapan prestasi kemajuan fisik pekerjaan", "Membayar penyedia secara tunai di muka 100%", "Memotong pajak penghasilan penyedia", "Mengurangi nilai kontrak agar murah", "A", 
     "Jadwal pembayaran bertahap (termin) memetakan RPD kontrak secara presisi sesuai tahapan progres fisik konstruksi/pekerjaan.", reg2),
    ("Apa arti status SPM 'Menunggu Approval' pada dashboard SAKTI?", 
     "SPP telah divalidasi oleh PPK dan saat ini sedang menunggu persetujuan dan injeksi tanda tangan elektronik (TTE) oleh PPSPM", "SPM telah dicairkan oleh Bank Indonesia", "Uang telah diterima oleh rekanan penyedia", "Dokumen ditolak oleh server Kemenkeu", "A", 
     "Status 'Menunggu Approval' menandakan dokumen SPP/SPM berada pada antrean wewenang PPSPM untuk diteliti dan disetujui secara digital.", reg2),
    ("Bagaimana cara mencatat setoran sisa kas UP ke kas negara pada SAKTI?", 
     "Operator Bendahara merekam data Surat Setoran Bukan Pajak (SSBP) dengan Nomor Transaksi Bank (NTB) dan Nomor Transaksi Penerimaan Negara (NTPN)", "Menulis di buku tulis bergaris", "Mengirim uang melalui wesel pos", "Memasukkan uang ke rekening tabungan pribadi bendahara", "A", 
     "Penyetoran kas ke Kas Negara wajib divalidasi di Modul Bendahara SAKTI dengan menginput data NTPN bukti setor penerimaan negara.", reg2),

    # 16 ANALISIS
    ("Analisis Kasus Kegagalan Inject TTE SPM oleh PPSPM: Pada akhir triwulan, PPSPM gagal menyetujui SPM karena sertifikat elektronik BSrE kedaluwarsa (expired). Solusi mitigasi kritis yang harus segera diambil agar SPM tidak melampaui batas norma waktu adalah:", 
     "Segera memperbarui masa berlaku sertifikat elektronik melalui helpdesk BSrE/Kominfo atau menunjuk Plt/pejabat pengganti dengan sertifikat aktif sesuai regulasi perbendaharaan", "Memalsukan tanda tangan digital dengan aplikasi edit foto", "Mengirimkan dokumen fisik tanpa TTE ke KPPN", "Membatalkan seluruh kegiatan belanja satker", "A", 
     "TTE kedaluwarsa menghambat validitas hukum dokumen; pembaharuan sertifikat atau penunjukan pejabat pengganti bersertifikat aktif wajib segera diproses.", reg2),
    ("Analisis Anomali Data Rekonsiliasi MonSAKTI (TDK Rupiah Kas): Pada rekonsiliasi akhir bulan, muncul TDK Rupiah antara SAKTI satker dan SPAN KPPN sebesar Rp 150 juta. Setelah ditelusuri, SP2D telah terbit di SPAN tetapi belum tercatat di GLP SAKTI. Tindakan penyelesaian yang tepat adalah:", 
     "Melakukan penarikan (download) ulang data transaksi SP2D pada Modul Pembayaran dan menjalankan proses validasi serta posting jurnal di Modul GLP", "Menghapus akun belanja terkait di SAKTI", "Meminta KPPN membatalkan SP2D yang telah cair", "Mengabaikan selisih karena sistem akan otomatis memperbaiki sendiri tanpa intervensi", "A", 
     "Data SP2D yang belum terpantul di GLP memerlukan sinkronisasi ulang data perbankan/SPAN ke Modul Pembayaran dan re-posting jurnal GLP.", reg2),
    ("Analisis Penanganan Pagu Minus Akibat Terbitnya Jurnal Penyesuaian Akhir Tahun: Pada penyusunan laporan keuangan unaudited, muncul pagu minus pada akun Belanja Pemeliharaan Gedung akibat jurnal koreksi aset. Mengapa pagu minus ini harus diselesaikan sebelum penutupan buku final?", 
     "Karena pagu minus melanggar UU Keuangan Negara (belanja melampaui batas anggaran) dan menyebabkan opini LK berpotensi disclaimer/WDP oleh BPK", "Karena rekening bank satker akan disita oleh pihak swasta", "Karena semua komputer satker akan terkunci otomatis", "Karena pegawai satker dilarang menerima gaji", "A", 
     "Pagu minus adalah pelanggaran konstitusional asas kepatutan anggaran; satker wajib menuntaskan revisi DIPA untuk menutup minus sebelum LK dikunci.", reg2),
    ("Analisis Kasus Ketidaksesuaian Akun dan BMN (Persediaan Belum Diregister): MonSAKTI menampilkan peringatan 'Akun Belanja Barang Persediaan (521811) belum diregister pada Modul Persediaan'. Risiko yang timbul pada Laporan Keuangan Satker jika tidak ditindaklanjuti adalah:", 
     "Nilai Aset Persediaan pada Neraca under-stated dan Beban Persediaan pada Laporan Operasional (LO) menjadi tidak akurat", "Kas di Bendahara Pengeluaran menjadi minus", "Penyedia barang tidak menerima pembayaran", "KPPN menolak pencairan uang gaji induk", "A", 
     "Belanja barang persediaan yang tidak diregister mengakibatkan nilai fisik persediaan tidak tercatat di neraca sehingga laporan keuangan salah saji.", reg2),
    ("Analisis Kasus Migrasi BMN Ganda (Double Recording): Operator Aset Tetap secara tidak sengaja menginput perolehan 10 unit laptop dua kali (dari BAST komitmen dan manual perolehan lainnya). Dampak terhadap Neraca satker dan langkah koreksi akuntansinya adalah:", 
     "Nilai Aset Tetap over-stated; solusinya merekam transaksi 'Koreksi Pembukuan/Penghapusan Catat Ganda' pada Modul Aset Tetap dan re-posting GLP", "Nilai Kas Negara bertambah dua kali lipat", "Satker wajib membeli 10 laptop tambahan", "KPPN akan mencairkan uang tunai ganda", "A", 
     "Pencatatan ganda menggelembungkan aset neraca secara fiktif; koreksi transaksi eliminasi catat ganda wajib dilakukan pada subledger aset.", reg2),
    ("Studi Kasus Gangguan Koneksi Jaringan SAKTI Terpusat (Disaster Recovery): Menjelang penutupan batas akhir pengajuan SPM gaji induk, koneksi server pusat SAKTI mengalami gangguan konektivitas (downtime). Prosedur operasional standar (SOP) kontingensi yang diberlakukan Kemenkeu adalah:", 
     "Penerbitan surat perpanjangan jam layanan/dispensasi kedaruratan teknis oleh Ditjen Perbendaharaan dan pengaktifan mekanisme fallback resmi", "Satker membayar gaji pegawai menggunakan uang kas pribadi bendahara", "Membatalkan pembayaran gaji bulan berkenaan", "Menghapus database gaji dari sistem", "A", 
     "Kemenkeu memiliki protokol Business Continuity Plan (BCP) yang menerbitkan pengumuman dispensasi waktu dan penyesuaian jadwal bagi seluruh satker.", reg2),
    ("Analisis Kasus Fraud Rekening Supplier (Man-in-the-Middle): Operator Komitmen menerima surat permintaan perubahan nomor rekening penyedia melalui email tak resmi, lalu mengubah data supplier di SAKTI tanpa verifikasi fisik. Evaluasi sistemik pencegahan fraud yang benar adalah:", 
     "Perubahan rekening supplier wajib melalui verifikasi ketat: surat permohonan resmi bermaterai dari direktur penyedia, konfirmasi ke bank penerbit, dan persetujuan PPK bertanda tangan elektronik", "Memperbolehkan perubahan rekening asal ada persetujuan staf administrasi", "Mentransfer uang ke rekening perorangan staf penyedia", "Menyerahkan uang pembayaran secara tunai", "A", 
     "Data supplier mengikat pencairan uang negara; perubahan nomor rekening adalah titik rawan korupsi yang memerlukan otentikasi berlapis dan validasi legal.", reg2),
    ("Analisis Kasus Saldo Kas Mengendap di Rekening Penampungan Akhir Tahun (RPATA): Bagaimana mekanisme pembukuan pada SAKTI jika pekerjaan fisik proyek belum tuntas 100% pada akhir tahun anggaran dan sisa dana ditempatkan pada RPATA?", 
     "Satker menerbitkan SPM-LS penampungan ke RPATA; di tahun anggaran berikutnya, pencairan dari RPATA ke rekening penyedia dicatat sebagai realisasi berbasis prestasi kerja riil", "Dana RPATA dianggap sebagai pendapatan negara bukan pajak", "Uang di RPATA otomatis menjadi milik penyedia tanpa syarat", "Sisa dana langsung dibagikan kepada panitia pengadaan", "A", 
     "RPATA menampung hak belanja kontraktual akhir tahun yang belum tuntas; pencairan ke penyedia dilakukan bertahap sesuai BAST kemajuan fisik tahun berikutnya.", reg2),
    ("Analisis Kasus Rekonsiliasi Internal Antara Modul Bendahara dan Modul GLP: Pada akhir triwulan, saldo LPJ Bendahara Pengeluaran tercatat Rp 10 juta, namun di Neraca saldo Kas di Bendahara bernilai Rp 0. Akar masalah ketidaksinkronan data ini adalah:", 
     "Operator GLP belum melakukan tutup periode atau belum menjalankan proses validasi dan posting jurnal kas bendahara pada modul GLP", "Bendahara kehilangan uang di brankas", "KPPN memotong saldo kas satker", "Nilai uang berkurang karena inflasi", "A", 
     "Transaksi kas bendahara yang telah dicatat di BKU harus melalui tahapan validasi dan posting jurnal di modul GLP agar terefleksi di pos Neraca.", reg2),
    ("Analisis Implementasi Single Sign-On (SSO) Kemenkeu pada Aplikasi SAKTI: Mengapa penerapan autentikasi multi-faktor (MFA) dan SSO menjadi mandatory dalam akses SAKTI era digital?", 
     "Mencegah pencurian kredensial akun pejabat perbendaharaan, melindungi integritas perintah transfer kas negara, dan memastikan non-repudiation transaksi", "Membuat proses login menjadi lebih rumit tanpa tujuan keamanan", "Mengurangi gaji pegawai yang lambat login", "Membatasi pegawai menggunakan internet di luar jam kantor", "A", 
     "SAKTI mengelola ribuan triliun APBN; pengamanan MFA/SSO mutlak untuk menjaga kerahasiaan, keutuhan, dan kepastian hukum identitas pengguna sistem.", reg2),
    ("Analisis Penanganan Unposted Transaction pada Modul Pelaporan: Operator mencetak Laporan Realisasi Anggaran (LRA) namun transaksi SP2D minggu terakhir tidak muncul. Saat dicek di MonSAKTI, terdapat 'Unposted Transactions'. Solusi teknis akuntansinya adalah:", 
     "Menjalankan menu Posting Jurnal pada Modul GLP untuk periode berkenaan agar seluruh transaksi subledger ditarik ke buku besar", "Mencatat transaksi secara manual dengan pulpen pada lembar cetak LRA", "Mengajukan SPM baru ke KPPN", "Menghapus SP2D yang tidak muncul", "A", 
     "Semua transaksi di modul operasional SAKTI baru akan masuk ke Laporan Keuangan setelah diproses posting buku besar pada Modul GL dan Pelaporan.", reg2),
    ("Analisis Penyusunan Catatan atas Laporan Keuangan (CaLK) Berbasis SAKTI: Mengapa tabel-tabel rincian di CaLK harus bersumber langsung dari modul SAKTI dan MonSAKTI?", 
     "Untuk memastikan konsistensi angka dan keterlacakan (audit trail) antara angka di lembar muka laporan keuangan dengan rincian transaksi pendukungnya", "Agar satker tidak perlu menulis narasi kebijakan", "Karena auditor eksternal tidak mau membaca dokumen cetak", "Supaya laporan keuangan berukuran tipis", "A", 
     "CaLK menyajikan pengungkapan rinci atas pos-pos LK; integrasi data SAKTI menjamin akurasi dan keandalan data bagi pemeriksa BPK.", reg2),
    ("Analisis Kasus Satker Gabungan (Likuidasi/Merger Instansi): Bagaimana prosedur SAKTI dalam menangani penggabungan dua satker kementerian akibat perampingan organisasi pemerintah?", 
     "Satker yang dilikuidasi melakukan tutup buku final, rekonsiliasi penutup, dan menerbitkan Berita Acara Transfer Saldo/Aset ke satker penerima melalui menu Transfer Keluar/Masuk Entitas Likuidasi", "Menghapus semua file komputer di satker lama", "Menjual seluruh gedung dan mobil dinas ke pasar lelang swasta", "Membagi-bagikan uang kas ke pegawai yang pensiun", "A", 
     "Penggabungan entitas memerlukan proses akuntansi likuidasi: tutup buku final, audit perantara, dan penyerahan neraca/aset via transaksi transfer SAKTI.", reg2),
    ("Analisis Pengendalian Internal Pemisahan Fungsi (Segregation of Duties) di SAKTI: Mengapa satu orang pegawai dilarang keras merangkap sebagai Operator Pembayaran dan Approver (PPSPM) sekaligus?", 
     "Mencegah benturan kepentingan (conflict of interest) dan risiko moral hazard pencairan anggaran negara tanpa pengujian silang yang sah", "Karena beban kerja menjadi terlalu ringan", "Karena sistem SAKTI akan kelebihan kapasitas memori", "Karena gaji pejabat akan dipotong dua kali", "A", 
     "Pemisahan tugas antara pembuat komitmen/tagihan dan penguji/penandatangan SPM adalah asas fundamental pengendalian intern pencegahan korupsi APBN.", reg2),
    ("Analisis Kasus Koreksi Transaksi Belanja yang Salah Akun Tahun Anggaran Lalu: Satker menemukan bahwa belanja modal tahun 2025 tercatat sebagai belanja barang. Mengapa koreksi tidak boleh dilakukan dengan mengubah DIPA tahun 2026?", 
     "Karena tahun anggaran 2025 telah audited dan closed; koreksi kesalahan tahun lalu wajib dicatat melalui akun Koreksi Ekuitas/Koreksi Nilai Aset pada modul GLP tahun berjalan", "Karena belanja tahun lalu sudah hangus", "Karena tidak ada pegawai yang mengingat transaksi tersebut", "Karena sistem menolak transaksi masa lalu secara permanen", "A", 
     "Sesuai Standar Akuntansi Pemerintahan, koreksi yang mempengaruhi neraca periode lalu dicatat langsung pada pos Ekuitas tanpa mengubah pagu belanja tahun berjalan.", reg2),
    ("Analisis Keterkaitan MonSAKTI dengan Evaluasi Reformasi Birokrasi (RB): Mengapa indikator kualitas data MonSAKTI (nihil unbalance, nihil TDK, nihil pagu minus) menjadi prasyarat penilaian indeks reformasi birokrasi satker?", 
     "Karena kualitas data keuangan yang akuntabel dan bersih mencerminkan tata kelola kepemerintahan yang baik (good public governance) dan maturitas pengendalian intern", "Karena nilai RB hanya dihitung dari kecepatan mengetik operator", "Karena KemenPAN-RB tidak memiliki indikator penilaian lain", "Agar satker mendapatkan kuota beasiswa luar negeri lebih banyak", "A", 
     "Akuntabilitas keuangan yang transparan dan tertib di MonSAKTI adalah bukti empiris berjalannya sistem integritas dan birokrasi yang bersih dan melayani.", reg2)
]

for idx, item in enumerate(t2_items):
    diff = "MUDAH" if idx < 17 else ("SEDANG" if idx < 34 else "ANALISIS")
    questions.append(q(cur_num, t2, diff, item[0], item[1], item[2], item[3], item[4], item[5], item[6], item[7]))
    cur_num += 1

print(f"Topic 2 completed. Total questions so far: {len(questions)}")

with open("scripts/p3_part2.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, indent=2, ensure_ascii=False)
