# -*- coding: utf-8 -*-
import json

def q(num, topic, diff, q_text, a, b, c, d, ans, exp, reg):
    pts = 5 if diff == 'MUDAH' else (10 if diff == 'SEDANG' else 15)
    return {
        "id": f"mbq_{num}",
        "number": num,
        "topic": topic,
        "difficulty": diff,
        "questionText": q_text,
        "optionA": a,
        "optionB": b,
        "optionC": c,
        "optionD": d,
        "correctAnswer": ans,
        "explanation": exp,
        "referenceRegulation": reg,
        "points": pts
    }

questions = []
cur_num = 1051

# ============================================================================
# TOPIC 1: IKPA - Reformulasi 2026 & Kinerja Anggaran (1051 - 1100)
# ============================================================================
t1 = "IKPA - Reformulasi 2026 & Kinerja Anggaran"
reg1 = "PER-5/PB/2022 jo Juknis IKPA DJPb Terkini"

t1_items = [
    # 17 MUDAH
    ("Berapakah jumlah indikator kinerja dalam kerangka penilaian IKPA reformulasi?", 
     "6 Indikator", "8 Indikator", "10 Indikator", "12 Indikator", "B", 
     "Sesuai reformulasi IKPA, terdapat 8 indikator kinerja yang terbagi dalam 3 aspek utama pelaksanaan anggaran.", reg1),
    ("Tiga aspek penilaian utama dalam evaluasi kinerja IKPA adalah:", 
     "Kualitas Perencanaan, Kualitas Pelaksanaan, dan Kualitas Hasil Pelaksanaan Anggaran", "Penyusunan DIPA, Penyerapan Kas, dan Audit BPK", "Modul Anggaran, Modul Komitmen, dan Modul Pembayaran", "Belanja Pegawai, Belanja Barang, dan Belanja Modal", "A", 
     "Tiga aspek evaluasi IKPA adalah Kualitas Perencanaan Anggaran, Kualitas Pelaksanaan Anggaran, dan Kualitas Hasil Pelaksanaan Anggaran.", reg1),
    ("Indikator IKPA yang mengukur deviasi rencana penarikan bulanan dengan realisasi adalah:", 
     "Revisi DIPA", "Deviasi Halaman III DIPA", "Penyerapan Anggaran", "Dispensasi SPM", "B", 
     "Deviasi Halaman III DIPA mengukur kesesuaian antara rencana penarikan dana bulanan dengan realisasi riil.", reg1),
    ("Batas maksimal toleransi deviasi per jenis belanja pada Halaman III DIPA agar mendapat nilai maksimal adalah:", 
     "5%", "10%", "15%", "20%", "A", 
     "Ambang toleransi deviasi Halaman III DIPA adalah 5% untuk setiap jenis belanja.", reg1),
    ("Berapa batas waktu pendaftaran data kontrak ke KPPN agar tidak mengurangi nilai indikator Pendaftaran Kontrak?", 
     "3 hari kerja setelah penandatanganan", "5 hari kerja setelah penandatanganan", "7 hari kerja setelah penandatanganan", "14 hari kalender setelah penandatanganan", "B", 
     "Pendaftaran kontrak ke KPPN wajib dilakukan paling lambat 5 hari kerja setelah SPK/kontrak ditandatangani.", reg1),
    ("Indikator Pengelolaan UP dan TUP dinilai berdasarkan rasio:", 
     "Ketepatan waktu dan jumlah revolving GUP minimal 100% dalam 1 bulan", "Banyaknya penolakan SPM oleh KPPN", "Jumlah saldo kas di brankas bendahara", "Persentase bunga bank rekening dinas", "A", 
     "Indikator UP dinilai dari frekuensi dan proporsi revolving GUP (minimal 100% dari pagu UP dalam 1 bulan kalender).", reg1),
    ("Berapa batas waktu penyelesaian tagihan LS nonkontraktual dari terbitnya BAST hingga persetujuan SPM?", 
     "5 hari kerja", "7 hari kerja", "14 hari kerja", "17 hari kerja", "D", 
     "Batas waktu norma penyelesaian tagihan LS non-kontraktual adalah 17 hari kerja sejak BAST/kuitansi diterbitkan.", reg1),
    ("Indikator Kualitas Hasil Pelaksanaan Anggaran dalam reformulasi IKPA dinilai melalui:", 
     "Deviasi Hal III DIPA", "Capaian Output", "Revisi DIPA", "Penyerapan Anggaran", "B", 
     "Kualitas Hasil Pelaksanaan Anggaran dinilai semata-mata dari indikator Capaian Output (konfirmasi dan pelaporan RO).", reg1),
    ("Nilai maksimal (skor sempurna) untuk masing-masing indikator pada IKPA adalah:", 
     "80", "90", "100", "120", "C", 
     "Skor maksimal per indikator dalam perhitungan IKPA adalah 100 poin.", reg1),
    ("Kapan batas akhir pemutakhiran RPD Halaman III DIPA pada setiap triwulannya?", 
     "Hari kerja kesepuluh bulan pertama triwulan berkenaan", "Akhir bulan kedua triwulan berkenaan", "Hari kerja terakhir bulan pertama triwulan berkenaan", "Awal tahun anggaran saja", "A", 
     "Pemutakhiran RPD Halaman III DIPA dibuka hingga hari kerja ke-10 atau ke-14 bulan pertama awal triwulan sesuai jadwal DJPb.", reg1),
    ("Dalam indikator Revisi DIPA, berapa batas revisi DIPA kewenangan Kanwil DJPb yang tidak mengurangi nilai IKPA per triwulan?", 
     "Maksimal 1 kali per triwulan", "Maksimal 2 kali per triwulan", "Bebas tanpa batas", "Maksimal 4 kali per tahun", "A", 
     "Frekuensi revisi DIPA yang diperkenankan tanpa mengurangi nilai adalah maksimal 1 kali dalam 1 triwulan.", reg1),
    ("Indikator Penyerapan Anggaran dinilai berdasarkan target serapan triwulanan pada jenis belanja:", 
     "Belanja Pegawai, Belanja Barang, Belanja Modal, dan Belanja Bantuan Sosial", "Hanya Belanja Barang", "Hanya Belanja Modal", "Belanja Transfer ke Daerah", "A", 
     "Target penyerapan triwulanan dihitung berbobot per jenis belanja: 51 (Pegawai), 52 (Barang), 53 (Modal), dan 57 (Bansos).", reg1),
    ("Indikator Dispensasi SPM mengukur:", 
     "Jumlah SPM yang ditolak KPPN karena salah akun", "Frekuensi pengajuan SPM yang memerlukan surat dispensasi keterlambatan", "Jumlah uang persediaan yang disetorkan kembali", "Permohonan perpanjangan masa TUP", "B", 
     "Dispensasi SPM mencatat pengajuan SPM yang melewati batas waktu norma sehingga memerlukan surat persetujuan dispensasi.", reg1),
    ("Apakah penolakan SPM oleh KPPN secara otomatis mengurangi nilai IKPA pada indikator tertentu?", 
     "Ya, langsung masuk indikator Penolakan SPM", "Tidak ada indikator penolakan SPM, namun berdampak pada keterlambatan penyelesaian tagihan dan deviasi RPD", "Penolakan SPM menghapus seluruh skor IKPA", "Penolakan SPM menambah nilai satker", "B", 
     "Dalam reformulasi IKPA, penolakan SPM tidak berdiri sendiri, namun dampaknya menurunkan indikator Penyelesaian Tagihan dan Deviasi Hal III.", reg1),
    ("Aplikasi yang digunakan sebagai dashboard utama monitoring nilai IKPA seluruh satker K/L adalah:", 
     "DJP Online", "MonSAKTI", "SIMPONI", "e-Katalog LKPP", "B", 
     "MonSAKTI menyediakan modul Monev Kinerja Pelaksanaan Anggaran dan visualisasi nilai IKPA secara real-time.", reg1),
    ("Target penyerapan anggaran Triwulan I untuk belanja operasional/barang umumnya dipatok sebesar:", 
     "10%", "15% - 20%", "50%", "75%", "B", 
     "Target serapan TW I nasional dipatok pada rentang 15% - 20% untuk mendorong percepatan perputaran ekonomi awal tahun.", reg1),
    ("Predikat 'Sangat Baik' dalam nilai akhir IKPA diberikan apabila satker memperoleh nilai kumulatif:", 
     "Nilai ≥ 75", "Nilai ≥ 85", "Nilai ≥ 95", "Nilai = 100 saja", "C", 
     "Kategori penilaian IKPA predikat Sangat Baik adalah nilai akhir IKPA ≥ 95,00.", reg1),

    # 17 SEDANG
    ("Bagaimanakah rumus perhitungan nilai Deviasi Halaman III DIPA apabila deviasi rata-rata per bulan adalah 8%?", 
     "Nilai = 100 - (8 - 5) * bobot penalti", "Nilai langsung 0", "Nilai tetap 100 karena masih di bawah 10%", "Nilai dihitung oleh KPPN secara manual", "A", 
     "Jika deviasi melampaui toleransi 5%, skor berkurang proporsional berdasarkan deviasi di atas 5% sesuai formula PER-5/PB/2022.", reg1),
    ("Satker X memiliki kontrak bernilai Rp 500 juta yang ditandatangani hari Senin 10 Mei. Kapan batas akhir pendaftaran data kontrak ke KPPN tanpa penalti?", 
     "Rabu 12 Mei", "Jumat 14 Mei", "Senin 17 Mei (5 hari kerja)", "Jumat 21 Mei", "C", 
     "Dihitung 5 hari kerja (tidak termasuk Sabtu-Minggu/hari libur) sejak penandatanganan kontrak.", reg1),
    ("Apabila satker memiliki sisa dana TUP sebesar Rp 25 juta pada akhir masa berlaku 30 hari kalender, langkah yang wajib diambil agar tidak terkena sanksi adalah:", 
     "Menyimpan uang di brankas untuk belanja bulan depan", "Menyetorkan sisa dana TUP ke Kas Negara dengan SSBP dan mengajukan LPJ TUP/PTUP", "Mengajukan SPM GUP untuk menambah saldo TUP", "Membelanjakan sisa dana tanpa kuitansi", "B", 
     "Sisa TUP wajib disetorkan kembali ke Kas Negara paling lambat hari kerja terakhir masa berlaku TUP dan dipertanggungjawabkan (PTUP).", reg1),
    ("Dalam pelaporan Capaian Output di MonSAKTI, terdapat 2 variabel utama yang wajib diinput oleh PPK yaitu:", 
     "Jumlah SP2D dan Jumlah Kuitansi", "Realisasi Volume Rincian Output (RVRO) dan Progres Capaian Rincian Output (PCRO)", "Nama vendor dan Nomor faktur pajak", "Kode akun dan Kode satker", "B", 
     "Dua variabel pengisian capaian output adalah Realisasi Volume RO (RVRO) dan Progres Capaian RO (PCRO).", reg1),
    ("Kapan batas akhir pengisian data Capaian Output bulanan di MonSAKTI sebelum penilaian dikunci?", 
     "Hari kerja pertama bulan berikutnya", "Hari kerja kelima bulan berikutnya", "Hari kerja kesepuluh bulan berikutnya", "Akhir triwulan berikutnya", "C", 
     "Pelaporan capaian output dibuka sampai dengan hari kerja ke-10 bulan berikutnya.", reg1),
    ("Apa yang menyebabkan indikator Penyelesaian Tagihan Satker mengalami penurunan skor secara drastis?", 
     "Banyak SPM yang diajukan dengan tanggal BAST lebih dari 17 hari kerja sebelumnya", "Terlalu banyak transaksi menggunakan Digipay", "Revisi DIPA dilakukan di awal triwulan", "Melakukan revolving UP dua kali sebulan", "A", 
     "Tagihan yang terlambat diajukan SPM-nya melampaui norma 17 hari kerja sejak BAST akan dikenakan penalti pada indikator ini.", reg1),
    ("Jika satker mengalami keterlambatan pendaftaran kontrak akibat gangguan sistem SAKTI terpusat, mekanisme penyelamatan nilai IKPA adalah:", 
     "Mengubah tanggal kontrak secara sepihak", "Mengajukan tiket permohonan dispensasi kedaruratan teknis ke Helpdesk Hai Kemenkeu/KPPN", "Menghapus kontrak dari sistem", "Membayar kontrak menggunakan kas UP tunai", "B", 
     "Kendala teknis sistemik dapat diajukan tiket kedaruratan/dispensasi teknis ke Ditjen Perbendaharaan untuk pengecualian penilaian.", reg1),
    ("Dalam penghitungan indikator Penyerapan Anggaran, jika realisasi belanja modal hanya mencapai 60% dari target triwulan, dampaknya adalah:", 
     "Skor penyerapan belanja modal proporsional 60/100 dikalikan bobot jenis belanja berkenaan", "Nilai IKPA satker langsung didiskualifikasi", "Satker wajib mengembalikan sisa belanja modal", "Kepala satker diberhentikan", "A", 
     "Skor penyerapan dihitung proporsional dari persentase ketercapaian terhadap target trajektori triwulanan.", reg1),
    ("Bagaimana cara satker meminimalkan Deviasi Halaman III DIPA jika jadwal pengadaan mengalami pergeseran waktu?", 
     "Membiarkan saja karena sudah tercetak di DIPA awal", "Melakukan pemutakhiran RPD Hal III DIPA pada periode reguler awal triwulan melalui revisi administratif", "Meminjam dana pihak ketiga", "Mengubah tanggal DIPA secara mandiri", "B", 
     "Satker wajib memanfaatkan periode pemutakhiran RPD triwulanan untuk menyelaraskan jadwal kas dengan pergeseran kegiatan.", reg1),
    ("Syarat agar revolving UP (GUP) dihitung optimal dalam indikator Pengelolaan UP dan TUP adalah:", 
     "Besaran penggantian UP minimal 100% dari pagu UP dalam 1 bulan kalender", "GUP diajukan cukup 1 kali per semester", "UP tidak pernah digunakan sama sekali", "UP disimpan dalam bentuk valuta asing", "A", 
     "Optimalisasi UP dinilai dari frekuensi dan rasio revolving yang mencapai minimal 100% dari besaran pagu UP dalam satu bulan.", reg1),
    ("Dalam hal terjadi penolakan pendaftaran kontrak oleh KPPN karena perbedaan data supplier, maka:", 
     "Kontrak dibatalkan demi hukum", "Satker wajib memperbaiki supplier dan mendaftarkan kembali, waktu pendaftaran tetap dihitung sejak tanggal kontrak awal", "Tanggal kontrak otomatis berubah", "Penyedia barang terkena denda keterlambatan", "B", 
     "Penolakan pendaftaran mengharuskan perbaikan segera; hitungan 5 hari kerja tetap merujuk pada tanggal penandatanganan kontrak asli.", reg1),
    ("Pada indikator Capaian Output, apa yang dimaksud dengan anomali data capaian output?", 
     "Realisasi anggaran 90% tetapi progres fisik 0%, atau progres fisik 100% tetapi realisasi anggaran 0% tanpa justifikasi rasional", "Realisasi anggaran sama persis dengan progres fisik", "Penginputan data tepat waktu sebelum tanggal 10", "Satker memiliki lebih dari 5 output prioritas", "A", 
     "Anomali output terjadi jika terdapat kesenjangan ekstrem antara penyerapan anggaran dan capaian progres fisik yang tidak logis.", reg1),
    ("Jika KPA mengajukan revisi DIPA ke Kanwil DJPb pada tanggal 25 Maret untuk Triwulan I, apakah revisi tersebut mengurangi nilai IKPA Triwulan I?", 
     "Tidak, jika revisi tersebut merupakan revisi pertama satker di Triwulan I", "Ya, setiap revisi pasti mengurangi nilai 50%", "Tidak, revisi di bulan Maret selalu bebas penalti", "Ya, karena diajukan di akhir triwulan", "A", 
     "Sesuai regulasi, revisi DIPA pertama dalam satu triwulan mendapatkan toleransi nilai 100 (tidak ada pengurangan).", reg1),
    ("Apa konsekuensi apabila satker tidak melaporkan Capaian Output di MonSAKTI hingga batas akhir?", 
     "Nilai indikator Capaian Output satker menjadi 0 (nol) untuk periode tersebut", "Satker dibekukan akses SAKTI-nya", "Semua pejabat satker dipotong tunjangan", "KPPN menghentikan pembayaran gaji", "A", 
     "Ketidakhadiran pelaporan capaian output menyebabkan nilai indikator Capaian Output menjadi nol, yang berbobot sangat tinggi pada IKPA.", reg1),
    ("Manakah indikator dalam IKPA yang memiliki bobot penilaian tertinggi pada aspek kualitas pelaksanaan?", 
     "Dispensasi SPM", "Penyerapan Anggaran dan Deviasi Hal III DIPA", "Revisi DIPA", "Pengelolaan Rekening", "B", 
     "Penyerapan Anggaran (20%) dan Deviasi Halaman III DIPA (15%) memegang porsi bobot paling signifikan.", reg1),
    ("Perhitungan indikator Pendaftaran Kontrak didasarkan pada:", 
     "Rasio jumlah kontrak yang didaftarkan tepat waktu (≤ 5 HK) terhadap total seluruh kontrak yang didaftarkan", "Total nominal rupiah kontrak yang dimenangkan BUMN", "Jumlah vendor yang mengikuti tender", "Nilai pagu belanja modal satker", "A", 
     "Skor = (Jumlah kontrak tepat waktu ≤ 5 HK / Total kontrak) x 100.", reg1),
    ("Jika satker memperoleh nilai IKPA 98,40 pada akhir tahun anggaran, penghargaan atau implikasi yang diterima satker adalah:", 
     "Mendapat piagam apresiasi KPPN/Kanwil dan pertimbangan fleksibilitas tata kelola anggaran", "Mendapat tambahan pagu bebas pajak", "Dikecualikan dari pemeriksaan BPK", "Tidak perlu menyusun Laporan Keuangan", "A", 
     "Nilai IKPA kategori Sangat Baik menjadi rujukan prestasi kerja satker, penghargaan Kemenkeu, dan penilaian reformasi birokrasi K/L.", reg1),

    # 16 ANALISIS
    ("Analisis Kasus Deviasi Halaman III DIPA Satker Balai Riset: Pada bulan Mei, satker merencanakan penarikan belanja barang Rp 500 juta, namun realisasinya hanya Rp 100 juta karena kegiatan seminar ditunda ke bulan Juli. Penyebab utama anjloknya skor Deviasi Hal III DIPA satker adalah:", 
     "Satker tidak melakukan penyesuaian RPD Hal III DIPA pada periode pemutakhiran awal Triwulan II", "Seminar diselenggarakan secara online", "KPPN menolak pencairan uang persediaan", "Peserta seminar tidak hadir tepat waktu", "A", 
     "Kegagalan mengantisipasi perubahan jadwal kegiatan dan tidak memutakhirkan RPD Hal III DIPA pada awal triwulan menimbulkan deviasi 80% yang merusak skor IKPA.", reg1),
    ("Analisis Kasus Keterlambatan Pendaftaran Kontrak Multi-Tahun: PPK menandatangani kontrak pekerjaan jembatan tanggal 1 April, namun pendaftaran karwas kontrak ke KPPN baru dikirim tanggal 15 April. Alasan PPK karena menunggu jaminan pelaksanaan fisik dari asuransi. Solusi preventif yang benar sesuai regulasi adalah:", 
     "Jaminan pelaksanaan wajib diserahkan sebelum penandatanganan kontrak sehingga pendaftaran SAKTI ke KPPN dapat diajukan dalam tempo ≤ 5 hari kerja", "Mengubah tanggal kontrak menjadi tanggal 14 April", "Membayar jembatan secara bertahap dengan UP", "Menunggu proyek selesai 100% baru didaftarkan", "A", 
     "Pasal 33 Perpres 16/2018 mengatur Jaminan Pelaksanaan diserahkan penyedia sebelum penandatanganan kontrak; menunda pendaftaran melanggar batas 5 HK.", reg1),
    ("Analisis Kasus Bottleneck Penyelesaian Tagihan LS: Satker mencatat 40 BAST ditandatangani tanggal 1 November, namun SPM LS baru disetujui tanggal 28 November (20 hari kerja). Alasan verifikator adalah antrian dokumen fisik yang menumpuk. Evaluasi perbaikan tata kelola internal yang tepat adalah:", 
     "Menerapkan otomasi verifikasi bertahap dan monitoring alert jatuh tempo H-5 di SAKTI agar SPM terbit sebelum batas 17 hari kerja", "Meminta penyedia merevisi tanggal BAST mundur ke akhir bulan", "Menolak seluruh tagihan penyedia", "Mengalihkan pembayaran menjadi sistem ganti uang persediaan", "A", 
     "Norma 17 HK wajib dikawal dengan sistem early warning pergerakan dokumen verifikasi belanja di SAKTI untuk mencegah penumpukan di akhir batas waktu.", reg1),
    ("Studi Kasus Penolakan SPM Berulang: KPPN menolak SPM LS Satker Pendidikan 3 kali berturut-turut karena kesalahan penulisan nomor rekening bank dan ketidaksesuaian akun belanja. Dampak sistemik kasus ini terhadap kinerja anggaran satker adalah:", 
     "Jatuh tempo pembayaran melewati 17 hari kerja, menghambat hak penyedia, dan memicu deviasi jadwal kas Halaman III DIPA", "KPPN memblokir seluruh rekening dinas satker", "Penyedia barang dipailitkan secara sepihak", "DIPA satker dicabut oleh Kementerian Keuangan", "A", 
     "Penolakan SPM menunda pencairan riil, memperburuk rasio penyelesaian tagihan (BAST kadaluwarsa), dan mengacaukan kesesuaian penarikan dana bulanan.", reg1),
    ("Analisis Anomali Capaian Output Satker Pembangunan Gedung: Hingga Triwulan III, realisasi anggaran belanja modal gedung telah mencapai 95%, namun PCRO yang dilaporkan hanya 35%. MonSAKTI menandai data ini sebagai anomali 'Low PCRO High Budget'. Tindakan audit kepatuhan yang harus dilakukan KPA adalah:", 
     "Memeriksa apakah telah terjadi pembayaran termin mendahului prestasi fisik pekerjaan riil di lapangan (kelebihan bayar)", "Mengubah progres fisik di sistem menjadi 95% secara manual tanpa cek lapangan", "Menghentikan tukang bangunan bekerja", "Menutup akun MonSAKTI pejabat terkait", "A", 
     "Kesenjangan anggaran tinggi namun fisik rendah merupakan sinyal bahaya fraud/kelebihan bayar mendahului prestasi kerja yang memerlukan investigasi fisik.", reg1),
    ("Analisis Kasus Satker Baru Operasional: Satker baru mendapatkan DIPA di bulan Agustus. Bagaimana strategi satker mengoptimalkan indikator Pengelolaan UP dan TUP dalam waktu 4 bulan tersisa?", 
     "Segera mengajukan UP perdana, merotasi belanja operasional rutin, dan mengajukan GUP tepat waktu minimal 100% dari pagu UP setiap bulannya", "Mengajukan UP maksimal lalu menyimpannya utuh di brankas", "Menghabiskan seluruh anggaran dengan mekanisme LS fiktif", "Menolak menggunakan UP dan hanya memakai dana talangan pribadi", "A", 
     "Optimalisasi UP memerlukan perputaran belanja cepat dan penggantian revolving (GUP) teratur sebesar minimal 100% pagu UP per siklus bulanan.", reg1),
    ("Analisis Penalti Dispensasi SPM Akhir Tahun: Pada tanggal 28 Desember, Satker mengajukan 5 SPM yang melewati batas waktu LLAT sehingga memerlukan surat dispensasi Kepala KPPN. Pengaruh penerbitan dispensasi ini terhadap skor IKPA satker adalah:", 
     "Skor indikator Dispensasi SPM akan terpotong sesuai jumlah frekuensi surat dispensasi yang diterbitkan", "Nilai IKPA satker langsung berubah menjadi 100", "Tidak ada pengaruh apapun karena dispensasi disetujui", "Satker wajib membayar denda kas negara sebesar 5% dari nilai SPM", "A", 
     "Setiap surat dispensasi keterlambatan yang diterbitkan KPPN akan memotong poin indikator Dispensasi SPM pada evaluasi tahun berjalan.", reg1),
    ("Analisis Komparasi Kinerja Satker A dan Satker B: Satker A memiliki serapan anggaran 99% tetapi nilai IKPA 82, sedangkan Satker B serapan anggarannya 92% tetapi nilai IKPA 96. Mengapa Satker B dinilai berkinerja lebih unggul?", 
     "Karena Satker B unggul dalam disiplin perencanaan (deviasi Hal III rendah), ketepatan waktu pendaftaran kontrak, nihil dispensasi, dan capaian output akurat", "Karena Satker B menyuap tim penilai KPPN", "Karena Satker A memiliki anggaran yang terlalu kecil", "Karena sistem penilaian salah menghitung skor", "A", 
     "IKPA mengukur tata kelola menyeluruh (kualitas belanja, ketepatan waktu, dan output), bukan sekadar menghabiskan uang secara ugal-ugalan di akhir tahun.", reg1),
    ("Analisis Kasus Revisi DIPA Otomatis (Automatic Adjustment): Apabila pemerintah menerapkan kebijakan pencadangan belanja (Automatic Adjustment), bagaimana satker menjaga agar nilai indikator Penyerapan Anggaran tidak anjlok?", 
     "Melakukan penyesuaian target penyerapan terhadap pagu efektif yang tidak diblokir melalui mekanisme yang diatur dalam regulasi monev DJPb", "Memaksa mencairkan anggaran yang sedang diblokir", "Menghapus target output yang telah tercapai", "Meminjam dana dari bank umum", "A", 
     "Penyusuaian perhitungan berbasis pagu efektif (setelah dikurangi blokir/AA) diatur DJPb agar penilaian penyerapan anggaran mencerminkan keadilan manajerial.", reg1),
    ("Analisis Kasus Satker Wilayah Kepulauan Terpencil: Satker di pulau terluar sering terlambat mendaftarkan kontrak akibat jaringan internet padam selama 1 minggu. Upaya mitigasi administratif yang sah agar tidak terkena penalti IKPA adalah:", 
     "Menyampaikan surat pemberitahuan kendala force majeure jaringan disertai bukti log teknis kepada KPPN untuk penetapan dispensasi gangguan teknis", "Mengirim kurir dengan perahu membawa uang tunai tanpa dokumen", "Memalsukan tanda tangan pejabat KPPN", "Membatalkan seluruh kegiatan pengadaan", "A", 
     "Regulasi perbendaharaan mengakomodasi keadaan force majeure/gangguan teknis jaringan dengan mekanisme pelaporan resmi dan persetujuan dispensasi teknis.", reg1),
    ("Analisis Kasus Kesenjangan Capaian Output (High PCRO Low Budget): Satker Penyuluhan Pertanian mencatat progres fisik mencapai 100% di Triwulan II, namun penyerapan anggaran baru 20%. Penjelasan logis dan valid yang dapat diterima adalah:", 
     "Penyuluhan dilakukan melalui kolaborasi daring dan fasilitas mitra tanpa biaya besar, atau tagihan operasional pihak ketiga belum diajukan SPM-nya", "Satker memalsukan laporan capaian output", "KPPN belum mentransfer uang gaji penyuluh", "Uang belanja dialihkan untuk membeli valas", "A", 
     "Pencapaian fisik mendahului belanja dapat terjadi pada kegiatan efisiensi non-fisik/swakelola, namun harus diverifikasi agar tagihan riil segera diselesaikan.", reg1),
    ("Analisis Dampak Reformulasi IKPA terhadap Efisiensi Fiskal: Mengapa reformulasi IKPA memberikan bobot penalti signifikan pada kegagalan penyerapan anggaran berbasis belanja modal dibandingkan belanja pegawai?", 
     "Karena belanja modal memiliki efek berganda (multiplier effect) tinggi bagi pembangunan infrastruktur dan pertumbuhan ekonomi nasional", "Karena belanja pegawai tidak penting bagi perekonomian", "Karena belanja modal tidak memerlukan bukti kuitansi", "Karena belanja modal ditentukan oleh perbankan swasta", "A", 
     "Belanja modal adalah penggerak utama pertumbuhan ekonomi dan fasilitas publik; keterlambatan penyerapan modal berdampak langsung pada kesejahteraan rakyat.", reg1),
    ("Analisis Kasus Restrukturisasi RPD Triwulan IV: Mengapa satker dilarang menumpuk rencana penarikan dana di bulan Desember lebih dari 40% dari total pagu tahunan?", 
     "Karena memicu lonjakan SPM akhir tahun (fiscal cliff), meningkatkan beban likuiditas kas negara, dan risiko kegagalan verifikasi dokumen belanja", "Karena kas negara kosong di bulan Desember", "Karena kantor KPPN tutup di awal Desember", "Karena hari libur nasional terlalu banyak", "A", 
     "Penumpukan belanja di akhir tahun membahayakan likuiditas Kas Negara, membebani kapasitas perbankan, dan meningkatkan risiko moral hazard pengadaan kilat.", reg1),
    ("Analisis Pengawasan Internal KPA Berbasis Dashboard MonSAKTI: Apa fungsi strategis matriks 'To Do List' pada MonSAKTI bagi KPA?", 
     "Menampilkan daftar tagihan mendekati 17 HK, kontrak mendekati 5 HK, dan batas waktu pengisian output sehingga pencegahan penalti dapat dilakukan seketika", "Mencatat absensi harian pegawai satker", "Mengirim pesan promosi barang dan jasa swasta", "Menggantikan peran audit laporan BPK", "A", 
     "Fitur To Do List MonSAKTI berfungsi sebagai early warning system interaktif untuk mencegah keterlambatan transaksi yang berpotensi menurunkan IKPA.", reg1),
    ("Analisis Kasus Transaksi GUP Nihil pada Akhir Tahun: Mengapa satker yang tidak melakukan revolving GUP Nihil hingga batas waktu LLAT dapat dijatuhi sanksi pemotongan pagu UP tahun berikutnya?", 
     "Karena sisa kas UP yang tidak dipertanggungjawabkan/disetorkan menjadi temuan ketekoran kas dan mengganggu penyusunan Neraca Laporan Keuangan BUN", "Karena bank operasional menolak melayani satker", "Karena kepala daerah akan menerbitkan surat teguran", "Karena uang tersebut hangus otomatis", "A", 
     "Pertanggungjawaban GUP Nihil dan penyetoran sisa UP mutlak diperlukan untuk memastikan saldo kas pada neraca akhir tahun bernilai nol dan valid.", reg1),
    ("Analisis Efektivitas Pengelolaan KKP terhadap Nilai IKPA: Mengapa penggunaan Kartu Kredit Pemerintah (KKP) Domestik secara intensif berkontribusi positif terhadap kinerja pelaksanaan anggaran?", 
     "Meningkatkan efisiensi kas, mempercepat revolving UP KKP tanpa idle cash fisik di brankas, serta mendorong transparansi jejak transaksi digital", "Menghapus kewajiban membayar pajak belanja", "Memberikan cashback pribadi bagi pemegang kartu kredit", "Membebaskan satker dari pembuatan kuitansi belanja", "A", 
     "Penggunaan KKP memitigasi idle cash, mempercepat siklus revolving uang persediaan, dan menyediakan audit trail digital yang transparan dan akuntabel.", reg1)
]

for idx, item in enumerate(t1_items):
    diff = "MUDAH" if idx < 17 else ("SEDANG" if idx < 34 else "ANALISIS")
    questions.append(q(cur_num, t1, diff, item[0], item[1], item[2], item[3], item[4], item[5], item[6], item[7]))
    cur_num += 1

print(f"Topic 1 completed. Total questions so far: {len(questions)}")

with open("scripts/p3_part1.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, indent=2, ensure_ascii=False)
