const fs = require('fs');
const path = require('path');

// Helper to create question object
function q(id, number, topic, difficulty, questionText, optionA, optionB, optionC, optionD, correctAnswer, explanation, referenceRegulation) {
  const points = difficulty === 'MUDAH' ? 5 : difficulty === 'SEDANG' ? 10 : 15;
  return {
    id: `mbq_${number}`,
    number,
    topic,
    difficulty,
    questionText,
    optionA,
    optionB,
    optionC,
    optionD,
    correctAnswer,
    explanation,
    referenceRegulation,
    points
  };
}

const part3Questions = [];
let currentNumber = 1051;

// ============================================================================
// TOPIC 1: IKPA - Reformulasi 2026 & Kinerja Anggaran (50 Questions)
// ============================================================================
const t1 = "IKPA - Reformulasi 2026 & Kinerja Anggaran";
const t1_reg = "PER-5/PB/2022 jo Petunjuk Teknis IKPA DJPb Terkini";

// 17 MUDAH
const t1_mudah = [
  ["Berapa jumlah indikator utama dalam penilaian Indikator Kinerja Pelaksanaan Anggaran (IKPA) sesuai reformulasi?",
   "6 Indikator", "8 Indikator", "10 Indikator", "12 Indikator", "B",
   "Sesuai reformulasi IKPA, terdapat 8 indikator kinerja pelaksanaan anggaran yang terbagi dalam 3 aspek."],
  ["Tiga aspek utama dalam evaluasi IKPA meliputi:",
   "Kualitas Perencanaan, Kualitas Pelaksanaan, dan Kualitas Hasil Pelaksanaan Anggaran", "Penyusunan Renja, Pemeriksaan BPK, dan Laporan Keuangan", "Pengadaan Barang, Pembayaran Gaji, dan Audit Internal", "Input SAKTI, Verifikasi SP2D, dan Penyetoran Pajak", "A",
   "Tiga aspek pengukuran IKPA adalah Kualitas Perencanaan Anggaran, Kualitas Pelaksanaan Anggaran, dan Kualitas Hasil Pelaksanaan Anggaran."],
  ["Indikator yang mengukur kesesuaian antara rencana penarikan dana bulanan dengan realisasi adalah:",
   "Revisi DIPA", "Halaman III DIPA", "Penyerapan Anggaran", "Dispensasi SPM", "B",
   "Indikator Deviasi Halaman III DIPA mengukur kesesuaian antara penarikan dana bulanan yang direncanakan dengan realisasi anggarannya."],
  ["Ambang batas maksimal deviasi bulanan Halaman III DIPA per jenis belanja agar memperoleh nilai 100 adalah:",
   "Maksimal 5%", "Maksimal 10%", "Maksimal 15%", "Maksimal 20%", "A",
   "Toleransi deviasi bulanan RPD Halaman III DIPA adalah maksimal 5% untuk mendapatkan nilai maksimal (100)."],
  ["Berapa kali batas frekuensi revisi DIPA kewenangan Kanwil DJPb/DJA per triwulan agar nilai indikator tetap 100?",
   "Maksimal 1 kali", "Maksimal 2 kali", "Maksimal 3 kali", "Tidak ada batasan", "A",
   "Satker diperkenankan melakukan revisi DIPA kewenangan Kanwil DJPb/DJA maksimal 1 kali dalam 1 triwulan kalender untuk nilai maksimal."],
  ["Berapa hari kerja batas waktu pendaftaran data perjanjian kontrak ke KPPN terhitung sejak tanggal kontrak ditandatangani?",
   "3 hari kerja", "5 hari kerja", "7 hari kerja", "14 hari kalender", "B",
   "Pendaftaran kontrak ke KPPN wajib dilakukan paling lambat 5 hari kerja sejak tanggal penandatanganan kontrak."],
  ["Berapa hari kerja batas waktu penerbitan SPM-LS ke KPPN terhitung sejak timbulnya hak tagih (BAST/BAPP)?",
   "7 hari kerja", "10 hari kerja", "14 hari kerja", "17 hari kerja", "D",
   "Batas waktu penyelesaian tagihan pihak ketiga adalah 17 hari kerja sejak timbulnya hak tagih (BAST/BAPP disahkan)."],
  ["Berapa minimal persentase revolving (penggantian) dana Uang Persediaan (UP) dalam 1 bulan kalender?",
   "25% dari pagu UP", "50% dari pagu UP", "75% dari pagu UP", "100% dari pagu UP", "B",
   "Ketentuan revolving UP adalah satker harus mengajukan GUP minimal 50% dari total besaran pagu UP dalam 1 bulan."],
  ["Target minimal penyerapan anggaran kumulatif untuk Belanja Barang pada akhir Triwulan I adalah sebesar:",
   "10%", "15%", "20%", "25%", "B",
   "Sesuai target kinerja IKPA, target penyerapan belanja barang pada triwulan I minimal adalah 15%."],
  ["Target minimal penyerapan anggaran kumulatif untuk Belanja Modal pada akhir Triwulan II adalah sebesar:",
   "30%", "40%", "50%", "60%", "B",
   "Target kumulatif penyerapan belanja modal pada akhir Triwulan II adalah minimal 40%."],
  ["Kapan batas waktu penyampaian data capaian output bulanan ke KPPN melalui aplikasi SAKTI?",
   "Tanggal 5 hari kerja bulan berikutnya", "Tanggal 10 hari kerja bulan berikutnya", "Tanggal 15 hari kalender bulan berikutnya", "Akhir bulan berjalan", "A",
   "Pelaporan data capaian output bulanan disampaikan paling lambat 5 hari kerja pada bulan berikutnya."],
  ["Indikator Dispensasi SPM pada IKPA bertujuan untuk:",
   "Mendorong satker mengajukan SPM di luar jam kerja", "Mencegah penumpukan SPM dan keterlambatan pengajuan di akhir tahun anggaran", "Mempercepat proses lelang barang dan jasa", "Mengurangi jumlah pagu anggaran yang belum terserap", "B",
   "Indikator Dispensasi SPM mengukur kedisiplinan satker agar tidak mengajukan SPM melampaui batas waktu yang ditentukan tanpa alasan darurat."],
  ["Bobot penilaian indikator Kualitas Pelaksanaan Anggaran dalam IKPA merupakan:",
   "Bobot terkecil", "Bobot terbesar (55%)", "Sama dengan perencanaan", "Tidak memiliki bobot", "B",
   "Aspek Kualitas Pelaksanaan Anggaran memiliki porsi bobot terbesar dalam penilaian keseluruhan IKPA."],
  ["Satker yang memiliki nilai IKPA kategori 'Sangat Baik' berada pada rentang nilai:",
   "Nilai 85 s.d. 89", "Nilai 90 s.d. 94", "Nilai 95 s.d. 100", "Nilai di atas 80", "C",
   "Predikat 'Sangat Baik' diberikan kepada Satker yang berhasil meraih nilai IKPA 95 sampai dengan 100."],
  ["Apa yang dimaksud dengan PCRO dalam pengukuran Indikator Capaian Output?",
   "Penyerapan Cepat Realisasi Operasional", "Progres Capaian Rincian Output", "Pengawasan Capaian Realisasi Output", "Pengukuran Capaian Rencana Organisasi", "B",
   "PCRO adalah Progres Capaian Rincian Output yang menunjukkan persentase progres fisik pelaksanaan kegiatan."],
  ["Apa yang dimaksud dengan RVRO dalam pengukuran Indikator Capaian Output?",
   "Realisasi Volume Rincian Output", "Rencana Validasi Realisasi Output", "Realisasi Verifikasi Rencana Operasi", "Rincian Volume Realisasi Organisasi", "A",
   "RVRO adalah Realisasi Volume Rincian Output yang mengukur jumlah satuan fisik output yang telah berhasil diselesaikan."],
  ["Apakah pengajuan revisi administrasi petunjuk operasional kegiatan (POK) mengurangi nilai IKPA Revisi DIPA?",
   "Ya, selalu mengurangi 5 poin", "Tidak, revisi POK kewenangan KPA tidak dihitung dalam frekuensi revisi DIPA", "Ya, jika diajukan lebih dari sekali", "Tergantung persetujuan KPPN", "B",
   "Revisi POK merupakan kewenangan internal KPA dan tidak tercatat sebagai revisi DIPA pada Ditjen Perbendaharaan/DJA sehingga tidak mengurangi nilai."]
];

t1_mudah.forEach(item => {
  part3Questions.push(q(`mbq_${currentNumber}`, currentNumber++, t1, "MUDAH", item[0], item[1], item[2], item[3], item[4], item[5], item[6], t1_reg));
});

// 17 SEDANG
const t1_sedang = [
  ["Satker BPS memiliki pagu UP Rp100.000.000. Dalam bulan Maret, satker melakukan belanja UP sebesar Rp30.000.000 dan mengajukan SPM-GUP pada 28 Maret. Berapakah status kepatuhan revolving UP satker tersebut?",
   "Patuh, karena ada pengajuan GUP sebelum akhir bulan", "Tidak optimal, karena revolving baru mencapai 30% (di bawah batas minimal 50%)", "Mendapat sanksi pemotongan UP sebesar 50%", "Otomatis nilai IKPA menjadi nol", "B",
   "Untuk mendapatkan nilai maksimal 100 pada indikator UP, revolving minimal adalah 50% dari pagu UP dalam satu bulan."],
  ["PPK menandatangani kontrak pengadaan senilai Rp250.000.000 pada hari Senin tanggal 3 November. Tanpa adanya hari libur nasional, kapan batas hari kerja terakhir pendaftaran CAN/Karwas Kontrak ke KPPN?",
   "Kamis, 6 November", "Jumat, 7 November", "Senin, 10 November", "Selasa, 11 November", "C",
   "Batas waktu pendaftaran adalah 5 hari kerja: Selasa (1), Rabu (2), Kamis (3), Jumat (4), Senin 10 November (5)."],
  ["BAST pekerjaan pengadaan komputer ditandatangani pada tanggal 1 Oktober. Karena kelalaian staf penguji, SPM-LS baru diterbitkan dan dikirim ke KPPN pada hari kerja ke-19. Dampak langsung bagi Satker adalah:",
   "KPPN menolak SPM secara permanen", "Tagihan dibatalkan oleh sistem SPAN", "Satker terkena penalti keterlambatan pada indikator Penyelesaian Tagihan IKPA", "Penyedia barang dikenakan denda keterlambatan", "C",
   "Keterlambatan penyampaian SPM melampaui 17 hari kerja menurunkan rasio ketepatan waktu penyelesaian tagihan pada IKPA satker."],
  ["Satker mengajukan revisi Halaman III DIPA pada awal triwulan III. Kapan batas waktu pemutakhiran RPD Hal III DIPA triwulanan agar diakui dalam penilaian IKPA?",
   "Paling lambat 10 hari kerja setelah triwulan dimulai", "Sesuai jadwal pembukaan pemutakhiran RPD Triwulanan oleh Ditjen Perbendaharaan (biasanya hari kerja ke-10 atau ke-15 awal triwulan)", "Setiap hari Jumat sebelum jam 15.00 WIB", "Akhir bulan kedua pada triwulan berjalan", "B",
   "Pemutakhiran RPD Halaman III DIPA triwulanan dibuka secara terjadwal pada awal triwulan sesuai surat edaran Dirjen Perbendaharaan."],
  ["Satker Dinas Pertanian memiliki realisasi anggaran Triwulan I sebesar 18% dari pagu, Triwulan II 48%, Triwulan III 72%, dan Triwulan IV 96%. Bagaimanakah penilaian penyerapan anggaran Triwulan II jika target belanja operasional adalah 50%?",
   "Nilai 100 karena deviasinya kecil", "Mendapat nilai proporsional karena realisasi 48% berada di bawah target minimal 50%", "Nilai otomatis 0 karena tidak mencapai target", "Diberikan dispensasi otomatis", "B",
   "Penyerapan yang berada di bawah target triwulanan dihitung secara proporsional sesuai rasio realisasi terhadap target."],
  ["Jika dalam 1 triwulan kalender satker melakukan revisi DIPA kewenangan Kanwil DJPb sebanyak 2 kali, berapakah nilai IKPA pada indikator Revisi DIPA triwulan tersebut?",
   "Nilai 100", "Nilai 95 s.d. 90", "Nilai 80 s.d. 75", "Nilai 50", "B",
   "Revisi DIPA kedua dalam satu triwulan akan mengurangi skor indikator dari 100 menjadi sekitar 90-95 sesuai rumus penalti."],
  ["Satker mengajukan 1 SPM pada bulan Desember dengan surat dispensasi persetujuan keterlambatan dari Kepala KPPN. Pengaruhnya terhadap nilai IKPA akhir tahun adalah:",
   "Tidak berpengaruh jika dispensasi disetujui", "Mengurangi nilai indikator Dispensasi SPM secara langsung sesuai bobot penalti jumlah SPM dispensasi", "Membuat seluruh nilai IKPA dibatalkan", "Menaikkan nilai karena berhasil mencairkan dana", "B",
   "Penerbitan dispensasi tetap dicatat sebagai pelanggaran timeline yang mengurangi poin indikator Dispensasi SPM."],
  ["Bagaimana cara Satker mempertahankan nilai 100 pada Indikator Capaian Output jika kegiatan baru dimulai pada Triwulan III?",
   "Mengisi progres fisik 100% secara fiktif di Triwulan I", "Melaporkan data capaian riil tepat waktu setiap bulan sesuai progres tahapan (PCRO) dan menjelaskan kendala pada kolom keterangan", "Tidak perlu melapor hingga akhir tahun", "Menghapus target output di SAKTI", "B",
   "Ketepatan waktu pelaporan data riil setiap bulan menjamin nilai indikator pelaporan capaian output tetap optimal."],
  ["Data anomali capaian output (misal realisasi anggaran 90% tetapi PCRO baru 5%) akan berakibat:",
   "Konfirmasi otomatis ke BPK", "Terbitnya notifikasi anomali/gap kinerja di MonSAKTI yang mengurangi penilaian kualitas capaian output jika tidak dikonfirmasi", "SP2D ditarik kembali ke kas negara", "Pemblokiran user PPK di SAKTI", "B",
   "Anomali gap antara anggaran dan fisik di MonSAKTI harus dikonfirmasi agar tidak menurunkan validitas capaian output."],
  ["Satker melakukan perikatan pengadaan langsung senilai Rp45.000.000 dengan Surat Perintah Kerja (SPK). Apakah kontrak ini wajib didaftarkan ke KPPN dalam waktu 5 hari kerja?",
   "Wajib, semua transaksi berapapun nilainya wajib didaftarkan", "Tidak wajib didaftarkan sebagai data kontrak ke KPPN jika dibayarkan melalui mekanisme UP/TUP atau SPM-LS Nonkontraktual di bawah Rp50 juta", "Wajib didaftarkan dalam waktu 1 hari", "Tergantung kemauan penyedia", "B",
   "Komitmen yang dibayarkan melalui UP atau LS non-kontraktual di bawah threshold kontrak tidak wajib didaftarkan di modul komitmen KPPN."],
  ["Apa yang menjadi faktor utama penyebab rendahnya nilai indikator Deviasi Halaman III DIPA pada satker vertikal?",
   "Pagu anggaran yang terlalu besar", "Kurangnya koordinasi internal antara pejabat pembuat komitmen dengan pengelola keuangan saat menyusun RPD awal tahun", "Bunga bank yang berfluktuasi", "Adanya audit dari inspektorat jenderal", "B",
   "Deviasi tinggi umumnya disebabkan penyusunan RPD Hal III DIPA yang copy-paste tanpa sinkronisasi jadwal pengadaan PPK."],
  ["Dalam aplikasi MonSAKTI, menu apakah yang digunakan untuk memantau nilai sementara dan detail transaksi seluruh indikator IKPA?",
   "Menu Monitoring Kontrak", "Menu Monev Kinerja IKPA", "Menu Administrator User", "Menu Neraca Percobaan", "B",
   "Menu Monev Kinerja IKPA pada MonSAKTI menyajikan rekapitulasi skor, tren nilai bulanan, dan detil data bermasalah."],
  ["Apabila satker memiliki sisa dana TUP sebesar Rp15.000.000 pada batas akhir 30 hari kalender, tindakan yang benar agar tidak merusak IKPA adalah:",
   "Menyimpan uang di brankas bendahara untuk bulan berikutnya", "Menyetorkan sisa TUP ke Kas Negara dengan SSPB sebelum batas waktu berakhir dan mempertanggungjawabkannya dengan SPM-PTUP", "Menggunakan dana tersebut untuk kegiatan lain di luar rincian kebutuhan TUP", "Meminta izin lisan kepada KPPN", "B",
   "Sisa TUP wajib disetor ke kas negara dan di-PTUP-kan tepat waktu agar indikator pengelolaan UP/TUP tidak terkena penalti."],
  ["Berapa batas waktu pertanggungjawaban TUP (SPM-PTUP) sejak tanggal SP2D TUP diterbitkan?",
   "14 hari kalender", "30 hari kalender", "60 hari kalender", "90 hari kalender", "B",
   "Sesuai PMK tata cara pembayaran, pertanggungjawaban TUP wajib diselesaikan maksimal dalam 30 hari kalender."],
  ["Satker mendapatkan hibah langsung dalam bentuk uang dari lembaga internasional. Apakah penyerapan belanja hibah ini dinilai dalam IKPA?",
   "Tidak, dana hibah dikecualikan sepenuhnya dari evaluasi kinerja", "Ya, setelah direvisi masuk ke dalam DIPA dan disahkan melalui SP2HL/SP4HL", "Hanya dinilai jika nilainya di atas Rp10 miliar", "Dinilai berdasarkan persetujuan menteri luar negeri", "B",
   "Dana hibah yang telah masuk DIPA dan teregister dinilai sesuai mekanisme pelaksanaan anggaran standar."],
  ["Jika satker memiliki pagu minus pada akhir bulan, apa dampaknya terhadap indikator IKPA dan penyusunan SPM?",
   "Tidak ada dampak selama minus di bawah Rp1 juta", "Pagu minus memblokir validasi SPM di SAKTI dan menunjukkan kelemahan perencanaan anggaran", "KPPN otomatis memberikan tambahan pagu", "Satker mendapat piagam penghargaan efisiensi", "B",
   "Pagu minus menyebabkan validasi pengeluaran gagal dan mencerminkan ketidaksesuaian alokasi anggaran."],
  ["Indikator Belanja Kontraktual dalam IKPA memberikan nilai tambah khusus bagi satker yang melakukan percepatan pengadaan melalui:",
   "Penunjukan langsung secara tertutup", "Penandatanganan kontrak dini (sebelum tahun anggaran berjalan dimulai) dan percepatan tender", "Pembayaran uang muka maksimal tanpa jaminan", "Pemecahan paket pengadaan menjadi kecil-kecil", "B",
   "Percepatan penandatanganan kontrak dini (early procurement) diapresiasi dalam akselerasi belanja modal/kontraktual."]
];

t1_sedang.forEach(item => {
  part3Questions.push(q(`mbq_${currentNumber}`, currentNumber++, t1, "SEDANG", item[0], item[1], item[2], item[3], item[4], item[5], item[6], t1_reg));
});

// 16 ANALISIS (HOTS)
const t1_analisis = [
  ["Studi Kasus HOTS IKPA (Mitigasi Deviasi Halaman III DIPA): Pada awal Triwulan IV, Satker Balai Diklat mendapati jadwal pengadaan sarana diklat senilai Rp2.000.000.000 yang semula dijadwalkan cair di bulan Oktober terpaksa mundur ke Desember karena kegagalan lelang pertama. RPD Halaman III DIPA di SAKTI masih mencatat rencana penarikan Rp2 Miliar di bulan Oktober. Langkah strategis KPA/PPK yang paling tepat sebelum batas akhir pemutakhiran RPD Triwulan IV adalah:",
   "Membiarkan data apa adanya dan berharap lelang kedua selesai dalam 3 hari",
   "Melakukan pemutakhiran data RPD Halaman III DIPA pada periode pembukaan revisi triwulan IV dengan menggeser rencana penarikan belanja modal dari Oktober ke Desember",
   "Menerbitkan SPM fiktif di bulan Oktober agar deviasi tidak muncul",
   "Mengubah jenis belanja modal menjadi belanja bantuan sosial",
   "B",
   "Pemutakhiran RPD Halaman III DIPA triwulanan adalah instrumen resmi untuk menyelaraskan kembali jadwal penarikan riil dengan komitmen pembayaran, sehingga deviasi bulanan tetap terjaga di bawah 5%."],
  ["Analisis HOTS Kepatuhan Kontrak: Satker Pengadilan Negeri menandatangani kontrak renovasi gedung Rp800.000.000 pada tanggal 12 Mei. Karena kesibukan PPK dinas luar kota, data kontrak baru diinput dan dikirim ke KPPN pada hari kerja ke-8. Di saat yang sama, PPK ingin agar nilai IKPA Satker tetap meraih predikat 'Sangat Baik' di akhir tahun. Evaluasi tindakan yang harus dilakukan satker adalah:",
   "Mengubah tanggal kontrak di dokumen fisik menjadi tanggal mundur",
   "Menerima catatan penalti keterlambatan pada indikator Belanja Kontraktual dan memperketat SOP internal pendaftaran kontrak berikutnya maksimal hari kerja ke-3",
   "Menghapus nomor kontrak dari pembukuan",
   "Meminta KPPN memanipulasi tanggal terima di SPAN",
   "B",
   "Keterlambatan pendaftaran kontrak tidak dapat dimanipulasi secara legal; satker harus mengevaluasi alur kerja agar kontrak berikutnya didaftarkan sebelum H+5 guna meminimalisir penurunan rata-rata tahunan."],
  ["Analisis Kasus HOTS Tagihan 17 HK: Penyedia jasa menyerahkan BAST perbaikan kendaraan dinas pada 1 Juni. PPK baru menyampaikan SPP ke PPSPM pada 25 Juni (hari kerja ke-18). PPSPM menolak menerbitkan SPM karena melampaui 17 HK. Manakah analisis yuridis yang tepat terhadap tindakan PPSPM?",
   "Tindakan PPSPM salah karena keterlambatan bukan tanggung jawab PPSPM",
   "Tindakan PPSPM tepat dalam menguji ketepatan waktu, namun jika tagihan riil dan sah, SPM tetap diterbitkan dengan konsekuensi penalti IKPA dicatat oleh sistem",
   "Tagihan pihak ketiga otomatis hangus dan tidak boleh dibayarkan selamanya",
   "PPK harus membayar tagihan tersebut menggunakan uang pribadi",
   "B",
   "Hak tagih pihak ketiga atas pekerjaan sah tetap harus diselesaikan negara, meskipun keterlambatan pengajuan SPM oleh PPK akan tercatat sebagai penalti pada indikator Penyelesaian Tagihan."],
  ["Analisis HOTS Revolving Uang Persediaan: Satker memiliki pagu UP Rp50.000.000. Hingga tanggal 25 setiap bulannya, realisasi belanja kuitansi hanya sekitar Rp15.000.000 (30%). Agar nilai indikator Pengelolaan UP tidak anjlok, opsi kebijakan pengelolaan kas yang paling rasional bagi KPA adalah:",
   "Mengajukan SPM-GUP fiktif tanpa bukti kuitansi",
   "Mengajukan surat permohonan penurunan besaran pagu UP ke KPPN agar proporsi revolving bulanan dapat melampaui 50% dari pagu baru yang lebih realistis",
   "Memaksakan pembelian barang yang tidak dibutuhkan satker",
   "Menarik seluruh uang tunai dari bank dan disimpan di brankas",
   "B",
   "Menurunkan besaran pagu UP (downsizing UP) ke nominal yang sesuai dengan kebutuhan operasional riil adalah langkah efisiensi kas negara yang otomatis memperbaiki rasio perputaran (revolving) UP."],
  ["Evaluasi HOTS Dispensasi Akhir Tahun: Pada tanggal 28 Desember, Satker X mengalami keterlambatan pengajuan SPM LS Gaji Induk Januari senilai Rp400 juta karena server lokal satker tersambar petir. Satker mengajukan surat permohonan dispensasi ke Kepala KPPN. Analisis konsekuensi manakah yang paling akurat?",
   "KPPN pasti menolak karena tidak ada toleransi di akhir tahun",
   "Kepala KPPN dapat menyetujui dispensasi dengan pertimbangan force majeure untuk menjamin hak gaji ASN, namun satker tetap menerima catatan dispensasi pada IKPA",
   "Satker langsung dibubarkan oleh Kementerian Keuangan",
   "Pegawai tidak akan menerima gaji selama 1 tahun anggaran",
   "B",
   "Kepala KPPN berwenang memberikan dispensasi atas dasar force majeure untuk kepentingan hak dasar pegawai, meski secara sistem akan tercatat dalam metrik dispensasi SPM."],
  ["Analisis HOTS Capaian Output Anomali Negatif: Pada akhir Triwulan III, output Bantuan Peralatan Sekolah mencatat penyerapan anggaran 95% (Rp1,9 M dari Rp2 M), namun PCRO baru terisi 20% dan RVRO 0 unit. Penyebabnya adalah barang telah diterima di gudang rekanan tetapi belum didistribusikan ke sekolah. Evaluasi pelaporan data di SAKTI yang paling tepat adalah:",
   "Mengisi PCRO 95% dan RVRO 100% agar MonSAKTI tidak merah",
   "Mengisi PCRO sesuai progres riil tahapan penerimaan (misal 80% perakitan) dan memberikan penjelasan rinci kendala distribusi pada referensi pelaporan",
   "Menghapus data capaian output hingga seluruh barang terdistribusi",
   "Menolak membayar rekanan pengadaan",
   "B",
   "Pengisian capaian output harus mencerminkan progres tahapan fisik riil disertai catatan keterangan yang valid guna mengklarifikasi anomali kesenjangan antara penyerapan dan fisik."],
  ["Analisis HOTS Strategi Optimalisasi Nilai IKPA: Satker Kemenag memiliki 10 DIPA Satker Daerah. Pada akhir triwulan II, nilai rata-rata IKPA adalah 88,5. Faktor kelemahan terbesar adalah deviasi Hal III DIPA (skor 65) dan penyelesaian tagihan (skor 78). Rekomendasi manajerial yang paling berdampak cepat untuk mendongkrak nilai di triwulan III adalah:",
   "Mengganti seluruh bendahara pengeluaran dengan staf baru",
   "Membentuk tim asistensi percepatan BAST 17 HK dan menyusun kalender kerja penarikan dana harian yang disinkronkan saat pemutakhiran RPD Triwulan III",
   "Menghentikan seluruh pencairan anggaran sampai akhir tahun",
   "Mengajukan revisi DIPA setiap minggu ke DJA",
   "B",
   "Fokus pada dua variabel dengan gap terbesar (penjadwalan RPD triwulan III dan monitoring ketat masa 17 HK sejak BAST) merupakan strategi terbukti mendongkrak nilai IKPA secara signifikan."],
  ["Analisis Kasus HOTS Kontrak Dini (Early Procurement): Satker Balai Jalan Nasional melakukan tender dini pada bulan November tahun n-1 sebelum DIPA tahun n disahkan. Penandatanganan kontrak dilakukan 3 hari kerja setelah DIPA diterima pada awal Januari. Bagaimana dampak tata kelola ini terhadap indikator IKPA?",
   "Dikenakan sanksi karena mendahului tahun anggaran",
   "Mendapatkan skor optimal pada akselerasi belanja kontraktual dan mempercepat penyerapan belanja modal sejak awal tahun",
   "Diwajibkan mengulang proses tender dari awal",
   "Kontrak otomatis dinyatakan batal demi hukum",
   "B",
   "Early procurement merupakan best practice pengadaan pemerintah yang sangat didorong Ditjen Perbendaharaan guna mengeliminasi penumpukan penyerapan di akhir tahun."],
  ["Evaluasi Kasus Penolakan SPM vs IKPA: Satker mengirim SPM-LS ke KPPN pada hari ke-15 sejak BAST. KPPN menolak SPM tersebut karena kesalahan penulisan nomor rekening bank penerima. Satker memperbaiki dan mengirim ulang SPM pada hari ke-18. Bagaimana status penilaian indikator Penyelesaian Tagihan?",
   "Dihitung berdasarkan tanggal pengajuan pertama (hari ke-15) sehingga tidak terkena penalti",
   "Dihitung berdasarkan tanggal SPM yang disetujui terbit SP2D (hari ke-18), sehingga tercatat melampaui batas waktu 17 hari kerja",
   "Otomatis diberi nilai 100 karena kesalahan bukan disengaja",
   "Penyedia jasa wajib mengganti kerugian penalti",
   "B",
   "Indikator penyelesaian tagihan dihitung sampai dengan tanggal SPM yang benar dan diproses menjadi SP2D oleh KPPN."],
  ["Analisis HOTS Revisi Pagu Anggaran Belanja Modal: KPA menerima DIPA Petikan Perubahan di pertengahan November dengan tambahan anggaran belanja modal Rp5 Miliar. Mengingat sisa waktu tinggal 6 minggu, mitigasi risiko IKPA yang wajib diambil adalah:",
   "Langsung mencairkan seluruh Rp5 Miliar ke rekening pribadi bendahara",
   "Meneliti kesiapan juknis dan pengadaan; bila tidak memungkinkan selesai 31 Desember, segera koordinasi penyesuaian RPD dan opsi penggunaan mekanisme RPATA atau penolakan revisi",
   "Mengajukan SPM-UP sebesar Rp5 Miliar",
   "Menunda pembayaran seluruh gaji pegawai",
   "B",
   "Menerima pagu belanja modal di akhir tahun tanpa mitigasi waktu lelang menimbulkan risiko penyerapan rendah, keterlambatan pembayaran, dan sanksi indikator IKPA."],
  ["Analisis HOTS Dispensasi SPM vs Nilai Akhir IKPA: Satker A memiliki nilai sempurna 100 pada 7 indikator, namun mengajukan 3 SPM dispensasi di bulan Desember. Satker B memiliki nilai 94 pada seluruh indikator tanpa satupun SPM dispensasi. Mengapa Satker B bisa memiliki performa pelaksanaan anggaran yang lebih sehat?",
   "Karena satker B menyuap KPPN",
   "Karena satker B menunjukkan perencanaan dan eksekusi yang disiplin tanpa mengganggu siklus penutupan kas negara di akhir tahun",
   "Karena satker B anggarannya lebih kecil",
   "Karena dispensasi SPM tidak mengurangi poin",
   "B",
   "Disiplin jadwal pengajuan SPM mencerminkan kematangan tata kelola dan kepatuhan terhadap regulasi penutupan kas negara BUN."],
  ["Analisis Kasus HOTS Gap RVRO dan Realisasi Anggaran: Di akhir tahun, output Pembangunan Jembatan mencatat realisasi anggaran 100% (SP2D cair lunas dengan Bank Garansi 100%), namun fisik jembatan di lapangan baru 85%. Berapakah RVRO yang seharusnya dilaporkan di SAKTI?",
   "Wajib dilaporkan 1 jembatan (100%) karena uang sudah cair semua",
   "Dilaporkan 0 unit jembatan (RVRO belum selesai) dengan penjelasan progres fisik 85% dan sisa pekerjaan dijamin bank garansi/RPATA",
   "Dihapus dari laporan tahunan",
   "Dilaporkan 2 jembatan untuk menutupi kekurangan",
   "B",
   "Volume output (RVRO) hanya boleh diakui bila output telah selesai secara fungsional (100% tuntas diserahterimakan), bukan sekadar serapan uang."],
  ["Studi Kasus HOTS Pemilihan Metode Pembayaran: Satker memiliki tagihan langganan daya dan jasa (listrik dan internet) senilai Rp85.000.000 tiap bulan. Opsi metode pembayaran manakah yang paling aman dan efisien terhadap likuiditas UP dan indikator IKPA?",
   "Membayar tunai dengan UP bendahara setiap bulan",
   "Menggunakan mekanisme SPM-LS langsung ke rekening PLN dan Telkom",
   "Menunda pembayaran hingga akhir tahun",
   "Meminta pegawai patungan",
   "B",
   "Penggunaan SPM-LS nonkontraktual untuk pembayaran langganan daya dan jasa di atas pagu UP menjaga likuiditas kas bendahara tetap longgar dan mempercepat penyerapan."],
  ["Analisis Kasus HOTS Deviasi Halaman III DIPA Satker BLU: Apakah pendapatan BLU yang melampaui target DIPA di tengah tahun anggaran mempengaruhi indikator deviasi Halaman III DIPA Satker BLU?",
   "Ya, penerimaan yang melonjak langsung membatalkan nilai IKPA",
   "Deviasi Hal III DIPA fokus mengukur sisi belanja; namun penambahan pagu belanja dari pendapatan BLU harus diakomodasi melalui revisi DIPA pengesahan belanja BLU",
   "BLU tidak memiliki DIPA sehingga bebas dari IKPA",
   "Uang lebih wajib disetor ke kas negara sebagai pajak",
   "B",
   "Fleksibilitas belanja BLU tetap harus disahkan melalui mekanisme revisi DIPA/SP3B agar penyerapan anggarannya sinkron dengan pembukuan BUN."],
  ["Analisis Kausalitas HOTS Penolakan SPM: KPPN mencatat tingkat penolakan SPM Satker Z mencapai 12% pada Triwulan II. Dampak domino yang terjadi pada komponen IKPA lainnya adalah:",
   "Tidak ada dampak apapun",
   "Penyelesaian tagihan pihak ketiga menjadi tertunda melampaui 17 HK dan penyerapan anggaran meleset dari jadwal RPD Halaman III DIPA",
   "Gaji kepala satker dipotong otomatis oleh bank",
   "DIPA satker dialihkan ke kementerian lain",
   "B",
   "Penolakan SPM mengakibatkan keterlambatan penyelesaian tagihan dan pergeseran realisasi dari jadwal RPD yang telah ditetapkan."],
  ["Analisis HOTS Integrasi Indikator IKPA 2026: Mengapa reformulasi IKPA memberikan bobot penalti signifikan pada kegagalan penyerapan anggaran berbasis belanja modal dibandingkan belanja pegawai?",
   "Karena belanja pegawai tidak penting bagi perekonomian",
   "Karena belanja modal memiliki efek berganda (multiplier effect) tinggi bagi pembangunan infrastruktur dan pertumbuhan ekonomi nasional",
   "Karena belanja modal tidak memerlukan bukti kuitansi",
   "Karena belanja modal ditentukan oleh perbankan swasta",
   "B",
   "Belanja modal adalah penggerak utama pertumbuhan ekonomi dan pelayanan infrastruktur publik, sehingga keterlambatan penyerapan modal berdampak langsung pada perekonomian."]
];

t1_analisis.forEach(item => {
  part3Questions.push(q(`mbq_${currentNumber}`, currentNumber++, t1, "ANALISIS", item[0], item[1], item[2], item[3], item[4], item[5], item[6], t1_reg));
});

console.log(`Topic 1 generated. Total questions now: ${part3Questions.length}`);

// We will write the full generator for Part 3 and run it.
