# -*- coding: utf-8 -*-
import json
import os

print("Starting generation of Part 3 (500 Questions: mbq_1051 to mbq_1550)...")

# Base questions builder
def make_q(num, topic, diff, q_text, a, b, c, d, ans, exp, reg):
    pts = 5 if diff == 'MUDAH' else (10 if diff == 'SEDANG' else 15)
    return {
        "id": f"mbq_{num}",
        "number": num,
        "topic": topic,
        "difficulty": diff,
        "questionText": q_text,
        "optionA": a,
        "optionB": b,
        "optionC": c,
        "optionD": d,
        "correctAnswer": ans,
        "explanation": exp,
        "referenceRegulation": reg,
        "points": pts
    }

all_questions = []

# Definition of topics and their 50 questions
topics_data = []

# =========================================================================
# 1. IKPA - Reformulasi 2026 & Kinerja Anggaran
# =========================================================================
t1_name = "IKPA - Reformulasi 2026 & Kinerja Anggaran"
t1_reg = "PER-5/PB/2022 jo Petunjuk Teknis IKPA Terkini"
t1_questions = [
    # 17 MUDAH
    ("Berapakah jumlah indikator kinerja dalam kerangka IKPA reformulasi?",
     "6 Indikator", "8 Indikator", "10 Indikator", "12 Indikator", "B",
     "Sesuai reformulasi IKPA, terdapat 8 indikator kinerja yang dikelompokkan ke dalam 3 aspek utama."),
    ("Tiga aspek penilaian utama dalam evaluasi kinerja IKPA adalah:",
     "Kualitas Perencanaan, Kualitas Pelaksanaan, dan Kualitas Hasil Pelaksanaan Anggaran", "Penyusunan DIPA, Penyerapan Kas, dan Audit BPK", "Modul Anggaran, Modul Komitmen, dan Modul Pembayaran", "Belanja Pegawai, Belanja Barang, dan Belanja Modal", "A",
     "Tiga aspek evaluasi IKPA adalah Kualitas Perencanaan Anggaran, Kualitas Pelaksanaan Anggaran, dan Kualitas Hasil."),
    ("Indikator IKPA yang mengukur deviasi rencana penarikan bulanan dengan realisasi adalah:",
     "Revisi DIPA", "Halaman III DIPA", "Penyerapan Anggaran", "Dispensasi SPM", "B",
     "Indikator Deviasi Halaman III DIPA mengukur kesesuaian penarikan dana bulanan dengan realisasi riilnya."),
    ("Ambang batas deviasi bulanan Halaman III DIPA per jenis belanja agar memperoleh nilai 100 adalah:",
     "Maksimal 5%", "Maksimal 10%", "Maksimal 15%", "Maksimal 20%", "A",
     "Toleransi deviasi bulanan RPD Halaman III DIPA adalah maksimal 5% untuk mendapatkan nilai maksimal 100."),
    ("Berapa batas frekuensi revisi DIPA kewenangan Kanwil DJPb/DJA per triwulan agar nilai 100?",
     "Maksimal 1 kali", "Maksimal 2 kali", "Maksimal 3 kali", "Tidak ada batasan", "A",
     "Satker mempertahankan skor 100 jika melakukan revisi DIPA kewenangan Kanwil/DJA maksimal 1 kali dalam 1 triwulan."),
    ("Berapa hari kerja batas waktu pendaftaran data kontrak (CAN) ke KPPN sejak ditandatangani?",
     "3 hari kerja", "5 hari kerja", "7 hari kerja", "14 hari kalender", "B",
     "Kontrak wajib didaftarkan ke KPPN paling lambat 5 hari kerja sejak tanggal penandatanganan kontrak."),
    ("Berapa hari kerja batas waktu penyelesaian tagihan LS (BAST ke SPM) pada indikator Penyelesaian Tagihan?",
     "7 hari kerja", "10 hari kerja", "14 hari kerja", "17 hari kerja", "D",
     "Batas waktu penyelesaian tagihan pihak ketiga adalah 17 hari kerja sejak timbulnya hak tagih (BAST disahkan)."),
    ("Minimal persentase revolving (penggantian) Uang Persediaan dalam 1 bulan kalender adalah:",
     "25% dari pagu UP", "50% dari pagu UP", "75% dari pagu UP", "100% dari pagu UP", "B",
     "Revolving UP dipersyaratkan minimal 50% dari pagu UP dalam satu bulan kalender agar nilai optimal."),
    ("Target penyerapan anggaran kumulatif untuk Belanja Barang pada akhir Triwulan I adalah sebesar:",
     "10%", "15%", "20%", "25%", "B",
     "Target minimal penyerapan belanja barang pada triwulan I adalah 15%."),
    ("Target penyerapan anggaran kumulatif untuk Belanja Modal pada akhir Triwulan II adalah sebesar:",
     "30%", "40%", "50%", "60%", "B",
     "Target kumulatif penyerapan belanja modal pada akhir triwulan II ditetapkan minimal 40%."),
    ("Batas waktu pelaporan data capaian output bulanan ke KPPN melalui SAKTI adalah:",
     "Paling lambat 5 hari kerja bulan berikutnya", "Paling lambat 10 hari kerja bulan berikutnya", "Paling lambat akhir bulan", "Tiap tanggal 15", "A",
     "Pelaporan data capaian output disampaikan paling lambat 5 hari kerja setelah bulan berkenaan berakhir."),
    ("Pengajuan SPM yang memerlukan surat dispensasi Kepala KPPN/Kanwil akan berakibat:",
     "Mengurangi skor indikator Dispensasi SPM secara otomatis", "Menaikkan nilai karena dana terserap", "Membatalkan seluruh DIPA", "Tidak mempengaruhi apapun", "A",
     "Dispensasi SPM dikenakan penalti poin yang menurunkan nilai indikator Dispensasi SPM."),
    ("Rentang nilai total IKPA untuk kategori predikat 'Sangat Baik' adalah:",
     "85 s.d. 89", "90 s.d. 94", "95 s.d. 100", "Di atas 75", "C",
     "Kategori nilai IKPA: Sangat Baik (95-100), Baik (85-94,99), Cukup (70-84,99), Kurang (<70)."),
    ("Komponen PCRO dalam penilaian indikator Capaian Output merupakan singkatan dari:",
     "Progres Capaian Rincian Output", "Pagu Capaian Rencana Operasional", "Penyerapan Capaian Rincian Output", "Pengawasan Capaian Realisasi Output", "A",
     "PCRO mengukur persentase kemajuan fisik rincian output kegiatan."),
    ("Komponen RVRO dalam indikator Capaian Output merupakan singkatan dari:",
     "Realisasi Volume Rincian Output", "Rencana Validasi Rincian Operasional", "Rincian Volume Rencana Organisasi", "Realisasi Verifikasi Rencana Output", "A",
     "RVRO mengukur jumlah kuantitas fisik output yang telah berhasil diserahterimakan."),
    ("Revisi Petunjuk Operasional Kegiatan (POK) kewenangan KPA tidak dihitung dalam frekuensi revisi DIPA karena:",
     "Merupakan kewenangan internal satker tanpa mengubah DIPA induk DJA/Kanwil", "POK tidak memiliki anggaran", "Revisi POK dilakukan oleh auditor BPK", "POK bersifat opsional", "A",
     "Revisi POK kewenangan internal KPA tidak dilaporkan sebagai revisi DIPA di Ditjen Perbendaharaan."),
    ("Menu pada MonSAKTI yang digunakan untuk memantau rekap skor dan transaksi penalti IKPA adalah:",
     "Menu Monev Kinerja IKPA", "Menu Administrator User", "Menu Neraca Saldo", "Menu Karwas Kontrak", "A",
     "Menu Monev Kinerja IKPA di MonSAKTI menyajikan rekap skor, tren, dan rincian transaksi bermasalah."),
    # 17 SEDANG
    ("Satker memiliki pagu UP Rp80.000.000. Realisasi belanja UP bulan Mei sebesar Rp32.000.000 dan SPM-GUP diajukan 30 Mei. Status revolving UP adalah:",
     "Tidak optimal, karena baru mencapai 40% (kurang dari syarat minimal 50%)", "Optimal 100% karena diajukan sebelum akhir bulan", "Diberikan surat teguran tertulis", "Pagu UP otomatis hangus", "A",
     "Realisasi 32 juta dari 80 juta adalah 40%, di bawah batas minimal revolving 50% per bulan."),
    ("PPK menandatangani kontrak pengadaan alat laboratorium pada Kamis tanggal 5 Juni. Hari libur akhir pekan Sabtu-Minggu. Kapan batas akhir pendaftaran kontrak ke KPPN?",
     "Selasa 10 Juni", "Rabu 11 Juni", "Kamis 12 Juni", "Jumat 13 Juni", "C",
     "5 hari kerja: Jumat (1), Senin (2), Selasa (3), Rabu (4), Kamis 12 Juni (5)."),
    ("BAST diterima 2 Februari. SPM-LS baru diterbitkan dan dikirim ke KPPN pada hari kerja ke-20. Konsekuensinya adalah:",
     "Nilai indikator Penyelesaian Tagihan mengalami penurunan akibat keterlambatan di atas 17 HK", "Kontrak otomatis dibatalkan pihak KPPN", "SP2D tidak dapat diterbitkan selamanya", "Satker wajib membayar denda kas negara", "A",
     "Penyelesaian tagihan di atas 17 hari kerja dicatat sebagai transaksi terlambat pada indikator Penyelesaian Tagihan."),
    ("Kapan periode resmi pemutakhiran data RPD Halaman III DIPA triwulanan dibuka oleh Ditjen Perbendaharaan?",
     "Pada awal setiap triwulan kalender (biasanya s.d. hari kerja ke-10 atau ke-15)", "Pada setiap akhir tahun", "Setiap awal minggu di hari Senin", "Hanya dibuka jika terjadi resesi", "A",
     "Pemutakhiran RPD Halaman III DIPA dibuka terjadwal pada awal triwulan agar satker dapat menyesuaikan rencana kas."),
    ("Jika satker melakukan revisi DIPA kewenangan Kanwil DJPb sebanyak 3 kali dalam satu triwulan, nilai indikator Revisi DIPA triwulan tersebut adalah:",
     "Nilai 100", "Nilai 85 s.d. 90", "Nilai 70 s.d. 80", "Nilai 50 atau lebih rendah", "C",
     "Setiap revisi melebihi frekuensi 1 kali per triwulan memberikan penalti pengurangan skor pada indikator Revisi DIPA."),
    ("Pengaruh pengajuan 2 SPM dispensasi pada akhir tahun terhadap nilai akhir IKPA tahunan adalah:",
     "Tidak ada pengaruh jika disetujui", "Mengurangi skor indikator Dispensasi SPM secara proporsional sesuai bobot penalti", "Nilai IKPA langsung di-reset ke 0", "KPA dicopot dari jabatannya", "B",
     "Dispensasi SPM dihitung penaltinya berdasarkan rasio SPM yang diajukan dengan dispensasi terhadap total SPM."),
    ("Bagaimana cara satker menghindari anomali gap antara penyerapan anggaran dan capaian output di MonSAKTI?",
     "Mengisi progres fisik fiktif", "Melaporkan progres fisik secara riil dan berkala setiap bulan sesuai tahapan pekerjaan", "Tidak usah menginput data output", "Menghapus DIPA dari SAKTI", "B",
     "Pengisian progres fisik secara disiplin dan akurat sesuai tahapan riil mencegah timbulnya data anomali di MonSAKTI."),
    ("Komitmen pengadaan senilai Rp40.000.000 dengan Surat Pesanan dibayarkan melalui SPM-LS Nonkontraktual. Apakah wajib didaftarkan sebagai data kontrak (CAN) di KPPN?",
     "Wajib dalam 5 hari kerja", "Tidak wajib didaftarkan di modul komitmen KPPN karena di bawah batas Rp50 juta nonkontraktual", "Wajib didaftarkan dalam 1 hari", "Tergantung arahan auditor", "B",
     "Pengadaan di bawah Rp50 juta dengan mekanisme non-kontraktual tidak memerlukan pendaftaran CAN ke KPPN."),
    ("Penyebab utama nilai Deviasi Halaman III DIPA rendah pada triwulan I dan II biasanya adalah:",
     "Rencana penarikan dana di DIPA awal dibuat merata (flat) tanpa memperhitungkan jadwal riil lelang PPK", "KPPN sering tutup layanan", "Penyedia menolak dibayar", "Inflasi daerah yang tinggi", "A",
     "RPD awal yang dibuat flat tanpa koordinasi jadwal lelang PPK menyebabkan deviasi realisasi sangat tinggi."),
    ("Jika satker memiliki sisa dana TUP sebesar Rp20.000.000 pada batas akhir 30 hari kalender, langkah yang benar adalah:",
     "Disimpan untuk belanja bulan berikutnya", "Menyetorkan sisa kas ke kas negara dengan SSPB dan mengajukan SPM-PTUP pertanggungjawaban", "Membagikan uang kepada pegawai", "Menyerahkan uang ke pihak ketiga", "B",
     "Sisa TUP wajib disetor kembali ke kas negara dan dipertanggungjawabkan tepat waktu agar tidak melanggar batas 30 hari."),
    ("Berapa batas waktu pertanggungjawaban dana TUP sejak SP2D diterbitkan sesuai ketentuan pembayaran APBN?",
     "14 hari kalender", "30 hari kalender", "60 hari kalender", "90 hari kalender", "B",
     "Pertanggungjawaban TUP wajib diselesaikan dalam 30 hari kalender sejak SP2D terbit."),
    ("Apakah hibah langsung dalam bentuk uang yang telah diregistrasi dinilai dalam IKPA setelah masuk DIPA?",
     "Tidak dinilai sama sekali", "Ya, dinilai sesuai siklus pelaksanaan anggaran normal setelah revisi DIPA pengesahan", "Hanya dinilai jika nilainya di atas Rp50 miliar", "Dinilai oleh kementerian luar negeri", "B",
     "Setelah masuk DIPA, anggaran hibah menjadi bagian dari realisasi DIPA satker yang dinilai dalam IKPA."),
    ("Pagu minus pada akun belanja operasional atau modal di SAKTI berakibat:",
     "SPM dapat diterbitkan bebas", "SPM tertolak sistem karena tidak boleh ada pengeluaran melebihi sisa pagu", "Pagu otomatis ditambah oleh sistem", "Bunga kas negara berkurang", "B",
     "Sistem SAKTI memblokir penerbitan SPP/SPM jika saldo pagu akun tidak mencukupi (pagu minus)."),
    ("Early Procurement (pengadaan dini) memberikan kontribusi positif terhadap IKPA terutama pada indikator:",
     "Belanja Kontraktual dan Akselerasi Penyerapan Anggaran sejak awal tahun", "Dispensasi SPM", "Pengelolaan UP", "Revisi DIPA", "A",
     "Pengadaan dini memungkinkan kontrak ditandatangani segera setelah DIPA efektif sehingga serapan awal tahun optimal."),
    ("Jika KPPN menolak SPM karena kesalahan nomor rekening pihak ketiga pada hari ke-16 dan SPM diperbaiki hari ke-19, maka:",
     "Dihitung hari ke-16", "Dihitung hari ke-19 saat SPM disetujui, sehingga tercatat terlambat melampaui 17 HK", "KPPN membatalkan penalti", "Satker dibebaskan dari penilaian", "B",
     "Penilaian ketepatan waktu tagihan dihitung sampai SPM dinyatakan benar dan diproses menjadi SP2D."),
    ("Dalam rangka mitigasi deviasi Hal III DIPA, satker dapat melakukan penyesuaian RPD secara mandiri pada:",
     "Setiap revisi DIPA triwulanan pemutakhiran Halaman III DIPA", "Hanya saat audit tahunan", "Tidak pernah diizinkan", "Setiap akhir pekan", "A",
     "Penyesuaian RPD difasilitasi saat periode pembukaan pemutakhiran Halaman III DIPA triwulanan."),
    ("Bobot indikator Penyerapan Anggaran dalam aspek Kualitas Pelaksanaan Anggaran adalah:",
     "Sangat kecil", "Signifikan (proporsional terhadap target belanja per jenis belanja)", "Nol persen", "Hanya formalitas", "B",
     "Penyerapan anggaran memiliki bobot krusial dalam menggerakkan perekonomian melalui belanja negara."),
    # 16 ANALISIS
    ("Analisis Kasus HOTS: Satker X memiliki deviasi RPD Belanja Modal sebesar 18% di Triwulan II. Pada Triwulan III, proyek fisik selesai lebih cepat dari jadwal. Apa tindakan optimal KPA saat pemutakhiran RPD Triwulan III agar deviasi kembali di bawah 5%?",
     "Membiarkan data RPD awal tetap di bulan November",
     "Memajukan jadwal penarikan RPD belanja modal pada pemutakhiran Hal III DIPA Triwulan III ke bulan September sesuai jadwal tagihan riil",
     "Menunda pencairan hingga akhir tahun agar deviasi hilang",
     "Mengubah jenis belanja menjadi belanja perjalanan dinas", "B",
     "Menyelaraskan jadwal RPD dengan kemajuan fisik riil pada pemutakhiran Hal III DIPA Triwulan III mengembalikan deviasi ke ambang batas aman."),
    ("Analisis Kasus Keterlambatan Pendaftaran Kontrak: Kontrak pengadaan mobil dinas senilai Rp600 juta ditandatangani 10 Juli. Dokumen baru dikirim ke KPPN tanggal 22 Juli (hari kerja ke-8). Mengapa sistem otomatis memberikan penalti indikator Belanja Kontraktual?",
     "Karena mobil dinas dilarang dibeli dengan APBN",
     "Karena pendaftaran melampaui batas wajib 5 hari kerja yang diatur dalam regulasi perbendaharaan",
     "Karena nilai kontrak terlalu besar",
     "Karena penyedia belum terdaftar di e-katalog", "B",
     "Pendaftaran kontrak melebihi H+5 kerja langsung dicatat sistem SPAN sebagai pelanggaran komitmen belanja kontraktual."),
    ("Analisis Kasus Penyelesaian Tagihan 17 HK: BAST pekerjaan instalasi jaringan disahkan 1 Agustus. Staf PPK baru menyerahkan berkas ke PPSPM pada 24 Agustus (hari kerja ke-16). PPSPM memerlukan 2 hari kerja untuk verifikasi berkas. Langkah mitigasi PPSPM agar tidak melanggar 17 HK adalah:",
     "Menolak berkas dan membatalkan pekerjaan",
     "Memprioritaskan pengujian hari itu juga dan menerbitkan SPM sebelum jam kerja hari ke-17 berakhir",
     "Mengubah tanggal BAST menjadi 10 Agustus secara sepihak",
     "Mengabaikan batas waktu karena keterlambatan bukan salah PPSPM", "B",
     "PPSPM harus melakukan pengujian cepat untuk mengamankan batas waktu maksimal hari kerja ke-17 sejak tanggal BAST."),
    ("Analisis Kasus Revolving UP Rendah: Satker Diklat memiliki pagu UP Rp100 juta namun realisasi belanja bulanan rata-rata hanya Rp25 juta (revolving 25%). Solusi struktural KPA agar nilai pengelolaan UP mencapai 100 tanpa melanggar prinsip kepatutan kas adalah:",
     "Melakukan belanja fiktif untuk menghabiskan dana",
     "Mengajukan surat permohonan penurunan pagu UP ke KPPN menjadi Rp40 juta sehingga serapan Rp25 juta melampaui 50%",
     "Menarik seluruh uang tunai dan disimpan di rekening pribadi bendahara",
     "Menghentikan seluruh kegiatan diklat", "B",
     "Menyesuaikan besaran pagu UP ke tingkat riil yang dibutuhkan meningkatkan rasio perputaran kas di atas 50%."),
    ("Analisis Kasus Dispensasi Akhir Tahun: Pada 27 Desember, satker mengalami kerusakan jaringan lokal sehingga SPM terlambat diajukan. KPA mengajukan permohonan dispensasi ke KPPN. Evaluasi yuridis terhadap penerbitan dispensasi adalah:",
     "KPPN menolak mutlak tanpa pertimbangan apapun",
     "Kepala KPPN dapat memberikan dispensasi atas dasar force majeure untuk menyelamatkan hak pihak ketiga/pegawai, dengan konsekuensi catatan penalti pada metrik IKPA satker",
     "KPPN menyetujui dispensasi dan menghapus seluruh penalti IKPA satker",
     "Satker otomatis dikenakan denda pidana", "B",
     "Dispensasi dapat disetujui demi kelancaran hak bayar negara, namun metrik kepatuhan IKPA tetap mencatat transaksi dispensasi tersebut."),
    ("Analisis Kasus Capaian Output Terhambat: Output Pembangunan Asrama Mahasiswa mencatat serapan anggaran 80% (uang muka dan termin 1), namun fisik bangunan baru 30%. Penyebabnya adalah cuaca ekstrem. Tindakan pelaporan data di SAKTI yang akuntabel adalah:",
     "Melaporkan PCRO 80% mengikuti serapan anggaran agar nilai IKPA bagus",
     "Melaporkan PCRO 30% sesuai fisik riil dan mencantumkan penjelasan kendala cuaca pada catatan keterangan",
     "Menghapus data capaian output hingga fisik mencapai 80%",
     "Mengubah target output menjadi 0", "B",
     "Pelaporan capaian output wajib jujur mencerminkan kondisi lapangan; anomali fisik dan anggaran diklarifikasi lewat catatan keterangan resmi."),
    ("Analisis Kasus Pemilihan Jenis SPM Pembayaran Langganan Daya: Satker memiliki tagihan listrik dan telepon rata-rata Rp60 juta per bulan, sementara pagu UP tunai satker hanya Rp50 juta. Metode pembayaran manakah yang paling aman untuk menjaga ketahanan UP satker?",
     "Membayar tunai bertahap dengan UP",
     "Menerbitkan SPM-LS Nonkontraktual langsung ke rekening PLN dan Telkom setiap bulan",
     "Menunda pembayaran listrik hingga akhir triwulan",
     "Meminta pegawai patungan", "B",
     "Penggunaan SPM-LS Nonkontraktual menjaga kas UP bendahara tidak terkuras dan menjamin kepatuhan jadwal pembayaran bulanan."),
    ("Analisis Kasus Kontrak Tahun Jamak (Multi-Years Contract): Satker Kementerian PUPR memiliki proyek multiyears. Bagaimana perlakuan pendaftaran komitmen kontrak tahun berikutnya di SAKTI?",
     "Kontrak didaftarkan ulang setiap tahun anggaran berjalan sebagai addendum/karwas tahunan dalam 5 hari kerja setelah DIPA efektif",
     "Cukup didaftarkan sekali di tahun pertama tanpa pemutakhiran",
     "Tidak perlu didaftarkan di modul komitmen",
     "Didaftarkan setelah seluruh proyek selesai 100%", "A",
     "Komitmen kontrak tahun jamak wajib dimutakhirkan dan dialokasikan karwas tahunannya pada setiap awal tahun anggaran."),
    ("Analisis Kasus Penolakan SPM KPPN: Dari 50 SPM yang diajukan satker dalam 1 bulan, terdapat 5 SPM ditolak KPPN karena salah akun belanja. Dampak langsung terhadap indikator IKPA lainnya adalah:",
     "Penyelesaian tagihan pihak ketiga berisiko melampaui 17 HK dan jadwal serapan anggaran di Hal III DIPA tergeser",
     "Tidak ada dampak apapun karena SPM bisa diajukan lagi",
     "Pagu akun belanja otomatis dipotong KPPN",
     "Gaji PPSPM dipotong 10%", "A",
     "Penolakan SPM menimbulkan efek domino keterlambatan pembayaran dan melesetnya rencana penarikan dana."),
    ("Analisis Kasus Retur SP2D Terkait IKPA: SP2D honor narasumber mengalami retur karena rekening penerima telah ditutup. Mengapa penyelesaian retur harus dilakukan secepatnya?",
     "Agar bunga bank tidak hilang",
     "Untuk mencegah penumpukan saldo gantung di rekening retur KPPN dan memastikan hak narasumber diterima tanpa keterlambatan berlarut-larut",
     "Agar KPPN tidak menyita aset satker",
     "Hanya formalitas laporan bulanan", "B",
     "Penyelesaian retur mendesak untuk memastikan dana sampai ke pihak yang berhak dan meniadakan saldo kas menggantung."),
    ("Analisis Kasus Early Procurement: Satker A menandatangani kontrak lelang dini pada 2 Januari setelah DIPA efektif akhir Desember. Satker B baru memulai lelang di bulan Maret. Dampak perbedaan ini pada nilai IKPA adalah:",
     "Satker A memiliki skor Belanja Kontraktual dan realisasi anggaran triwulan I yang jauh lebih unggul daripada Satker B",
     "Satker B lebih hemat anggaran karena lelang lebih teliti",
     "Kedua satker memiliki nilai yang sama persis",
     "Satker A terkena sanksi karena mendahului waktu", "A",
     "Pengadaan dini memberikan keunggulan telak pada kecepatan penyerapan belanja modal dan kualitas belanja kontraktual."),
    ("Analisis Kasus Pengelolaan TUP Menjelang Akhir Tahun: Satker memperoleh SP2D TUP tanggal 10 Desember sebesar Rp200 juta. Hingga 28 Desember, dana baru terserap Rp160 juta. Langkah wajib bendahara sebelum 31 Desember adalah:",
     "Menyimpan sisa Rp40 juta untuk belanja bulan Januari",
     "Menyetorkan sisa kas Rp40 juta ke Kas Negara dengan SSPB dan mengajukan SPM-PTUP pertanggungjawaban nihil sebelum tutup tahun buku",
     "Membelanjakan sisa dana untuk barang yang tidak tercantum dalam rincian TUP",
     "Mengabaikan sisa dana", "B",
     "Ketentuan LLAT mewajibkan seluruh sisa UP/TUP disetor ke kas negara dan di-PTUP-kan tuntas pada akhir tahun anggaran."),
    ("Analisis Kasus Gap Output Belanja Bantuan Pemerintah: Satker menyalurkan bantuan operasional pesantren 100% di Triwulan II. Mengapa RVRO baru boleh diakui 100% setelah laporan pertanggungjawaban penerima bantuan terverifikasi?",
     "Karena pencairan uang belum tentu menjamin bantuan sampai dan dimanfaatkan sesuai petunjuk teknis",
     "Karena bank penyalur menahan bunga simpanan",
     "Karena uang bantuan harus dikembalikan ke negara",
     "Karena pesantren tidak memiliki NPWP", "A",
     "Output bantuan pemerintah diakui secara paripurna saat manfaat bantuan telah benar-benar diterima sasaran (output delivered)."),
    ("Analisis Kasus Sinkronisasi Perencanaan dan Pengadaan: Satker merencanakan pengadaan server Rp1 Miliar di RPD bulan April. Lelang gagal dan baru selesai di bulan Juli. KPA tidak melakukan pemutakhiran RPD Triwulan II. Akibatnya adalah:",
     "Deviasi Halaman III DIPA bulan April dan Mei membengkak drastis sehingga skor indikator jatuh",
     "Nilai IKPA tetap 100 karena lelang gagal adalah faktor eksternal",
     "Server diberikan gratis oleh penyedia",
     "Pagu anggaran ditarik kembali oleh DJA", "A",
     "Tidak memutakhirkan RPD saat terjadi pergeseran jadwal lelang mengakibatkan deviasi besar pada bulan-bulan rencana awal."),
    ("Analisis Kasus Reformulasi IKPA Berbasis Kualitas Belanja: Mengapa penyerapan anggaran tidak lagi menjadi satu-satunya indikator dominan dalam IKPA?",
     "Karena pemerintah tidak membutuhkan laporan penyerapan",
     "Agar satker tidak sekadar mengejar serapan kuantitas anggaran di akhir tahun, melainkan mengedepankan ketepatan perencanaan, ketepatan waktu pembayaran, dan capaian output riil",
     "Karena anggaran negara surplus",
     "Karena sistem perbankan sudah otomatis", "B",
     "Reformulasi IKPA menggeser paradigma dari 'spending more' menuju 'spending better' dan akuntabilitas hasil."),
    ("Analisis Kasus Pengawasan KPA terhadap Penilaian IKPA: Apa fungsi strategis monitoring matriks IKPA mingguan oleh KPA melalui dashboard MonSAKTI?",
     "Mencari-cari kesalahan bendahara",
     "Mendeteksi secara dini anomali transaksi (kontrak telat, tagihan mendekati 17 HK, gap output) sebelum periode penilaian ditutup sehingga tindakan korektif dapat segera diambil",
     "Memenuhi syarat kenaikan pangkat KPA semata",
     "Menggantikan peran auditor eksternal", "B",
     "Monitoring berkala memungkinkan mitigasi cepat atas potensi penalti sebelum data terkunci pada akhir triwulan.")
]
topics_data.append((t1_name, t1_reg, t1_questions))

print("Topic 1 data compiled.")

# Helper to generate a generic domain engine of 50 high quality questions
def build_domain_questions(domain_name, reg_base, concepts_17, procedural_17, cases_16):
    res = []
    # 17 mudah
    for item in concepts_17:
        res.append((item[0], item[1], item[2], item[3], item[4], item[5], item[6]))
    # 17 sedang
    for item in procedural_17:
        res.append((item[0], item[1], item[2], item[3], item[4], item[5], item[6]))
    # 16 analisis
    for item in cases_16:
        res.append((item[0], item[1], item[2], item[3], item[4], item[5], item[6]))
    return res

# We will generate topics 2 through 10 in Python!
