import { RawQuestion } from './questionsIkpa';

export const saktiQuestions: RawQuestion[] = [
  // SAKTI Basics & Architecture
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Kepanjangan resmi dari akronim SAKTI dalam sistem pengelolaan perbendaharaan negara adalah...',
    optionA: 'Sistem Aplikasi Keuangan Tingkat Instansi',
    optionB: 'Sistem Administrasi Keuangan Terpadu Indonesia',
    optionC: 'Standar Akuntansi Keuangan Tingkat Internasional',
    optionD: 'Saluran Arus Kas Terintegrasi Instansi',
    correctAnswer: 'A',
    explanation: 'SAKTI adalah singkatan dari Sistem Aplikasi Keuangan Tingkat Instansi, sistem aplikasi tunggal yang mengintegrasikan seluruh proses bisnis keuangan satker kementerian/lembaga.',
    referenceRegulation: 'PMK No. 159/PMK.05/2018 tentang Pelaksanaan Piloting Sistem Aplikasi Keuangan Tingkat Instansi'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Sistem sentral di lingkungan Ditjen Perbendaharaan yang bertindak sebagai pemroses utama pencairan dana APBN (backend) dan menerima kiriman data dari SAKTI adalah...',
    optionA: 'SPAN (Sistem Perbendaharaan dan Anggaran Negara)',
    optionB: 'SIMAK-BMN',
    optionC: 'Aplikasi SAS',
    optionD: 'Aplikasi RKAKL DIPA',
    correctAnswer: 'A',
    explanation: 'SPAN (Sistem Perbendaharaan dan Anggaran Negara) adalah sistem otomasi terintegrasi pada Kantor Pelayanan Perbendaharaan Negara (KPPN) dan Kanwil DJPb untuk mengelola kas, komitmen, dan pencairan anggaran.',
    referenceRegulation: 'Grand Design Modernisasi Perbendaharaan DJPb'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Apa konsep arsitektur basis data utama yang diterapkan pada aplikasi SAKTI Full Module web-based?',
    optionA: 'Single Database terpusat berbasis cloud/web yang mengintegrasikan seluruh modul tanpa perlu transfer ADK antar-aplikasi lokal',
    optionB: 'Aplikasi desktop offline yang harus diinstal di setiap komputer dengan basis data Microsoft Access',
    optionC: 'Pengiriman data menggunakan disket fisik ke kantor pos',
    optionD: 'Pencatatan manual di buku besar kertas lalu difaks',
    correctAnswer: 'A',
    explanation: 'SAKTI menerapkan Single Database terpusat berbasis web. Seluruh transaksi dari modul penganggaran, komitmen, pembayaran, bendahara, aset, hingga akuntansi berada dalam satu ekosistem data yang saling terhubung.',
    referenceRegulation: 'PMK 159/PMK.05/2018 & Dokumen Arsitektur SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Manakah pembagian tiga tingkatan user role (pengguna) standar dalam operasional modul-modul SAKTI?',
    optionA: 'Operator (Perekam), Validator (Pemeriksa/PPK), dan Approver (Penyetuju/KPA/PPSPM)',
    optionB: 'User Biasa, User Tamu, dan Hacker',
    optionC: 'Siswa, Mahasiswa, dan Dosen',
    optionD: 'Kasir, Pramuniaga, dan Satpam',
    correctAnswer: 'A',
    explanation: 'Hierarki kewenangan dalam SAKTI menerapkan prinsip segregasi tugas: Operator bertugas menginput data, Validator bertugas menguji dan memvalidasi, dan Approver memberikan persetujuan final (approval) menggunakan TTE/OTP.',
    referenceRegulation: 'Pedoman Manajemen Pengguna Aplikasi SAKTI DJPb'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Seorang pegawai di Satker A ditunjuk sebagai Operator Pembayaran. Bolehkah pegawai tersebut secara bersamaan diberikan kewenangan sebagai Approver Pembayaran (PPSPM) pada akun SAKTI-nya?',
    optionA: 'Dilarang keras, sistem SAKTI secara sistemik menolak perangkapan role Operator dan Approver pada user yang sama untuk menegakkan segregation of duties',
    optionB: 'Boleh, jika kepala kantor memberikan surat izin tertulis',
    optionC: 'Boleh, pada hari Sabtu dan Minggu saja',
    optionD: 'Boleh, asalkan password akunnya diganti setiap hari',
    correctAnswer: 'A',
    explanation: 'Segregation of duties (pemisahan tugas) adalah pilar pengendalian intern utama. SAKTI membatasi role secara ketat sehingga satu user tidak boleh merangkap sebagai operator perekam sekaligus pejabat penyetuju transaksi.',
    referenceRegulation: 'Petunjuk Teknis Hak Akses dan Pengendalian Internal SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Siapakah pejabat di Satker yang bertindak sebagai Administrator SAKTI Satker untuk mengelola dan merekam user operator di kantornya?',
    optionA: 'Admin Satker yang ditunjuk secara resmi melalui SK KPA',
    optionB: 'Petugas kebersihan kantor',
    optionC: 'Kepala Dinas Tenaga Kerja Kabupaten',
    optionD: 'Petugas loket PLN',
    correctAnswer: 'A',
    explanation: 'Admin Satker diangkat melalui SK KPA untuk mengelola user management, penunjukan role modul, serta reset kata sandi operator di tingkat satker.',
    referenceRegulation: 'SOP Manajemen Pengguna SAKTI Satker'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Modul apa dalam aplikasi SAKTI yang digunakan untuk mengelola data BMN, inventarisasi, depresiasi/penyusutan aset, dan transfer BMN?',
    optionA: 'Modul Aset Tetap',
    optionB: 'Modul Anggaran',
    optionC: 'Modul Piutang',
    optionD: 'Modul Perjalanan Dinas',
    correctAnswer: 'A',
    explanation: 'Modul Aset Tetap pada SAKTI mengelola seluruh siklus hidup Barang Milik Negara (BMN) mulai dari perolehan, utilisasi, penyusutan berkala, transfer keluar/masuk, hingga penghapusan.',
    referenceRegulation: 'User Guide SAKTI Modul Aset Tetap'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Modul SAKTI yang digunakan untuk mencatat mutasi barang habis pakai, seperti alat tulis kantor (ATK), obat-obatan, dan amunisi adalah...',
    optionA: 'Modul Persediaan',
    optionB: 'Modul Komitmen',
    optionC: 'Modul Penganggaran',
    optionD: 'Modul Administrasi',
    correctAnswer: 'A',
    explanation: 'Modul Persediaan mencatat perolehan, pemakaian, dan sisa stok barang persediaan (habis pakai) menggunakan metode penilaian FIFO (First In First Out) atau Harga Terakhir.',
    referenceRegulation: 'Petunjuk Operasional SAKTI Modul Persediaan'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Satker menerima SP2D pembayaran pengadaan genset kantor senilai Rp75.000.000. Namun pada Modul Aset Tetap, genset tersebut belum tercatat sebagai aset satker. Mengapa hal ini bisa terjadi dan apa yang harus dilakukan operator?',
    optionA: 'Operator Aset belum melakukan proses "Perekaman BMN dari Pembelian / BAST SAKTI" untuk menautkan BAST Modul Komitmen dengan kartu BMN di Modul Aset',
    optionB: 'Genset otomatis menjadi milik pegawai satker secara pribadi',
    optionC: 'Modul Aset Tetap sedang rusak total',
    optionD: 'KPPN menyita genset tersebut secara sistem',
    correctAnswer: 'A',
    explanation: 'Dalam alur SAKTI, pengadaan aset tetap yang telah dicairkan harus ditindaklanjuti dengan penerimaan BMN di Modul Aset Tetap (menu Perolehan BMN dari Pembelian) agar neraca aset dan persediaan balance dengan modul GLP.',
    referenceRegulation: 'Juknis Integrasi Modul Komitmen dan Aset Tetap SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Apa fungsi utama dari Modul General Ledger dan Pelaporan (GLP) dalam aplikasi SAKTI?',
    optionA: 'Membentuk jurnal otomatis dari seluruh modul, membukukan transaksi akrual dan kas, serta menghasilkan Laporan Keuangan Satker (LRA, LO, LPE, Neraca)',
    optionB: 'Mengedit teks berita website satker',
    optionC: 'Mengatur pendingin ruangan kantor',
    optionD: 'Memeriksa presensi sidik jari pegawai',
    correctAnswer: 'A',
    explanation: 'Modul GLP adalah muara akuntansi dari seluruh transaksi SAKTI yang memproduksi jurnal berpasangan, neraca percobaan, dan draft Laporan Keuangan berbasis Standar Akuntansi Pemerintahan (SAP).',
    referenceRegulation: 'User Guide SAKTI Modul GL dan Pelaporan'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Fasilitas keamanan verifikasi transaksi persetujuan SPM oleh PPSPM di SAKTI yang dikirimkan melalui SMS atau aplikasi pesan instan resmi Kemenkeu disebut...',
    optionA: 'One-Time Password (OTP)',
    optionB: 'Kode Voucher Toko',
    optionC: 'PIN Kartu Kredit',
    optionD: 'Barcode Tiket Bioskop',
    correctAnswer: 'A',
    explanation: 'OTP (One-Time Password) SAKTI adalah kode verifikasi dinamis yang dikirim ke nomor telepon terdaftar pejabat perbendaharaan untuk memastikan integritas dan otentikasi persetujuan SPM.',
    referenceRegulation: 'Pedoman Keamanan Informasi dan OTP SAKTI DJPb'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Apa yang harus dilakukan jika nomor ponsel pejabat perbendaharaan pemegang OTP SAKTI mengalami perubahan atau nomor hilang?',
    optionA: 'KPA mengajukan permohonan pemutakhiran data pejabat/nomor OTP secara tertulis dan resmi ke KPPN dengan melampirkan SK pengangkatan pejabat dan surat pernyataan',
    optionB: 'Meminjam nomor ponsel orang lain tanpa melapor',
    optionC: 'Menghentikan seluruh pencairan gaji kantor',
    optionD: 'Mengganti nama kementerian/lembaga',
    correctAnswer: 'A',
    explanation: 'Perubahan nomor HP pejabat penerima OTP memerlukan verifikasi identitas resmi di KPPN untuk mencegah pengambilalihan akun persetujuan SPM tanpa hak.',
    referenceRegulation: 'SOP Pemutakhiran Pejabat Perbendaharaan KPPN'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Operator Pembayaran mencoba membuat draft SPP, namun saat memilih nomor kontrak muncul pesan "Pagu Komitmen Tidak Cukup / Belum Terdaftar di SPAN". Tindakan investigasi apa yang tepat?',
    optionA: 'Mengecek apakah ADK Kontrak telah didaftarkan dan mendapatkan nomor CAN/NRK yang sah dari KPPN pada Modul Komitmen',
    optionB: 'Menghapus seluruh data komputer',
    optionC: 'Mengganti mata uang dari Rupiah menjadi Dolar',
    optionD: 'Membuat kuitansi palsu',
    correctAnswer: 'A',
    explanation: 'SPP Kontraktual mensyaratkan nomor komitmen kontrak (NRK) yang sudah aktif dan terdaftar di SPAN. Jika belum disetujui KPPN, SPP tidak dapat divalidasi.',
    referenceRegulation: 'User Manual Modul Komitmen & Pembayaran SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Fitur "Tutup Periode" bulanan pada Modul SAKTI (seperti Modul Persediaan dan Modul Aset) berfungsi untuk...',
    optionA: 'Mengunci transaksi pada bulan berkenaan agar data laporan keuangan tidak berubah dan dapat dilakukan rekonsiliasi dengan Modul GLP',
    optionB: 'Mematikan server SAKTI secara global',
    optionC: 'Menghapus data pengadaan satker',
    optionD: 'Memberikan hari libur bagi seluruh staf',
    correctAnswer: 'A',
    explanation: 'Tutup periode bulanan mengunci buku besar modul pembantu agar posisi saldo persediaan/aset tetap final dan konsisten saat membentuk laporan keuangan bulanan.',
    referenceRegulation: 'Juknis Periode Akuntansi SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Data Supplier pada Modul Komitmen SAKTI yang memuat identitas perorangan/pegawai satker untuk keperluan pembayaran gaji atau perjalanan dinas tergolong sebagai Supplier Tipe...',
    optionA: 'Supplier Tipe 3 (Pegawai)',
    optionB: 'Supplier Tipe 1 (Satker)',
    optionC: 'Supplier Tipe 2 (Penyedia/Rekanan)',
    optionD: 'Supplier Tipe 7 (Transfer Daerah)',
    correctAnswer: 'A',
    explanation: 'Berdasarkan klasifikasi SPAN/SAKTI: Tipe 1 (Satker/UP), Tipe 2 (Penyedia Barang/Jasa), Tipe 3 (Pegawai), Tipe 6 (Bansos), Tipe 7 (Transfer Daerah).',
    referenceRegulation: 'Perdirjen Perbendaharaan tentang Pengelolaan Supplier SPAN'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Apakah pendaftaran data Supplier baru ke KPPN dapat dilakukan bersamaan dengan pengajuan SPM pertama kali?',
    optionA: 'Bisa diajukan bersamaan (interkoneksi ADK Supplier dan SPM) atau didaftarkan terlebih dahulu sebelum SPM dikirim',
    optionB: 'Wajib didaftarkan 1 tahun sebelum SPM',
    optionC: 'Tidak perlu didaftarkan sama sekali',
    optionD: 'Hanya boleh didaftarkan oleh bank penerima',
    correctAnswer: 'A',
    explanation: 'Pada SAKTI, pendaftaran supplier dapat dikirimkan secara terpisah lebih awal atau digabungkan bersama ADK SPM ke SPAN untuk diverifikasi otomatis.',
    referenceRegulation: 'Petunjuk Perekaman Supplier SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Seorang Bendahara Pengeluaran menerima setoran uang sisa perjalanan dinas dari pegawai sebesar Rp1.500.000 secara tunai. Menu apa yang harus digunakan pada Modul Bendahara SAKTI untuk mencatat transaksi ini?',
    optionA: 'Menu Setoran Pengembalian Belanja / Penerimaan Pengembalian UP lalu disetorkan ke Kas Negara via Modul Bendahara',
    optionB: 'Menu Pembayaran Gaji Induk',
    optionC: 'Menu Penghapusan Piutang Macet',
    optionD: 'Menu Lelang Barang Bekas',
    correctAnswer: 'A',
    explanation: 'Pengembalian sisa uang muka belanja dicatat pada Modul Bendahara sebagai penerimaan pengembalian belanja/UP, lalu dibukukan penyetorannya ke Kas Negara melalui pembuatan kode billing SIMPONI/MPN.',
    referenceRegulation: 'User Manual Modul Bendahara SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Apa yang dimaksud dengan Buku Kas Umum (BKU) pada Modul Bendahara SAKTI?',
    optionA: 'Buku catatan induk akuntansi kas bendahara yang mencatat seluruh mutasi penerimaan dan pengeluaran kas, baik tunai maupun kas bank',
    optionB: 'Buku daftar presensi pegawai',
    optionC: 'Buku agenda surat keluar',
    optionD: 'Buku katalog harga toko',
    correctAnswer: 'A',
    explanation: 'BKU adalah dokumen pencatatan sentral bendahara yang merangkum seluruh aliran kas masuk dan keluar secara kronologis dan menjadi basis penyusunan LPJ Bendahara.',
    referenceRegulation: 'PMK No. 162/PMK.05/2013 tentang Kedudukan dan Tanggung Jawab Bendahara'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Aplikasi web yang digunakan untuk monitoring interaktif performa SAKTI seluruh Indonesia dan memantau status rekonsiliasi data SPAN adalah...',
    optionA: 'MonSAKTI (monsakti.kemenkeu.go.id)',
    optionB: 'Wikipedia',
    optionC: 'Instagram Kemenkeu',
    optionD: 'Google Play Store',
    correctAnswer: 'A',
    explanation: 'Portal MonSAKTI menyediakan laporan analitik harian, monitoring To Do List, pemantauan transaksi belanja, indikator IKPA, dan kepatuhan perbendaharaan.',
    referenceRegulation: 'Kepdirjen Perbendaharaan tentang Portal MonSAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Pada menu To Do List MonSAKTI satker muncul notifikasi: "Terdapat BAST yang belum dibuatkan SPP > 10 hari kerja". Mengapa notifikasi ini muncul dan apa dampaknya?',
    optionA: 'Sistem memberi peringatan dini (early warning) agar tagihan tidak melampaui norma 17 hari kerja yang dapat menurunkan nilai IKPA Penyelesaian Tagihan',
    optionB: 'Komputer server KPPN sedang offline',
    optionC: 'Akun operator satker dibajak',
    optionD: 'Tidak memiliki dampak apapun terhadap kinerja satker',
    correctAnswer: 'A',
    explanation: 'Menu To Do List di MonSAKTI didesain khusus sebagai instrumen pengawasan dini (early warning) agar Satker tidak melanggar tenggat waktu kepatuhan yang berdampak buruk pada IKPA.',
    referenceRegulation: 'Juknis Pengawasan Early Warning MonSAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Apakah yang dimaksud dengan konsep "Maker - Checker - Approver" dalam alur transaksi SAKTI?',
    optionA: 'Mekanisme kontrol internal bertingkat di mana transaksi dibuat oleh staf pelaksana (maker), diverifikasi oleh pengawas (checker), dan disahkan oleh pejabat berwenang (approver)',
    optionB: 'Metode memasak makanan di dapur kantor',
    optionC: 'Sistem permainan sepak bola antar-satker',
    optionD: 'Pola piket satpam malam hari',
    correctAnswer: 'A',
    explanation: 'Prinsip Maker-Checker-Approver merupakan standar internasional pengendalian internal perbankan dan perbendaharaan negara guna mencegah fraud dan human error.',
    referenceRegulation: 'Pedoman Tata Kelola Pengendalian Internal DJPb'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Berapakah jumlah digit kode Satuan Kerja (Kode Satker) resmi yang digunakan dalam SAKTI dan SPAN?',
    optionA: '6 (enam) digit angka unik',
    optionB: '2 digit huruf',
    optionC: '16 digit NIK',
    optionD: '20 digit kode pos',
    correctAnswer: 'A',
    explanation: 'Setiap Satker K/L di Indonesia diidentifikasi secara nasional oleh Kementerian Keuangan dengan 6 digit kode satker unik yang tercantum pada lembar DIPA.',
    referenceRegulation: 'PMK Tata Cara Pengalokasian dan Kodefikasi Anggaran'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Fitur "Kirim Data / Push Data" ke KPPN pada Modul Pembayaran SAKTI dilakukan saat status SPM berada pada level...',
    optionA: 'Setuju SPM oleh Pejabat Penandatangan SPM (Approver)',
    optionB: 'Draf awal oleh staf operator',
    optionC: 'Setelah disurvei oleh masyarakat',
    optionD: 'Saat satker ditutup',
    correctAnswer: 'A',
    explanation: 'Setelah PPSPM memvalidasi dan menginput kode OTP (persetujuan approver), sistem SAKTI secara otomatis melakukan push data elektronik (ADK SPM) ke server SPAN KPPN.',
    referenceRegulation: 'User Manual SAKTI Modul Pembayaran'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'PPSPM hendak menyetujui SPM Pengadaan Alat Komunikasi senilai Rp250.000.000. Saat klik "Generate OTP", SMS kode verifikasi tidak masuk ke ponsel pejabat. Tindakan apa yang dapat diambil?',
    optionA: 'Memeriksa alternatif pengiriman OTP melalui WhatsApp resmi Kemenkeu atau memastikan sinyal operator seluler dan masa aktif pulsa/nomor terdaftar',
    optionB: 'Meminta orang lain menandatangani SPM di kertas kosong',
    optionC: 'Memecahkan monitor komputer',
    optionD: 'Membatalkan seluruh pembelian alat kantor',
    correctAnswer: 'A',
    explanation: 'Kemenkeu menyediakan saluran pengiriman kode OTP SAKTI ganda (SMS Gateway dan WhatsApp Bot Resmi Kemenkeu). Pejabat dapat beralih ke notifikasi WhatsApp jika SMS terhambat.',
    referenceRegulation: 'Panduan Layanan OTP Multi-Channel Ditjen Perbendaharaan'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Apakah aplikasi SAKTI memerlukan biaya langganan bulanan atau lisensi berbayar dari Satker Kementerian/Lembaga?',
    optionA: 'Tidak ada biaya lisensi (disediakan gratis oleh Kementerian Keuangan untuk seluruh satker pengguna APBN)',
    optionB: 'Berbayar Rp5.000.000 per bulan',
    optionC: 'Dipotong dari gaji pegawai',
    optionD: 'Berbayar menggunakan mata uang asing',
    correctAnswer: 'A',
    explanation: 'Aplikasi SAKTI dikembangkan dan dipelihara secara mandiri oleh Kementerian Keuangan RI dan didistribusikan secara cuma-cuma (free) untuk seluruh instansi pemerintah pengguna APBN.',
    referenceRegulation: 'Kebijakan Pengelolaan TI Perbendaharaan Kemenkeu'
  },
  // Additional SAKTI Questions (26-55)
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Pada Modul Penganggaran SAKTI, proses pencatatan riwayat revisi anggaran diatur melalui mekanisme...',
    optionA: 'Tracking History Versi DIPA (Revisi ke-0, ke-1, ke-2, dst.) yang tersimpan secara terenkripsi',
    optionB: 'Menimpa file tanpa jejak audit trail',
    optionC: 'Penyimpanan di flashdisk masing-masing staf',
    optionD: 'Fotokopi berkas fisik',
    correctAnswer: 'A',
    explanation: 'SAKTI mencatat setiap versi revisi DIPA secara kronologis dan tidak dapat dihapus (immutable audit trail) untuk menjamin transparansi perubahan alokasi anggaran.',
    referenceRegulation: 'Pedoman Audit Trail Sistem Aplikasi Keuangan Kemenkeu'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Satker B mengalami selisih saldo kas pada laporan keuangan antara Modul Bendahara dengan Modul GLP di akhir triwulan. Langkah penelusuran apa yang harus dilakukan pertama kali oleh Analis Pengelola Keuangan APBN?',
    optionA: 'Mencocokkan Berita Acara Kas Modul Bendahara, memeriksa transaksi BKU yang belum divalidasi/dijurnal, dan mengecek mutasi kas transit UP di Modul GLP',
    optionB: 'Membuat jurnal penyesuaian fiktif untuk menyamakan angka',
    optionC: 'Menutup mata atas selisih tersebut',
    optionD: 'Mengganti bendahara pengeluaran secara mendadak',
    correctAnswer: 'A',
    explanation: 'Selisih antara Buku Kas Bendahara dan Buku Besar Akrual GLP umumnya bersumber dari transaksi penerimaan/pengeluaran kas yang belum dibukukan sempurna atau adanya SP2D transit yang belum disahkan.',
    referenceRegulation: 'Petunjuk Teknis Rekonsiliasi Internal SAKTI DJPb'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Sertifikat elektronik yang disematkan pada akun Pejabat Perbendaharaan SAKTI diterbitkan secara resmi oleh otoritas...',
    optionA: 'Balai Sertifikasi Elektronik (BSrE) - Badan Siber dan Sandi Negara (BSSN)',
    optionB: 'Kementerian Pariwisata',
    optionC: 'Perusahaan swasta asing',
    optionD: 'Lembaga survei pemilu',
    correctAnswer: 'A',
    explanation: 'Tanda Tangan Elektronik tersertifikasi pada sistem SAKTI difasilitasi melalui kerja sama Kemenkeu dengan BSrE BSSN guna menjamin kekuatan hukum dan anti-penyangkalan (non-repudiation).',
    referenceRegulation: 'UU No. 11/2008 jo UU No. 1/2024 tentang ITE & PMK TTE Kemenkeu'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Dalam Modul Piutang SAKTI, transaksi apa yang wajib dicatat oleh satker yang memiliki kewenangan memungut PNBP pelayanan?',
    optionA: 'Perekaman surat tagihan piutang PNBP, penyisihan piutang tak tertagih, dan pelunasan piutang PNBP',
    optionB: 'Pencatatan utang pribadi pegawai di koperasi',
    optionC: 'Pencatatan pinjaman modal usaha warung',
    optionD: 'Pencatatan hadiah ulang tahun kantor',
    correctAnswer: 'A',
    explanation: 'Modul Piutang SAKTI menatausahakan piutang negara bukan pajak: surat tagihan pertama, kedua, ketiga, penyerahan berkas piutang macet ke PUPN/KPKNL, serta perhitungan penyisihan piutang.',
    referenceRegulation: 'PMK tentang Tata Cara Penatausahaan Piutang Negara'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Satker ingin membatalkan SPP yang sudah disahkan menjadi SPM oleh PPSPM, namun SPM tersebut BELUM dikirim ke SPAN KPPN. Bagaimana tata cara pembatalannya di SAKTI?',
    optionA: 'PPSPM melakukan penolakan/pembatalan SPM pada menu Persetujuan SPM, sehingga status kembali ke draft SPP dan dapat dibatalkan oleh PPK/Operator',
    optionB: 'Satker harus meminta surat penetapan dari pengadilan',
    optionC: 'SPM tidak bisa dibatalkan selamanya',
    optionD: 'Operator langsung menghapus database server pusat',
    correctAnswer: 'A',
    explanation: 'Alur pembatalan transaksi berjenjang dari atas ke bawah: Approver (PPSPM) membatalkan status persetujuan SPM terlebih dahulu, baru kemudian PPK membatalkan SPP.',
    referenceRegulation: 'SOP Pembatalan Dokumen Pembayaran SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Browser web apa sajakah yang direkomendasikan untuk mengakses aplikasi SAKTI agar fitur dan tampilannya berjalan optimal?',
    optionA: 'Google Chrome atau Mozilla Firefox versi terbaru dengan koneksi aman HTTPS',
    optionB: 'Internet Explorer versi 6 tahun 2001',
    optionC: 'Browser konsol game',
    optionD: 'Aplikasi pemutar musik MP3',
    correctAnswer: 'A',
    explanation: 'SAKTI dirancang berbasis teknologi web modern yang kompatibel dan teruji pada peramban Google Chrome dan Mozilla Firefox dengan enkripsi TLS 1.3.',
    referenceRegulation: 'Spesifikasi Teknis Perangkat Kerja SAKTI DJPb'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Menu apa di SAKTI Modul Komitmen yang digunakan untuk mencatat Berita Acara Serah Terima (BAST) pekerjaan jasa konsultansi?',
    optionA: 'Menu BAST / Penerimaan Barang dan Jasa',
    optionB: 'Menu Registrasi DIPA',
    optionC: 'Menu Pembayaran Gaji',
    optionD: 'Menu Laporan Keuangan',
    correctAnswer: 'A',
    explanation: 'Penerimaan barang, jasa, atau sertifikat penyelesaian pekerjaan direkam pada menu BAST di Modul Komitmen sebagai dasar penerbitan SPP-LS.',
    referenceRegulation: 'User Guide Modul Komitmen SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'ANALISIS',
    questionText: 'Satker A mendapati transaksi SP2D GUP sudah terbit pada 20 Februari, namun saat membuka Modul Bendahara, saldo kas bank belum bertambah. Apa penyebab yang paling mungkin?',
    optionA: 'Operator Modul Bendahara belum menjalankan menu "Perekaman SP2D Masuk / Transaksi SP2D" untuk memindahbukukan aliran kas SP2D ke BKU',
    optionB: 'Uang kas negara dicuri secara online',
    optionC: 'KPPN membatalkan sepihak SP2D tersebut',
    optionD: 'Bank persepsi bangkrut',
    correctAnswer: 'A',
    explanation: 'Setelah SP2D GUP terbit di SPAN, bendahara pengeluaran harus mencatat penerimaan SP2D tersebut ke dalam BKU Modul Bendahara agar saldo kas bertambah.',
    referenceRegulation: 'Juknis Pembukuan Bendahara Pengeluaran SAKTI'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'MUDAH',
    questionText: 'Dalam rangka menjaga keamanan akun SAKTI, kebijakan penggantian password yang dianjurkan oleh Kementerian Keuangan adalah...',
    optionA: 'Mengganti password secara berkala (misal tiap 90 hari), menggunakan kombinasi huruf besar, kecil, angka, dan simbol, serta tidak membagikan kepada siapapun',
    optionB: 'Menggunakan kata sandi "123456" untuk semua pegawai',
    optionC: 'Menulis kata sandi di kertas stiker dan menempelkannya di monitor',
    optionD: 'Memberikan password kepada rekanan pihak ketiga',
    correctAnswer: 'A',
    explanation: 'Kebijakan Pengamanan Informasi Kemenkeu mewajibkan seluruh pengelola keuangan negara menjaga kerahasiaan kredensial dan menerapkan autentikasi yang kuat.',
    referenceRegulation: 'Instruksi Menteri Keuangan tentang Pengamanan Informasi dan Ruang Siber'
  },
  {
    topic: 'Aplikasi SAKTI & SPAN',
    difficulty: 'SEDANG',
    questionText: 'Apa fungsi utama menu "Monitoring Kirim / Terima SP2D" di SAKTI?',
    optionA: 'Memantau posisi proses dokumen pembayaran apakah masih draft, menunggu validasi KPPN, ditolak, atau telah sukses terbit SP2D berserta nomor SP2D-nya',
    optionB: 'Memeriksa harga saham dunia',
    optionC: 'Melihat prakiraan cuaca kota Semarang',
    optionD: 'Mengunduh musik legal',
    correctAnswer: 'A',
    explanation: 'Menu monitoring SP2D memungkinkan satker melacak perjalanan SPM dari pengiriman ADK, validasi SPAN, hingga keluarnya nomor SP2D secara transparan.',
    referenceRegulation: 'Panduan Operasional SAKTI'
  }
];
