export interface RawQuestion {
  topic: string;
  difficulty: 'MUDAH' | 'SEDANG' | 'ANALISIS';
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  referenceRegulation: string;
}

export const ikpaQuestions: RawQuestion[] = [
  // 1-15: Deviasi Hal III DIPA
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'MUDAH',
    questionText: 'Berapakah batas ambang toleransi deviasi bulanan antara realisasi anggaran dengan Rencana Penarikan Dana (RPD) Hal III DIPA agar Satker tetap memperoleh nilai maksimal (100) pada indikator IKPA?',
    optionA: 'Maksimal 5%',
    optionB: 'Maksimal 10%',
    optionC: 'Maksimal 15%',
    optionD: 'Maksimal 20%',
    correctAnswer: 'A',
    explanation: 'Sesuai dengan Peraturan Direktur Jenderal Perbendaharaan No. PER-5/PB/2022, ambang toleransi deviasi per jenis belanja setiap bulan adalah maksimal 5% untuk memperoleh nilai maksimal 100.',
    referenceRegulation: 'PER-5/PB/2022 Petunjuk Teknis IKPA Lampiran I'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'MUDAH',
    questionText: 'Kapan batas waktu penyampaian usulan pemutakhiran RPD Halaman III DIPA reguler dibuka pada setiap awal triwulan berkenaan?',
    optionA: 'Paling lambat 10 (sepuluh) hari kerja pertama triwulan berkenaan',
    optionB: 'Paling lambat akhir bulan pertama triwulan berjalan',
    optionC: 'Paling lambat 15 hari kalender sebelum triwulan berakhir',
    optionD: 'Bebas dimutakhirkan setiap hari kerja tanpa batas waktu',
    correctAnswer: 'A',
    explanation: 'Pemutakhiran RPD Hal III DIPA reguler dibuka pada 10 (sepuluh) hari kerja pertama setiap awal triwulan untuk memberikan kesempatan satker menyelaraskan rencana penarikan kas dengan tren realisasi riil.',
    referenceRegulation: 'PER-5/PB/2022 Pasal 4 ayat (3)'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'ANALISIS',
    questionText: 'Satker KPPN Pratama memiliki RPD Belanja Barang bulan Februari sebesar Rp400.000.000. Realisasi riil SP2D belanja barang yang diterbitkan pada bulan Februari adalah Rp368.000.000. Berapakah persentase deviasi dan bagaimana dampaknya pada nilai IKPA?',
    optionA: 'Deviasi 8%, melebihi ambang batas toleransi 5% sehingga nilai berkurang',
    optionB: 'Deviasi 4%, berada di bawah ambang batas toleransi sehingga bernilai 100',
    optionC: 'Deviasi 12%, terkena penalti nilai 50%',
    optionD: 'Deviasi 3,2%, memperoleh predikat sempurna',
    correctAnswer: 'A',
    explanation: 'Rumus: |Realisasi - RPD| / RPD = |368.000.000 - 400.000.000| / 400.000.000 = 32.000.000 / 400.000.000 = 0,08 atau 8%. Karena 8% > 5%, maka deviasi melampaui batas toleransi 5% dan nilai indikator Deviasi Hal III DIPA mengalami pemotongan skor.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran I Matriks Perhitungan Deviasi'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'SEDANG',
    questionText: 'Jenis belanja apa sajakah yang dihitung dan dinilai dalam indikator Deviasi Halaman III DIPA?',
    optionA: 'Belanja Pegawai (51), Belanja Barang (52), dan Belanja Modal (53)',
    optionB: 'Hanya Belanja Barang (52) dan Belanja Modal (53)',
    optionC: 'Seluruh jenis belanja termasuk Belanja Bunga dan Subsidi',
    optionD: 'Hanya Belanja Modal (53) berskala kontraktual',
    correctAnswer: 'A',
    explanation: 'Indikator Deviasi Halaman III DIPA menghitung selisih realisasi terhadap RPD pada 3 jenis belanja utama yaitu Belanja Pegawai (51), Belanja Barang (52), dan Belanja Modal (53). Belanja Bansos dapat diperhitungkan jika ada alokasinya.',
    referenceRegulation: 'PER-5/PB/2022 Bab II Indikator Deviasi Hal III DIPA'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'SEDANG',
    questionText: 'Bagaimanakah perlakuan terhadap RPD Halaman III DIPA pada triwulan I jika satker terlambat menyampaikan pemutakhiran?',
    optionA: 'Penilaian deviasi akan didasarkan pada RPD awal DIPA petikan tanpa pemutakhiran',
    optionB: 'Nilai IKPA indikator Deviasi Hal III otomatis diberikan nilai 0 untuk seluruh tahun',
    optionC: 'DIPA satker diblokir secara otomatis oleh sistem SAKTI',
    optionD: 'Satker diberikan izin merevisi di bulan berikutnya tanpa sanksi',
    correctAnswer: 'A',
    explanation: 'Jika satker tidak memanfaatkan jendela pemutakhiran 10 hari kerja pertama triwulan I, data pembanding yang digunakan adalah baseline RPD awal DIPA yang disahkan di awal tahun anggaran.',
    referenceRegulation: 'Juknis Monitoring IKPA DJPb Kemenkeu'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'ANALISIS',
    questionText: 'Satker Balai Litbang memiliki RPD Belanja Modal bulan Juni sebesar Rp1.000.000.000. Akibat gagal lelang, realisasi SP2D bulan Juni hanya Rp100.000.000. Tindakan mitigasi apa yang seharusnya dilakukan satker sebelum berakhirnya Triwulan II?',
    optionA: 'Mengajukan pemutakhiran RPD Hal III DIPA pada 10 hari kerja pertama Triwulan II agar target penarikan digeser ke Triwulan III/IV',
    optionB: 'Menerbitkan SP2D fiktif untuk memenuhi penyerapan',
    optionC: 'Mengubah akun belanja modal menjadi belanja pegawai',
    optionD: 'Mengabaikan saja karena deviasi belanja modal tidak dinilai',
    correctAnswer: 'A',
    explanation: 'Ketika teridentifikasi adanya potensi keterlambatan lelang atau penundaan termin pekerjaan modal, satker wajib proaktif memutakhirkan jadwal penarikan RPD Hal III DIPA pada periode pemutakhiran triwulanan agar deviasi tidak anjlok.',
    referenceRegulation: 'Surat Edaran Dirjen Perbendaharaan tentang Mitigasi Risiko Kinerja Pelaksanaan Anggaran'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'MUDAH',
    questionText: 'Aplikasi resmi milik Kementerian Keuangan yang digunakan satker untuk memantau nilai Deviasi Halaman III DIPA harian dan bulanan secara online adalah...',
    optionA: 'MonSAKTI (Monitoring SAKTI)',
    optionB: 'SIAP-DJA',
    optionC: 'DJP Online Pajak',
    optionD: 'LPSE LKPP',
    correctAnswer: 'A',
    explanation: 'MonSAKTI (monsakti.kemenkeu.go.id) merupakan portal terpusat untuk monitoring pelaksanaan anggaran, IKPA, To Do List, rekonsiliasi, dan kepatuhan satker kementerian/lembaga.',
    referenceRegulation: 'PER-5/PB/2022 & Kepdirjen Perbendaharaan tentang MonSAKTI'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'SEDANG',
    questionText: 'Apakah penarikan dana melalui SPM GUP (Penggantian Uang Persediaan) diperhitungkan dalam realisasi RPD Halaman III DIPA?',
    optionA: 'Ya, seluruh SP2D GUP yang terbit pada bulan berkenaan dihitung sebagai realisasi belanja',
    optionB: 'Tidak, hanya SPM LS pihak ketiga yang dihitung',
    optionC: 'Hanya jika nilainya di atas Rp100 juta',
    optionD: 'Hanya jika telah dibuatkan BAST kontraktual',
    correctAnswer: 'A',
    explanation: 'Seluruh SP2D pengeluaran kas riil atas beban APBN (baik SPM-LS maupun SPM-GUP/PTUP) yang membebani pagu belanja 51, 52, dan 53 pada bulan bersangkutan diperhitungkan sebagai realisasi belanja terhadap RPD.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran I'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'ANALISIS',
    questionText: 'Pada tanggal 28 Maret, Satker mendapati rencana penarikan RPD Maret belanja modal Rp200.000.000 belum terserap karena penyedia baru mengajukan tagihan tanggal 27 Maret. Jika SPM diajukan tanggal 29 Maret dan SP2D terbit 2 April, apa konsekuensinya?',
    optionA: 'Realisasi tercatat di bulan April, sehingga bulan Maret terjadi deviasi 100% pada belanja modal tersebut',
    optionB: 'Realisasi tetap dicatat di bulan Maret karena tanggal SPM di bulan Maret',
    optionC: 'Deviasi Maret dihapuskan oleh sistem SPAN',
    optionD: 'Satker dapat meminta surat rekomendasi pembatalan deviasi ke Kanwil DJPb',
    correctAnswer: 'A',
    explanation: 'Realisasi anggaran dihitung berdasarkan tanggal terbit SP2D oleh KPPN (basis kas). Bila SP2D baru terbit 2 April, maka realisasi masuk ke bulan April, mengakibatkan bulan Maret mengalami under-spending deviasi yang sangat tajam.',
    referenceRegulation: 'PER-5/PB/2022 Penilaian Deviasi Berdasarkan Tanggal SP2D'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'SEDANG',
    questionText: 'Apa rumus dasar perhitungan deviasi bulanan per jenis belanja pada indikator Deviasi Hal III DIPA?',
    optionA: 'Deviasi = |Realisasi - RPD| / RPD x 100%',
    optionB: 'Deviasi = (RPD - Realisasi) / Realisasi x 100%',
    optionC: 'Deviasi = Realisasi / Pagu DIPA Tahunan x 100%',
    optionD: 'Deviasi = (Pagu - RPD) / Pagu x 100%',
    correctAnswer: 'A',
    explanation: 'Rumus resmi deviasi IKPA mengukur selisih mutlak (nilai absolut) antara realisasi kas terhadap target RPD dibagi nilai target RPD dikalikan 100%.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran Indikator Deviasi'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'SEDANG',
    questionText: 'Jika pada suatu bulan tertentu nilai RPD Belanja Modal suatu satker adalah Rp0, namun satker menerbitkan SP2D belanja modal sebesar Rp50.000.000, bagaimana dampaknya?',
    optionA: 'Terjadi deviasi tidak terencana 100% yang menurunkan nilai indikator belanja modal bulan tersebut',
    optionB: 'Satker memperoleh bonus poin karena berhasil menyerap anggaran lebih cepat',
    optionC: 'Nilai IKPA bulan tersebut otomatis dibatalkan',
    optionD: 'Tidak berdampak karena RPD awal adalah Rp0',
    correctAnswer: 'A',
    explanation: 'Penarikan dana tanpa rencana (RPD Rp0 namun ada realisasi) mengakibatkan deviasi maksimal (100%) dan mengurangi nilai indikator secara signifikan karena mencerminkan perencanaan kas yang tidak disiplin.',
    referenceRegulation: 'Pedoman Penilaian Kualitas RPD DJPb'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'MUDAH',
    questionText: 'Peran pejabat perbendaharaan manakah di Satker yang paling bertanggung jawab dalam menyusun rencana penarikan dana bulanan?',
    optionA: 'Pejabat Pembuat Komitmen (PPK) berkoordinasi dengan KPA dan Bendahara',
    optionB: 'Hanya Pengemudi dan Pramubakti',
    optionC: 'Auditor BPK RI',
    optionD: 'Customer Service Bank Persepsi',
    correctAnswer: 'A',
    explanation: 'PPK bersama tim perencana dan pengelola keuangan satker bertugas merumuskan jadwal penyerapan kegiatan dan jadwal penarikan dana sesuai agenda eksekusi pengadaan.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 12'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'ANALISIS',
    questionText: 'Satker A memiliki 3 jenis belanja: Belanja Pegawai (Deviasi 2%), Belanja Barang (Deviasi 4%), Belanja Modal (Deviasi 18%). Berapakah jenis belanja yang memenuhi batas toleransi nilai maksimal 100?',
    optionA: '2 jenis belanja (Pegawai dan Barang)',
    optionB: 'Semua jenis belanja memenuhi',
    optionC: 'Hanya 1 jenis belanja (Modal)',
    optionD: 'Tidak ada satupun yang memenuhi',
    correctAnswer: 'A',
    explanation: 'Ambang batas nilai maksimal adalah deviasi <= 5%. Belanja Pegawai (2% <= 5%) dan Belanja Barang (4% <= 5%) memenuhi, sedangkan Belanja Modal (18% > 5%) tidak memenuhi.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran I'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'SEDANG',
    questionText: 'Mengapa disiplin Rencana Penarikan Dana (RPD) pada Hal III DIPA sangat krusial bagi Bendahara Umum Negara (BUN)?',
    optionA: 'Untuk menjaga manajemen likuiditas kas negara, optimalisasi saldo kas, dan mencegah idle cash',
    optionB: 'Hanya sebagai formalitas administrasi laporan akhir tahun',
    optionC: 'Agar dana APBN bisa diinvestasikan di pasar kripto oleh KPPN',
    optionD: 'Untuk memperlambat pembayaran kepada rekanan pemerintah',
    correctAnswer: 'A',
    explanation: 'BUN mengelola kas negara berbasis Cash Forecasting. Ketepatan RPD satker memungkinkan BUN merencanakan penempatan kas, menghindari kekurangan likuiditas, dan mencegah penumpukan saldo kas menganggur (idle cash).',
    referenceRegulation: 'UU No. 1/2004 tentang Perbendaharaan Negara & Grand Design Treasury Management'
  },
  {
    topic: 'IKPA - Deviasi Hal III DIPA',
    difficulty: 'ANALISIS',
    questionText: 'Di awal triwulan III (bulan Juli), Satker B berencana melaksanakan 5 paket renovasi gedung di bulan September senilai Rp800.000.000. Tindakan apa yang tepat pada pemutakhiran RPD Hal III DIPA?',
    optionA: 'Mengalokasikan RPD Rp800.000.000 pada bulan September dan memastikan lelang selesai sebelum akhir Agustus',
    optionB: 'Membagi rata RPD Rp800.000.000 ke bulan Januari, Februari, dan Maret yang sudah lewat',
    optionC: 'Menaruh seluruh RPD di bulan Juli padahal belum ada kontrak kerja',
    optionD: 'Membiarkan RPD bulan September Rp0 lalu menarik uang sekaligus di akhir tahun',
    correctAnswer: 'A',
    explanation: 'Pemutakhiran yang berkualitas menyelaraskan jadwal penyelesaian pekerjaan dan pembayaran termin dengan bulan RPD yang bersangkutan sehingga saat tagihan cair tidak terjadi deviasi.',
    referenceRegulation: 'Panduan Praktis Perencanaan Kas Satker Kemenkeu'
  },

  // 16-25: Revisi DIPA
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'MUDAH',
    questionText: 'Dalam formula penilaian indikator Pengelolaan Revisi DIPA pada IKPA, berapa kalikah frekuensi revisi DIPA maksimal per triwulan yang diperbolehkan agar satker tidak terkena pemotongan nilai?',
    optionA: 'Maksimal 1 kali revisi per triwulan yang diperhitungkan',
    optionB: 'Maksimal 5 kali revisi per triwulan',
    optionC: 'Maksimal 10 kali revisi per bulan',
    optionD: 'Tidak dibatasi sama sekali jumlah revisinya',
    correctAnswer: 'A',
    explanation: 'Dalam IKPA (PER-5/PB/2022), frekuensi revisi anggaran yang diperhitungkan dibatasi maksimal 1 kali per triwulan pada setiap jenis kewenangan revisi agar mencerminkan konsistensi perencanaan anggaran.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran II Indikator Revisi DIPA'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'SEDANG',
    questionText: 'Manakah jenis revisi DIPA berikut ini yang TIDAK mengurangi nilai indikator Revisi DIPA pada IKPA?',
    optionA: 'Revisi pemutakhiran data administratif atau revisi akibat kebijakan strategis pemerintah pusat (automatic adjustment / instruksi Presiden)',
    optionB: 'Revisi pergeseran antar rincian output dalam satu satker tanpa urgensi khusus',
    optionC: 'Revisi akibat kelalaian satker salah memasukkan akun belanja',
    optionD: 'Revisi pemecahan paket pekerjaan konstruksi yang terlambat lelang',
    correctAnswer: 'A',
    explanation: 'Revisi administratif dan revisi yang diakibatkan kebijakan pemerintah pusat yang bersifat mandatory / ex-officio dikecualikan dari perhitungan frekuensi revisi yang mengurangi nilai IKPA.',
    referenceRegulation: 'PMK tentang Tata Cara Revisi Anggaran & PER-5/PB/2022'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'MUDAH',
    questionText: 'Instansi vertikal DJPb di tingkat provinsi yang berwenang mengesahkan revisi DIPA kewenangan Kanwil adalah...',
    optionA: 'Kantor Wilayah Direktorat Jenderal Perbendaharaan (Kanwil DJPb)',
    optionB: 'Kantor Pelayanan Pajak (KPP)',
    optionC: 'Kantor Pertanahan ATR/BPN',
    optionD: 'Inspektorat Daerah Provinsi',
    correctAnswer: 'A',
    explanation: 'Pengesahan revisi anggaran kewenangan Kanwil diajukan melalui aplikasi SAKTI dan disahkan oleh Kepala Kanwil DJPb provinsi setempat.',
    referenceRegulation: 'PMK Tata Cara Revisi Anggaran'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'ANALISIS',
    questionText: 'Satker Balai Pelatihan melakukan 4 kali pengajuan revisi anggaran DIPA dalam kurun waktu Triwulan II. Berapakah frekuensi revisi yang dinilai berlebih dalam perhitungan formula IKPA Triwulan II?',
    optionA: '3 kali revisi berlebih (hanya 1 kali yang ditoleransi untuk nilai sempurna)',
    optionB: 'Semua 4 kali revisi diterima penuh',
    optionC: '2 kali revisi berlebih',
    optionD: 'Tidak ada konsekuensi terhadap nilai IKPA',
    correctAnswer: 'A',
    explanation: 'Toleransi revisi optimal per triwulan adalah 1 kali. Jika dilakukan 4 kali, maka terjadi kelebihan 3 kali revisi yang akan mengurangi skor indikator Kualitas Revisi Anggaran.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran II'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'SEDANG',
    questionText: 'Salah satu prinsip efektivitas revisi anggaran menurut Ditjen Perbendaharaan adalah...',
    optionA: 'Dilakukan secara terencana, konsolidatif, dan tidak sporadis berulang kali',
    optionB: 'Diajukan sesering mungkin setiap ada sisa belanja Rp10.000',
    optionC: 'Hanya diajukan 1 hari sebelum akhir tahun anggaran',
    optionD: 'Dilakukan tanpa melibatkan persetujuan KPA',
    correctAnswer: 'A',
    explanation: 'Revisi anggaran sebaiknya dikonsolidasikan dan dipetakan secara matang dalam satu usulan revisi berkala, bukan diajukan secara sporadis setiap minggu yang menandakan lemahnya perencanaan.',
    referenceRegulation: 'Surat Edaran Dirjen Perbendaharaan Kualitas Belanja'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'MUDAH',
    questionText: 'Aplikasi yang digunakan satker untuk menyusun usulan RKA-K/L DIPA dan melakukan proses pengajuan revisi anggaran adalah...',
    optionA: 'SAKTI Modul Penganggaran',
    optionB: 'Aplikasi Silabi',
    optionC: 'Aplikasi SPM Offline versi 2014',
    optionD: 'Aplikasi SIPKD Kemendagri',
    correctAnswer: 'A',
    explanation: 'Penyusunan rencana kerja anggaran serta proses revisi anggaran Satker K/L dilakukan secara paperless dan terintegrasi melalui SAKTI Modul Penganggaran.',
    referenceRegulation: 'Juknis SAKTI Modul Penganggaran Ditjen Perbendaharaan'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'ANALISIS',
    questionText: 'Suatu satker ingin melakukan revisi pergeseran pagu belanja antar Subkomponen dalam satu Komponen tanpa mengubah total pagu jenis belanja. Kewenangan pengesahan revisi tersebut berada pada...',
    optionA: 'Kuasa Pengguna Anggaran (KPA) melalui Surat Penetapan Revisi Anggaran KPA',
    optionB: 'Presiden Republik Indonesia',
    optionC: 'DPR RI Komisi Keuangan',
    optionD: 'Kepala Kantor Pos',
    correctAnswer: 'A',
    explanation: 'Pergeseran anggaran dalam satu output/komponen yang tidak mengubah total alokasi merupakan kewenangan Kuasa Pengguna Anggaran (KPA) dan dicatatkan pada sistem SAKTI.',
    referenceRegulation: 'PMK tentang Tata Cara Revisi Anggaran Tahun Berkenaan'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'SEDANG',
    questionText: 'Apa dampak revisi DIPA yang mengubah pagu atau alokasi bulanan terhadap Halaman III DIPA?',
    optionA: 'Satker wajib menyusun dan menyelaraskan kembali RPD Halaman III DIPA agar tidak timbul deviasi tak terduga',
    optionB: 'Halaman III DIPA akan otomatis menyesuaikan tanpa perlu diperiksa satker',
    optionC: 'Revisi DIPA otomatis membatalkan seluruh SP2D yang telah terbit sebelumnya',
    optionD: 'Tidak ada hubungan antara pagu DIPA dengan Halaman III DIPA',
    correctAnswer: 'A',
    explanation: 'Setiap kali revisi pagu disahkan, distribusi RPD pada Halaman III DIPA dapat mengalami pergeseran. Satker harus segera memverifikasi dan memastikan RPD sesuai dengan target penarikan riil.',
    referenceRegulation: 'PER-5/PB/2022'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'MUDAH',
    questionText: 'Batas akhir pengajuan revisi anggaran reguler pada akhir tahun anggaran biasanya diatur melalui...',
    optionA: 'Peraturan Direktur Jenderal Perbendaharaan tentang Pedoman Penerimaan dan Pengeluaran Negara Akhir Tahun (Langkah-Langkah Akhir Tahun / LLAT)',
    optionB: 'Surat kabar daerah setempat',
    optionC: 'Undang-Undang Pemilihan Umum',
    optionD: 'Instruksi Asosiasi Kontraktor Nasional',
    correctAnswer: 'A',
    explanation: 'Setiap akhir tahun, Ditjen Perbendaharaan menerbitkan Perdirjen LLAT yang memuat tenggat waktu (cut-off) pengajuan revisi anggaran, penerbitan SPM, dan pendaftaran kontrak.',
    referenceRegulation: 'Perdirjen DJPb tentang Langkah-Langkah Akhir Tahun Anggaran (LLAT)'
  },
  {
    topic: 'IKPA - Revisi DIPA',
    difficulty: 'SEDANG',
    questionText: 'Revisi anggaran yang memerlukan persetujuan Direktorat Jenderal Anggaran (DJA) pusat antara lain meliputi...',
    optionA: 'Perubahan pagu total anggaran belanja, penggunaan saldo anggaran lebih (SAL), dan pembentukan output baru yang bersifat strategis',
    optionB: 'Perbaikan nomor telepon bendahara di lembar DIPA',
    optionC: 'Pencetakan ulang kuitansi bensin operasional',
    optionD: 'Penambahan jumlah panitia lomba 17 Agustus satker',
    correctAnswer: 'A',
    explanation: 'Revisi yang menyangkut kebijakan fiskal makro, penambahan pagu DIPA total, pinjaman/hibah luar negeri, atau target PNBP baru merupakan kewenangan DJA Kementerian Keuangan.',
    referenceRegulation: 'PMK Tata Cara Revisi Anggaran'
  },

  // 26-35: Penyerapan Anggaran
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'MUDAH',
    questionText: 'Berapakah target kumulatif penyerapan anggaran Triwulan I yang umumnya ditetapkan dalam standar IKPA untuk Belanja Barang (52)?',
    optionA: 'Minimal 15%',
    optionB: 'Minimal 50%',
    optionC: 'Minimal 75%',
    optionD: 'Minimal 100%',
    correctAnswer: 'A',
    explanation: 'Dalam ketentuan IKPA, target penyerapan belanja barang pada Triwulan I umumnya minimal 15% (atau 20% sesuai simplifikasi nasional terkini) untuk mencegah penumpukan belanja di akhir tahun.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran III Target Penyerapan Anggaran'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'SEDANG',
    questionText: 'Berapakah target kumulatif penyerapan anggaran pada akhir Triwulan III untuk memperoleh skor optimal pada indikator Penyerapan Anggaran?',
    optionA: 'Minimal 70% atau 75% bergantung jenis belanja',
    optionB: 'Minimal 20%',
    optionC: 'Minimal 99%',
    optionD: 'Maksimal 30%',
    correctAnswer: 'A',
    explanation: 'Target penyerapan triwulanan dirancang progresif: TW I (15-20%), TW II (50%), TW III (70-75%), dan TW IV (90-95%) agar pola belanja negara tidak menumpuk di bulan Desember.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran III'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'ANALISIS',
    questionText: 'Satker Balai Konservasi memiliki pagu Belanja Modal sebesar Rp2.000.000.000. Pada akhir Triwulan II, realisasi SP2D belanja modal baru mencapai Rp600.000.000 (30%), sementara target TW II adalah 40%. Berapa rupiah kekurangan realisasi untuk mencapai target TW II?',
    optionA: 'Rp200.000.000 (40% x Rp2.000.000.000 = Rp800.000.000)',
    optionB: 'Rp400.000.000',
    optionC: 'Rp100.000.000',
    optionD: 'Rp50.000.000',
    correctAnswer: 'A',
    explanation: 'Target 40% dari Rp2 Miliar = Rp800.000.000. Realisasi saat ini Rp600.000.000. Kekurangan = Rp800.000.000 - Rp600.000.000 = Rp200.000.000.',
    referenceRegulation: 'Matematika Kinerja Anggaran DJPb'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'MUDAH',
    questionText: 'Mengapa fenomena penyerapan anggaran menumpuk di Triwulan IV (ujung tahun anggaran) dinilai merugikan perekonomian?',
    optionA: 'Menghambat perputaran ekonomi sejak dini, menimbulkan risiko ketergesaan pekerjaan, dan memicu idle cash perbankan',
    optionB: 'Karena KPPN tutup di bulan Desember',
    optionC: 'Karena uang kas negara akan hangus otomatis di bulan Juli',
    optionD: 'Karena pegawai satker dilarang lembur di akhir tahun',
    correctAnswer: 'A',
    explanation: 'Pola belanja menumpuk di akhir tahun (backloading) menyebabkan stimulus fiskal APBN terlambat mengalir ke masyarakat dan meningkatkan risiko kegagalan proyek akibat waktu yang sempit.',
    referenceRegulation: 'Kajian Fiskal Regional Ditjen Perbendaharaan'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'SEDANG',
    questionText: 'Manakah jenis belanja berikut yang penyerapan anggarannya biasanya paling stabil dan merata setiap bulan sepanjang tahun?',
    optionA: 'Belanja Pegawai (Akun 51) berupa gaji pokok dan tunjangan tetap',
    optionB: 'Belanja Modal Gedung dan Bangunan (Akun 53)',
    optionC: 'Belanja Bantuan Sosial Non-Terencana (Akun 57)',
    optionD: 'Belanja Darurat Bencana Alam',
    correctAnswer: 'A',
    explanation: 'Belanja pegawai reguler memiliki pola rutin dan teratur setiap awal bulan sehingga tingkat penyerapannya linier sekitar 8,3% per bulan.',
    referenceRegulation: 'Analisis Realisasi Belanja APBN DJPb'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'ANALISIS',
    questionText: 'Satker X memiliki DIPA yang sebagian anggarannya berstatus tanda bintang (blokir DIPA) senilai Rp500.000.000 dari total pagu Rp2.000.000.000. Dalam penilaian IKPA indikator penyerapan anggaran, apakah pagu yang diblokir tetap dihitung sebagai pembagi?',
    optionA: 'Ya, pagu pembagi tetap menggunakan total pagu DIPA aktif, sehingga satker harus segera menyelesaikan dokumen pembukaan blokir',
    optionB: 'Tidak, sistem otomatis memotong pagu pembagi menjadi Rp1.500.000.000',
    optionC: 'Pagu blokir diganti uang tunai oleh KPPN',
    optionD: 'Satker dibebaskan dari kewajiban menyerap anggaran',
    correctAnswer: 'A',
    explanation: 'Pagu DIPA yang masih diblokir tetap menjadi pembagi pada indikator penyerapan, sehingga menjadi kewajiban satker dan K/L untuk segera memenuhi dokumen persyaratan pembukaan blokir.',
    referenceRegulation: 'PER-5/PB/2022 Kebijakan Pagu Blokir IKPA'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'SEDANG',
    questionText: 'Apa strategi terbaik untuk mempercepat penyerapan anggaran pada Belanja Modal di awal tahun anggaran (Triwulan I)?',
    optionA: 'Melakukan lelang dini (pra-DIPA) sebelum tahun anggaran berjalan dan menuntaskan kontrak segera setelah DIPA disahkan',
    optionB: 'Menunggu bulan Oktober baru mengumumkan tender',
    optionC: 'Membayar lunas seluruh pekerjaan sebelum barang diterima',
    optionD: 'Mengganti rekanan lokal dengan rekanan luar negeri',
    correctAnswer: 'A',
    explanation: 'Lelang pra-DIPA diatur dalam regulasi pengadaan barang/jasa pemerintah agar penandatanganan kontrak dan penerbitan SP2D uang muka dapat dilakukan langsung pada awal Januari.',
    referenceRegulation: 'Perpres No. 16/2018 jo Perpres No. 12/2021 tentang PBJ Pemerintah'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'MUDAH',
    questionText: 'Dokumen apa yang menandai bahwa pengeluaran anggaran telah sah membebani kas negara dan dihitung sebagai realisasi penyerapan?',
    optionA: 'Surat Perintah Pencairan Dana (SP2D)',
    optionB: 'Surat Perintah Membayar (SPM)',
    optionC: 'Kuitansi bermeterai toko',
    optionD: 'Nota dinas permohonan dana',
    correctAnswer: 'A',
    explanation: 'Basis realisasi belanja negara di Indonesia adalah basis kas, di mana realisasi diakui saat kas negara dicairkan melalui penerbitan SP2D oleh KPPN selaku Kuasa BUN.',
    referenceRegulation: 'UU No. 1/2004 tentang Perbendaharaan Negara'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'ANALISIS',
    questionText: 'Sebuah satker mengalami kendala pengadaan sehingga sisa pagu belanja barang sebesar Rp100.000.000 diperkirakan tidak dapat terserap hingga 31 Desember. Apa yang sebaiknya dilakukan secara akuntabel?',
    optionA: 'Mencatatkan sisa anggaran tersebut sebagai sisa hemat/efisiensi dan tidak memaksakan belanja fiktif',
    optionB: 'Menarik uang tunai melalui UP dan menyimpannya di brankas pribadi bendahara',
    optionC: 'Mentransfer dana ke rekening pribadi PPK untuk dibelanjakan tahun depan',
    optionD: 'Membuat kuitansi palsu belanja alat tulis kantor',
    correctAnswer: 'A',
    explanation: 'Integritas pengelolaan keuangan negara melarang keras penyerapan semu atau manipulasi kuitansi/UP. Sisa pagu yang tidak terserap harus dipertanggungjawabkan secara sah sebagai sisa anggaran (efisiensi/tidak terserap).',
    referenceRegulation: 'UU No. 1/2004 & UU No. 31/1999 jo UU No. 20/2001 (Pemberantasan Tindak Pidana Korupsi)'
  },
  {
    topic: 'IKPA - Penyerapan Anggaran',
    difficulty: 'SEDANG',
    questionText: 'Dalam aplikasi MonSAKTI, menu apa yang dapat digunakan untuk melihat perbandingan pagu, realisasi, dan persentase penyerapan per jenis belanja secara real-time?',
    optionA: 'Menu Monitoring Kinerja Pelaksanaan Anggaran (IKPA) - Kinerja Penyerapan',
    optionB: 'Menu Kirim Pesan Singkat Kemenkeu',
    optionC: 'Menu Pengaduan Pegawai',
    optionD: 'Menu Arsip Surat Masuk',
    correctAnswer: 'A',
    explanation: 'MonSAKTI menyediakan dashboard interaktif IKPA yang merinci nilai dan progres penyerapan satker per jenis belanja (51, 52, 53, 57).',
    referenceRegulation: 'Panduan Operasional MonSAKTI DJPb'
  },

  // 36-45: Belanja Kontraktual & Pendaftaran Kontrak
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'MUDAH',
    questionText: 'Berapakah batas waktu maksimal penyampaian / pendaftaran Data Kontrak (Karwas Kontrak) ke KPPN terhitung sejak tanggal kontrak ditandatangani?',
    optionA: 'Paling lambat 5 (lima) hari kerja sejak kontrak ditandatangani',
    optionB: 'Paling lambat 30 hari kalender sejak kontrak ditandatangani',
    optionC: 'Paling lambat pada saat pengajuan SPM termin pertama',
    optionD: 'Bebas disampaikan kapan saja sebelum akhir tahun',
    correctAnswer: 'A',
    explanation: 'Berdasarkan PMK 190/PMK.05/2012 dan PER-5/PB/2022, data perjanjian/kontrak beserta ADK Kontrak (SAKTI) wajib disampaikan ke KPPN paling lambat 5 (lima) hari kerja setelah penandatanganan kontrak.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 38 ayat (1) & PER-5/PB/2022'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'SEDANG',
    questionText: 'Apa konsekuensi terhadap nilai IKPA jika satker mendaftarkan kontrak ke KPPN pada hari kerja ke-7 setelah penandatanganan kontrak?',
    optionA: 'Pendaftaran dinilai terlambat dan mengurangi nilai indikator Pengelolaan Data Kontrak pada IKPA',
    optionB: 'Kontrak dinyatakan batal demi hukum oleh pengadilan',
    optionC: 'KPPN menolak menerbitkan SP2D selamanya',
    optionD: 'Penyedia dikenakan denda pemutusan hubungan kerja',
    correctAnswer: 'A',
    explanation: 'Keterlambatan pendaftaran kontrak (lebih dari 5 hari kerja) akan tercatat pada kartu pengawasan SPAN dan memotong skor indikator Belanja Kontraktual satker.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran IV Indikator Data Kontrak'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'ANALISIS',
    questionText: 'Kontrak pekerjaan pengadaan komputer ditandatangani pada hari Rabu, 10 Maret (tidak ada hari libur nasional). Kapan batas akhir pendaftaran data kontrak tersebut ke KPPN agar tepat waktu?',
    optionA: 'Rabu, 17 Maret (5 hari kerja: Kamis 11, Jumat 12, Senin 15, Selasa 16, Rabu 17)',
    optionB: 'Senin, 15 Maret (5 hari kalender)',
    optionC: 'Jumat, 12 Maret (3 hari kerja)',
    optionD: 'Jumat, 19 Maret (7 hari kerja)',
    correctAnswer: 'A',
    explanation: 'Perhitungan hari kerja tidak menghitung hari Sabtu dan Minggu. Hari 1: Kamis 11 Mar, Hari 2: Jumat 12 Mar, Hari 3: Senin 15 Mar, Hari 4: Selasa 16 Mar, Hari 5: Rabu 17 Mar.',
    referenceRegulation: 'PMK 190/PMK.05/2012'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'SEDANG',
    questionText: 'Berapakah nilai ambang batas minimal suatu perikatan/kontrak yang WAJIB didaftarkan ke KPPN dengan penerbitan Nomor Register Dokumen Kontrak (NRK)?',
    optionA: 'Nilai perjanjian di atas Rp50.000.000 (lima puluh juta rupiah)',
    optionB: 'Nilai perjanjian di atas Rp10.000.000',
    optionC: 'Hanya kontrak di atas Rp1.000.000.000',
    optionD: 'Semua transaksi belanja berapapun nilainya termasuk kuitansi Rp100.000',
    correctAnswer: 'A',
    explanation: 'Sesuai regulasi perbendaharaan, perikatan berupa Surat Perintah Kerja (SPK) atau Surat Perjanjian dengan nilai di atas Rp50.000.000 wajib didaftarkan ke KPPN untuk diterbitkan Nomor Register Komitmen (CAN / NRK).',
    referenceRegulation: 'PMK 190/PMK.05/2012 jo PMK 210/PMK.05/2019'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'ANALISIS',
    questionText: 'Sebuah satker melakukan addendum perpanjangan waktu dan perubahan nilai kontrak. Apakah addendum kontrak tersebut wajib didaftarkan ulang ke KPPN?',
    optionA: 'Ya, perubahan data kontrak (addendum) wajib didaftarkan ke KPPN paling lambat 5 hari kerja sejak tanggal addendum',
    optionB: 'Tidak perlu, cukup disimpan di arsip satker saja',
    optionC: 'Hanya perlu jika nilai kontrak bertambah lebih dari 50%',
    optionD: 'Hanya perlu dilaporkan ke dinas pemadam kebakaran',
    correctAnswer: 'A',
    explanation: 'Setiap addendum kontrak (perubahan nilai, rekening, jangka waktu penyelesaian, atau termin penarikan) wajib didaftarkan ke KPPN paling lambat 5 hari kerja setelah addendum ditandatangani untuk memperbarui data komitmen pada SPAN.',
    referenceRegulation: 'PMK 190/PMK.05/2012'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'MUDAH',
    questionText: 'Modul apa pada aplikasi SAKTI yang digunakan oleh operator untuk merekam data supplier dan resume kontrak?',
    optionA: 'Modul Komitmen',
    optionB: 'Modul Pembayaran',
    optionC: 'Modul Bendahara',
    optionD: 'Modul Pelaporan (GLP)',
    correctAnswer: 'A',
    explanation: 'Perekaman data supplier (tipe 1, 2, 3, dst.) dan komitmen kontrak dilakukan pada Modul Komitmen SAKTI oleh Operator Komitmen dan disetujui oleh PPK.',
    referenceRegulation: 'User Manual SAKTI Modul Komitmen'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'SEDANG',
    questionText: 'Apa yang dimaksud dengan CAN (Commitment Application Number) atau Nomor Register Kontrak (NRK) yang diterbitkan oleh KPPN/SPAN?',
    optionA: 'Nomor identitas unik yang diterbitkan SPAN atas data kontrak yang telah tervalidasi dan mengunci pagu komitmen DIPA',
    optionB: 'Nomor rekening bank milik kontraktor',
    optionC: 'Nomor surat tugas staf PPK',
    optionD: 'Nomor telepon pengaduan KPPN',
    correctAnswer: 'A',
    explanation: 'NRK/CAN merupakan identitas komitmen resmi pada sistem SPAN yang mengunci alokasi pagu DIPA agar tidak terpakai oleh transaksi lain dan menjadi prasyarat penerbitan SPM-LS Kontraktual.',
    referenceRegulation: 'Petunjuk Teknis Pengelolaan Komitmen Kemenkeu'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'MUDAH',
    questionText: 'Apakah SPM-LS Kontraktual dapat disetujui dan dicairkan oleh KPPN jika data kontraknya belum didaftarkan atau ditolak pendaftarannya oleh SPAN?',
    optionA: 'Tidak bisa, sistem SPAN akan secara otomatis menolak SPM yang nomor register kontraknya tidak valid',
    optionB: 'Bisa, jika satker membawa surat jaminan dari bendahara',
    optionC: 'Bisa, jika nilai tagihannya di bawah Rp100 juta',
    optionD: 'Bisa, jika disetujui lisan oleh petugas FO KPPN',
    correctAnswer: 'A',
    explanation: 'SPAN menerapkan validasi ketat (three-way matching). SPM-LS Kontraktual wajib merujuk pada NRK yang valid dan aktif di SPAN dengan pagu komitmen yang mencukupi.',
    referenceRegulation: 'SOP Penerbitan SP2D KPPN'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'ANALISIS',
    questionText: 'PPK menandatangani kontrak pengadaan alat laboratorium senilai Rp300.000.000 pada tanggal 1 Agustus. Namun, staf baru merekam di SAKTI tanggal 15 Agustus dan dikirim ke KPPN. Apa langkah koreksi yang TIDAK boleh dilakukan?',
    optionA: 'Mengubah tanggal tanda tangan kontrak secara sepihak (backdating) untuk memanipulasi agar seolah-olah tidak terlambat 5 hari kerja',
    optionB: 'Mengevaluasi kelemahan alur kerja internal satker agar ke depan tidak terulang',
    optionC: 'Mendaftarkan kontrak apa adanya dan menerima konsekuensi pemotongan nilai kepatuhan kontrak',
    optionD: 'Memberikan pembinaan kepada operator komitmen satker',
    correctAnswer: 'A',
    explanation: 'Backdating dokumen kontrak adalah tindakan manipulasi administrasi dan pelanggaran etika hukum. Keterlambatan harus dicatat jujur dan dijadikan bahan perbaikan kepatuhan satker.',
    referenceRegulation: 'Pedoman Integritas & Kepatuhan Internal Kemenkeu'
  },
  {
    topic: 'IKPA - Belanja Kontraktual',
    difficulty: 'SEDANG',
    questionText: 'Dalam komponen penilaian IKPA terbaru, akselerasi pendaftaran kontrak dini (kontrak yang ditandatangani di awal tahun) bertujuan untuk...',
    optionA: 'Mendorong percepatan penyerapan anggaran belanja modal dan output riil pemerintah sejak Triwulan I',
    optionB: 'Menghabiskan kas negara sebelum audit BPK',
    optionC: 'Mempermudah penyedia meminjam uang di rentenir',
    optionD: 'Menghindari pemeriksaan pajak oleh Ditjen Pajak',
    correctAnswer: 'A',
    explanation: 'Akselerasi belanja kontraktual di awal tahun memberikan stimulus ekonomi lebih cepat bagi sektor riil dan mencegah pengerjaan proyek konstruksi terburu-buru di akhir tahun.',
    referenceRegulation: 'PER-5/PB/2022'
  },

  // 46-53: Penyelesaian Tagihan (17 Hari Kerja)
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'MUDAH',
    questionText: 'Berapakah batas waktu maksimal penyelesaian tagihan belanja APBN (SPM-LS Non-Belanja Pegawai) terhitung sejak timbulnya hak tagih (BAST / BAP ditandatangani) sampai dengan SPM diterbitkan?',
    optionA: 'Paling lambat 17 (tujuh belas) hari kerja',
    optionB: 'Paling lambat 30 hari kalender',
    optionC: 'Paling lambat 60 hari kerja',
    optionD: 'Paling lambat 7 hari kerja',
    correctAnswer: 'A',
    explanation: 'Sesuai PMK 190/PMK.05/2012 dan PER-5/PB/2022, norma waktu penyelesaian tagihan non-belanja pegawai adalah maksimal 17 hari kerja sejak BAST/hak tagih timbul sampai SPM diajukan ke KPPN.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 40 & PER-5/PB/2022'
  },
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'SEDANG',
    questionText: 'Bagaimana pembagian norma waktu penyelesaian tagihan 17 hari kerja antara pihak rekanan, PPK, dan PPSPM?',
    optionA: 'Penyedia menyampaikan tagihan maks 5 hari kerja, PPK menguji dan menerbitkan SPP maks 5 hari kerja, PPSPM menguji dan menerbitkan SPM maks 5 hari kerja (dengan toleransi total 17 HK)',
    optionB: 'Penyedia 10 hari kerja, PPK 5 hari kerja, PPSPM 2 hari kalender',
    optionC: 'PPK 15 hari kerja, PPSPM 2 jam',
    optionD: 'Tidak ada pembagian tahapan waktu',
    correctAnswer: 'A',
    explanation: 'Tahapan norma waktu: Penyedia ke PPK (maks 5 HK), PPK menerbitkan SPP (maks 5 HK), penerbitan SPM oleh PPSPM (maks 5 HK), serta proses penyampaian ke KPPN (total koridor maksimal 17 hari kerja).',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 40-42'
  },
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'ANALISIS',
    questionText: 'BAST pekerjaan pengadaan ATK ditandatangani tanggal 1 Juli. Surat Perintah Membayar (SPM) baru diterbitkan oleh PPSPM dan dikirim ke KPPN pada hari kerja ke-22 setelah BAST. Apa dampaknya terhadap IKPA Satker?',
    optionA: 'Tagihan dinilai terlambat (melebihi batas 17 hari kerja) dan mengurangi skor indikator Penyelesaian Tagihan',
    optionB: 'Tagihan tidak dapat dibayar oleh KPPN',
    optionC: 'Nilai IKPA satker otomatis bertambah 10 poin',
    optionD: 'PPK harus diganti oleh Menteri Keuangan',
    correctAnswer: 'A',
    explanation: 'Penerbitan SPM yang melampaui 17 hari kerja sejak BAST menurunkan rasio ketepatan waktu penyelesaian tagihan pada indikator IKPA satker.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran V Indikator Penyelesaian Tagihan'
  },
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'MUDAH',
    questionText: 'Tujuan utama diterapkannya indikator ketepatan waktu Penyelesaian Tagihan 17 hari kerja adalah...',
    optionA: 'Menjamin kepastian pembayaran kepada rekanan/penyedia pihak ketiga dan mencegah pengendapan berkas tagihan',
    optionB: 'Menambah beban kerja administrasi satker',
    optionC: 'Mempercepat kebangkrutan penyedia',
    optionD: 'Mengurangi anggaran kas negara di bank',
    correctAnswer: 'A',
    explanation: 'Norma 17 hari kerja melindungi hak penyedia barang/jasa agar segera menerima pembayaran atas pekerjaan yang telah diselesaikan dengan baik, sekaligus menjaga reputasi pemerintah.',
    referenceRegulation: 'Inpres Percepatan Pelaksanaan APBN'
  },
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'SEDANG',
    questionText: 'Data apa yang digunakan oleh SPAN dan MonSAKTI untuk mendeteksi ketepatan waktu penyelesaian tagihan 17 hari kerja?',
    optionA: 'Perbandingan antara tanggal BAST/dokumen penerimaan barang dengan tanggal persetujuan SPM oleh PPSPM pada Modul Pembayaran SAKTI',
    optionB: 'Tanggal kuitansi fotokopi',
    optionC: 'Tanggal sertifikat garansi barang',
    optionD: 'Tanggal slip setoran pajak',
    correctAnswer: 'A',
    explanation: 'Sistem SAKTI mencatat tanggal dokumen sumber (BAST) dan mencocokkannya dengan tanggal persetujuan SPM oleh PPSPM (generate OTP SPM).',
    referenceRegulation: 'Juknis Monitoring Kepatuhan Pembayaran SAKTI'
  },
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'ANALISIS',
    questionText: 'Penyedia telah menyelesaikan pekerjaan renovasi dan menandatangani BAST pada 10 November. Namun rekanan terlambat melampirkan kuitansi bermeterai dan faktur pajak sehingga berkas baru lengkap 20 hari kemudian. Apa mitigasi yang seharusnya dilakukan PPK?',
    optionA: 'Menolak menandatangani BAST sebelum seluruh berkas pendukung pembayaran dan faktur pajak diserahkan lengkap oleh penyedia',
    optionB: 'Menandatangani BAST kosong tanpa tanggal',
    optionC: 'Menerbitkan SPP fiktif tanpa dokumen',
    optionD: 'Membayar menggunakan dana pribadi staf',
    correctAnswer: 'A',
    explanation: 'BAST sebaiknya ditandatangani saat seluruh hasil pekerjaan telah terverifikasi dan dokumen pendukung tagihan siap diproses, agar perhitungan 17 hari kerja tidak terlewati akibat kelalaian penyedia.',
    referenceRegulation: 'Mitigasi Risiko Penyelesaian Tagihan Kemenkeu'
  },
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'SEDANG',
    questionText: 'Apakah pengajuan tagihan melalui mekanisme Uang Persediaan (UP) dihitung dalam indikator Penyelesaian Tagihan 17 hari kerja?',
    optionA: 'Tidak, indikator ini khusus mengukur SPM-LS Kontraktual dan Non-Kontraktual pihak ketiga yang diterbitkan ke KPPN',
    optionB: 'Ya, seluruh kuitansi UP wajib diajukan ke KPPN dalam 17 hari kerja',
    optionC: 'Hanya belanja perjalanan dinas UP',
    optionD: 'Hanya belanja makan rapat di bawah Rp1 juta',
    correctAnswer: 'A',
    explanation: 'Indikator Penyelesaian Tagihan difokuskan pada penerbitan SPM-LS pihak ketiga non-belanja pegawai untuk memastikan tagihan rekanan langsung dituntaskan oleh Kuasa BUN.',
    referenceRegulation: 'PER-5/PB/2022'
  },
  {
    topic: 'IKPA - Penyelesaian Tagihan',
    difficulty: 'MUDAH',
    questionText: 'Berapakah jangka waktu yang dimiliki KPPN untuk menerbitkan SP2D setelah SPM dinyatakan lengkap dan benar?',
    optionA: 'Paling lambat 1 (satu) jam kerja pada kondisi normal setelah SPM disetujui sistem',
    optionB: 'Paling lambat 14 hari kerja',
    optionC: 'Paling lambat 30 hari kalender',
    optionD: 'Paling lambat 3 bulan',
    correctAnswer: 'A',
    explanation: 'Sesuai Standar Pelayanan KPPN, penerbitan SP2D atas SPM yang telah tervalidasi lengkap dan sah secara elektronik diselesaikan paling lambat 1 jam pada loket pelayanan terpadu.',
    referenceRegulation: 'Keputusan Dirjen Perbendaharaan tentang Standar Pelayanan DJPb'
  },

  // 54-60: Pengelolaan UP & TUP, Dispensasi SPM, Capaian Output
  {
    topic: 'IKPA - Pengelolaan UP dan TUP',
    difficulty: 'MUDAH',
    questionText: 'Berapakah persentase minimal revolving (penggantian) dana Uang Persediaan (UP) dalam 1 (satu) bulan agar satker tidak terkena pemotongan nilai IKPA?',
    optionA: 'Minimal 50% dari besaran pagu UP dalam 1 bulan',
    optionB: 'Minimal 10% dalam 1 bulan',
    optionC: 'Minimal 100% setiap minggu',
    optionD: 'Bebas tidak perlu di-revolving',
    correctAnswer: 'A',
    explanation: 'Indikator Pengelolaan UP dan TUP menilai kepatuhan perputaran kas (revolving) minimal 50% dari besaran pagu UP dalam kurun waktu 1 bulan melalui pengajuan SPM-GUP.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran VI Pengelolaan UP & TUP'
  },
  {
    topic: 'IKPA - Pengelolaan UP dan TUP',
    difficulty: 'SEDANG',
    questionText: 'Berapakah batas waktu maksimal pertanggungjawaban Tambahan Uang Persediaan (TUP) melalui SPM Pertanggungjawaban TUP (PTUP)?',
    optionA: 'Paling lambat 1 (satu) bulan terhitung sejak tanggal SP2D TUP diterbitkan',
    optionB: 'Paling lambat 3 bulan sejak SP2D terbit',
    optionC: 'Paling lambat akhir tahun anggaran berjalan',
    optionD: 'Paling lambat 5 hari kerja',
    correctAnswer: 'A',
    explanation: 'Dana TUP harus digunakan dan dipertanggungjawabkan (PTUP) paling lambat 1 (satu) bulan sejak SP2D TUP terbit, dan sisa dana yang tidak terpakai wajib disetorkan kembali ke Kas Negara.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 47 & PER-5/PB/2022'
  },
  {
    topic: 'IKPA - Pengelolaan UP dan TUP',
    difficulty: 'ANALISIS',
    questionText: 'Satker C menerima SP2D TUP sebesar Rp150.000.000 pada tanggal 10 April. Sampai dengan 15 Mei, satker belum mengajukan SPM PTUP maupun menyetor sisa dana. Apa sanksi yang dapat dijatuhkan oleh Kepala KPPN?',
    optionA: 'Penerbitan surat peringatan dan pemotongan alokasi UP berikutnya sebesar 25%, serta penolakan pengajuan SPM non-gaji',
    optionB: 'Pencabutan status satker menjadi yayasan swasta',
    optionC: 'Penyitaan gedung satker oleh juru sita pajak',
    optionD: 'Pemecatan seluruh pegawai satker',
    correctAnswer: 'A',
    explanation: 'Sesuai PMK 190/2012, jika TUP tidak dipertanggungjawabkan dalam 1 bulan, KPPN menerbitkan surat teguran dan dapat mengenakan sanksi penundaan penerbitan SPM atau pemotongan uang persediaan.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 48'
  },
  {
    topic: 'IKPA - Dispensasi SPM',
    difficulty: 'MUDAH',
    questionText: 'Apa yang dimaksud dengan indikator Dispensasi SPM dalam kerangka IKPA?',
    optionA: 'Penilaian terhadap kepatuhan satker mengajukan SPM sesuai jadwal waktu normal tanpa memerlukan surat izin dispensasi keterlambatan',
    optionB: 'Pemberian diskon harga barang oleh toko rekanan',
    optionC: 'Izin bagi satker untuk tidak membayar pajak',
    optionD: 'Pembebasan satker dari audit BPK',
    correctAnswer: 'A',
    explanation: 'Dispensasi SPM diberikan nilai 100 jika satker tidak pernah mengajukan SPM yang melewati batas waktu kedaluwarsa atau batas cut-off akhir tahun yang memerlukan surat dispensasi Kepala KPPN/Kanwil.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran VII'
  },
  {
    topic: 'IKPA - Dispensasi SPM',
    difficulty: 'SEDANG',
    questionText: 'Pengajuan dispensasi penerbitan SPM melewati batas waktu akhir tahun anggaran (LLAT) diajukan oleh KPA kepada...',
    optionA: 'Kepala Kantor Wilayah Ditjen Perbendaharaan (Kanwil DJPb) / Kepala KPPN sesuai ketentuan LLAT',
    optionB: 'DPRD Kabupaten setempat',
    optionC: 'Kantor Cabang Bank BRI',
    optionD: 'Pengadilan Negeri setempat',
    correctAnswer: 'A',
    explanation: 'Kewenangan pemberian dispensasi SPM diatur dalam Perdirjen LLAT dan umumnya menjadi kewenangan Kepala Kanwil DJPb dengan rekomendasi dari Kepala KPPN mitra kerja.',
    referenceRegulation: 'Perdirjen LLAT Akhir Tahun Ditjen Perbendaharaan'
  },
  {
    topic: 'IKPA - Capaian Output',
    difficulty: 'MUDAH',
    questionText: 'Kapan batas waktu pengisian data Progres Capaian Output bulanan pada aplikasi SAKTI / MonSAKTI?',
    optionA: 'Paling lambat 5 (atau 10) hari kerja pertama pada bulan berikutnya',
    optionB: 'Paling lambat akhir tahun anggaran',
    optionC: 'Hanya diisi jika proyek telah selesai 100%',
    optionD: 'Tidak wajib diisi oleh satker',
    correctAnswer: 'A',
    explanation: 'Pelaporan capaian output diisi setiap bulan oleh satker paling lambat pada hari kerja ke-5 (atau ke-10) bulan berikutnya melalui SAKTI Modul Komitmen/Pembayaran dan dipantau di MonSAKTI.',
    referenceRegulation: 'PER-5/PB/2022 Lampiran VIII Indikator Capaian Output'
  },
  {
    topic: 'IKPA - Capaian Output',
    difficulty: 'ANALISIS',
    questionText: 'Sebuah satker melaporkan penyerapan anggaran belanja modal mencapai 90%, namun progres fisik/output yang dilaporkan di SAKTI masih 15% tanpa penjelasan anomali. Bagaimana penilaian indikator Capaian Outputnya?',
    optionA: 'Terjadi anomali kesenjangan (gap) antara realisasi anggaran dengan output riil yang menurunkan skor kualitas capaian output',
    optionB: 'Satker memperoleh penghargaan karena sangat hemat biaya',
    optionC: 'Output otomatis dinaikkan oleh AI Kemenkeu menjadi 90%',
    optionD: 'Tidak mempengaruhi nilai IKPA satker',
    correctAnswer: 'A',
    explanation: 'Indikator Capaian Output mengukur kewajaran (gap) antara penyerapan anggaran dengan capaian volume riil dan progres rincian output (RO). Kesenjangan ekstrem yang tidak logis akan menurunkan nilai efisiensi dan ketepatan pelaporan.',
    referenceRegulation: 'Juknis Pengukuran Capaian Output DJPb'
  }
];
