import { RawQuestion } from './questionsIkpa';

export const pembayaranQuestions: RawQuestion[] = [
  // 1-15: SPP, SPM, SP2D Mekanisme Dasar
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'MUDAH',
    questionText: 'Siapakah pejabat perbendaharaan yang berwenang menerbitkan Surat Perintah Membayar (SPM) untuk diajukan ke KPPN?',
    optionA: 'Pejabat Penandatangan Surat Perintah Membayar (PPSPM)',
    optionB: 'Pejabat Pembuat Komitmen (PPK)',
    optionC: 'Bendahara Pengeluaran',
    optionD: 'Kuasa Pengguna Anggaran (KPA) langsung',
    correctAnswer: 'A',
    explanation: 'Berdasarkan PMK 190/PMK.05/2012, Pejabat Penandatangan Surat Perintah Membayar (PPSPM) adalah pejabat yang diberi kewenangan oleh KPA untuk melakukan pengujian atas SPP beserta dokumen pendukung dan menerbitkan SPM.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 1 angka 10 dan Pasal 14'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'MUDAH',
    questionText: 'Surat perintah yang diterbitkan oleh KPPN selaku Kuasa Bendahara Umum Negara (BUN) untuk mencairkan dana atas beban Rekening Kas Umum Negara disebut...',
    optionA: 'Surat Perintah Pencairan Dana (SP2D)',
    optionB: 'Surat Perintah Membayar (SPM)',
    optionC: 'Surat Permintaan Pembayaran (SPP)',
    optionD: 'Surat Setoran Bukan Pajak (SSBP)',
    correctAnswer: 'A',
    explanation: 'Surat Perintah Pencairan Dana (SP2D) adalah dokumen yang diterbitkan oleh KPPN selaku Kuasa BUN untuk melaksanakan pengeluaran atas beban APBN berdasarkan SPM yang diajukan oleh Satker.',
    referenceRegulation: 'UU No. 1/2004 tentang Perbendaharaan Negara Pasal 1 & PMK 190/2012'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'SEDANG',
    questionText: 'Apakah Pejabat Pembuat Komitmen (PPK) diperbolehkan merangkap jabatan sebagai Pejabat Penandatangan SPM (PPSPM)?',
    optionA: 'Tidak boleh, untuk menjamin prinsip pemisahan fungsi (check and balances) antara ordonator dan komitmen',
    optionB: 'Boleh, asalkan disetujui secara lisan oleh kepala kantor',
    optionC: 'Boleh, jika satker memiliki pagu di bawah Rp1 miliar',
    optionD: 'Boleh, pada satker perwakilan luar negeri saja',
    correctAnswer: 'A',
    explanation: 'Pasal 15 PMK 190/PMK.05/2012 secara tegas melarang perangkapan jabatan antara PPK dan PPSPM demi menjaga prinsip pengendalian intern dan objektivitas pengujian tagihan.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 15 ayat (2)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'ANALISIS',
    questionText: 'PPK menerbitkan Surat Permintaan Pembayaran (SPP) pengadaan mebeler senilai Rp80.000.000 pada tanggal 5 Mei. Saat PPSPM menguji SPP, ditemukan bahwa dokumen sertifikat garansi dan bukti pembayaran pajak belum terlampir. Tindakan apa yang WAJIB diambil oleh PPSPM?',
    optionA: 'Menolak menerbitkan SPM dan mengembalikan SPP beserta berkas pendukung kepada PPK untuk dilengkapi paling lambat 2 hari kerja',
    optionB: 'Tetap menerbitkan SPM dengan janji berkas menyusul minggu depan',
    optionC: 'Mengubah nominal SPP secara mandiri menjadi Rp40.000.000',
    optionD: 'Menghubungi rekanan secara langsung untuk meminta uang jaminan',
    correctAnswer: 'A',
    explanation: 'PPSPM bertugas melakukan pengujian kelengkapan dokumen pendukung SPP. Jika terdapat kekurangan berkas, PPSPM wajib mengembalikan SPP kepada PPK disertai surat penolakan / alasan pengembalian.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 54'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'SEDANG',
    questionText: 'Berapakah jangka waktu yang dimiliki oleh PPSPM untuk menguji SPP dan menerbitkan SPM sejak SPP diterima lengkap dan benar?',
    optionA: 'Paling lambat 5 (lima) hari kerja',
    optionB: 'Paling lambat 14 hari kalender',
    optionC: 'Paling lambat 30 hari kerja',
    optionD: 'Paling lambat 1 bulan',
    correctAnswer: 'A',
    explanation: 'Sesuai Pasal 54 ayat (2) PMK 190/PMK.05/2012, pengujian SPP dan penerbitan SPM oleh PPSPM diselesaikan paling lambat 5 (lima) hari kerja setelah SPP diterima secara lengkap dan sah.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 54 ayat (2)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'MUDAH',
    questionText: 'Metode pembayaran belanja APBN yang langsung ditransfer dari Kas Negara ke rekening pihak ketiga/penyedia barang disebut...',
    optionA: 'Pembayaran Langsung (LS)',
    optionB: 'Uang Persediaan (UP)',
    optionC: 'Tambahan Uang Persediaan (TUP)',
    optionD: 'Pinjaman Komersial Bank',
    correctAnswer: 'A',
    explanation: 'Pembayaran Langsung (LS) adalah mekanisme pembayaran yang dilakukan langsung kepada bendahara pengeluaran/penerima hak/pihak ketiga atas dasar perjanjian/surat keputusan.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 1 angka 16'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'SEDANG',
    questionText: 'Kapan pembayaran atas beban APBN wajib menggunakan mekanisme Pembayaran Langsung (LS) Pihak Ketiga?',
    optionA: 'Untuk pembayaran pengadaan barang/jasa bernilai di atas Rp50.000.000 (lima puluh juta rupiah)',
    optionB: 'Hanya untuk pengadaan bernilai di atas Rp10 miliar',
    optionC: 'Untuk semua belanja tanpa batas minimal nominal',
    optionD: 'Hanya jika rekanan meminta secara tertulis',
    correctAnswer: 'A',
    explanation: 'Pembayaran kepada penyedia barang/jasa dengan nilai di atas Rp50.000.000 wajib dilakukan melalui mekanisme LS langsung ke rekening penyedia.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 37 ayat (1)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'ANALISIS',
    questionText: 'Satker ingin membayarkan uang lembur pegawai dan uang makan PNS bulan sebelumnya sebesar Rp35.000.000. Mekanisme pembayaran apa yang paling tepat digunakan?',
    optionA: 'SPM-LS Bendahara Pengeluaran untuk diteruskan kepada masing-masing rekening pegawai',
    optionB: 'SPM-UP Tunai brankas',
    optionC: 'SPM-LS Pihak Ketiga ke rekening toko rekanan',
    optionD: 'SPM TUP Valuta Asing',
    correctAnswer: 'A',
    explanation: 'Pembayaran belanja pegawai non-gaji induk (seperti uang lembur, uang makan, dan honorarium tim) diajukan melalui SPM-LS kepada Bendahara Pengeluaran untuk ditransfer ke rekening masing-masing penerima.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 39'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'MUDAH',
    questionText: 'Tanda tangan yang digunakan oleh PPSPM untuk mengesahkan dan menerbitkan SPM pada aplikasi SAKTI ke sistem SPAN KPPN adalah...',
    optionA: 'Tanda Tangan Elektronik (TTE) / One-Time Password (OTP) tersertifikasi BSrE / Kemenkeu',
    optionB: 'Cap stempel basah tinta ungu',
    optionC: 'Tanda tangan manual lalu difotokopi berwarna',
    optionD: 'Tanda tangan surat kabar',
    correctAnswer: 'A',
    explanation: 'Penerbitan SPM pada era digital perbendaharaan sepenuhnya paperless menggunakan Digital Signature / OTP tersertifikasi oleh Balai Sertifikasi Elektronik (BSrE) / BSSN.',
    referenceRegulation: 'PMK 210/PMK.05/2019 tentang Tata Cara Pembayaran dalam rangka Pelaksanaan APBN'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'SEDANG',
    questionText: 'Dalam pengujian SPM oleh Front Office (FO) Penerimaan SPM KPPN, aspek apa saja yang diuji sebelum diterbitkan SP2D?',
    optionA: 'Kebenaran formal dokumen, kelengkapan ADK, keabsahan TTE/OTP, dan ketersediaan pagu komitmen DIPA',
    optionB: 'Warna cat mobil rekanan penyedia',
    optionC: 'Kesesuaian suku bunga bank swasta',
    optionD: 'Kondisi kesehatan fisik bendahara satker',
    correctAnswer: 'A',
    explanation: 'KPPN bertindak menguji kebenaran formal SPM: keterpenuhan syarat dokumen, validitas tanda tangan elektronik PPSPM, kecocokan supplier terdaftar, dan sisa pagu anggaran.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 57'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'ANALISIS',
    questionText: 'SPM-LS Kontraktual bernilai Rp120.000.000 diajukan oleh satker ke KPPN. Namun pada sistem SPAN muncul status penolakan: "Pagu Minus pada Akun 532111". Mengapa penolakan ini terjadi?',
    optionA: 'Realisasi kumulatif sebelumnya ditambah nilai SPM melebihi alokasi pagu DIPA aktif pada akun tersebut',
    optionB: 'Nomor telepon rekanan tidak aktif',
    optionC: 'Tanggal SPM mendahului tanggal surat tugas',
    optionD: 'KPPN kehabisan uang kertas di brankas',
    correctAnswer: 'A',
    explanation: 'Sistem SPAN memiliki kontrol pagu otomatis (fund check). Pengeluaran kas tidak dapat diproses jika pagu DIPA pada akun/kegiatan bersangkutan tidak mencukupi (pagu minus).',
    referenceRegulation: 'UU No. 1/2004 Pasal 21 & Juknis SPAN Kemenkeu'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'SEDANG',
    questionText: 'Berapa harikah masa berlaku (kedaluwarsa) suatu Surat Perintah Membayar (SPM) sejak tanggal diterbitkan oleh PPSPM sampai diajukan ke KPPN?',
    optionA: 'Maksimal 30 (tiga puluh) hari kalender',
    optionB: 'Maksimal 7 hari kerja',
    optionC: 'Maksimal 90 hari kalender',
    optionD: 'Tidak pernah kedaluwarsa',
    correctAnswer: 'A',
    explanation: 'Berdasarkan PMK 190/PMK.05/2012, SPM berlaku selama 30 hari kalender sejak tanggal diterbitkan. Jika melampaui 30 hari dan belum diproses SP2D, SPM tersebut kedaluwarsa dan harus dibatalkan/diterbitkan kembali.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 55 ayat (2)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'MUDAH',
    questionText: 'KPPN merupakan unit kerja instansi vertikal yang berada di bawah naungan...',
    optionA: 'Direktorat Jenderal Perbendaharaan (DJPb), Kementerian Keuangan RI',
    optionB: 'Direktorat Jenderal Pajak (DJP)',
    optionC: 'Badan Pemeriksa Keuangan (BPK)',
    optionD: 'Kementerian Dalam Negeri (Kemendagri)',
    correctAnswer: 'A',
    explanation: 'KPPN (Kantor Pelayanan Perbendaharaan Negara) adalah instansi vertikal Ditjen Perbendaharaan Kemenkeu yang bertindak sebagai Kuasa Bendahara Umum Negara di daerah.',
    referenceRegulation: 'PMK tentang Organisasi dan Tata Kerja Kementerian Keuangan'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'ANALISIS',
    questionText: 'Jika terjadi gangguan jaringan internet nasional sehingga pengiriman SPM elektronik (ADK) terhambat, mitigasi Business Continuity Plan (BCP) apa yang resmi berlaku?',
    optionA: 'Penyampaian ADK SPM secara luring (offline) menggunakan media penyimpanan data resmi disertai Surat Keterangan Gangguan Jaringan dari KPA',
    optionB: 'Membayar rekanan dengan uang kas pribadi kepala KPPN',
    optionC: 'Menutup layanan kantor selama 1 bulan',
    optionD: 'Membatalkan seluruh kegiatan APBN tahun tersebut',
    correctAnswer: 'A',
    explanation: 'SOP Penanganan Keadaan Darurat / BCP Ditjen Perbendaharaan mengizinkan pengantaran fisik ADK SPM melalui media penyimpanan data terenkripsi disertai surat keterangan KPA.',
    referenceRegulation: 'Juknis Keadaan Darurat (BCP) SAKTI-SPAN DJPb'
  },
  {
    topic: 'Mekanisme Pembayaran APBN',
    difficulty: 'SEDANG',
    questionText: 'Dokumen pendukung apa sajakah yang WAJIB diunggah (upload) pada aplikasi SAKTI saat mengajukan SPM-LS Pembayaran Sewa Gedung Kantor?',
    optionA: 'Surat Perjanjian Sewa, Kuitansi/Bukti Pembayaran, BAST Penerimaan Hak Sewa, Faktur Pajak/e-Billing, dan SPTJM KPA/PPK',
    optionB: 'Hanya fotokopi KTP penjaga malam gedung',
    optionC: 'Brosur promosi gedung perumahan',
    optionD: 'Denah tata ruang kota provinsi',
    correctAnswer: 'A',
    explanation: 'Pengajuan SPM sewa wajib didukung kontrak/perjanjian sewa, BAST pemanfaatan gedung, kuitansi sah, perhitungan pajak (PPh 4 ayat 2 final 10%), serta SPTJM keabsahan komitmen.',
    referenceRegulation: 'PMK 190/PMK.05/2012 & Perdirjen PBJ Kemenkeu'
  },

  // 16-30: Uang Persediaan (UP), GUP, PTUP, Nihil
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'MUDAH',
    questionText: 'Uang muka kerja dalam jumlah tertentu yang diberikan kepada Bendahara Pengeluaran untuk membiayai kegiatan operasional sehari-hari satker disebut...',
    optionA: 'Uang Persediaan (UP)',
    optionB: 'Gaji Pokok',
    optionC: 'Bantuan Operasional Sekolah',
    optionD: 'Dana Alokasi Khusus',
    correctAnswer: 'A',
    explanation: 'Uang Persediaan (UP) adalah uang muka kerja dalam jumlah tertentu yang diberikan kepada Bendahara Pengeluaran untuk membiayai kegiatan operasional sehari-hari perkantoran yang tidak dapat dilakukan dengan LS.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 1 angka 17'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'SEDANG',
    questionText: 'Berapakah batasan besaran uang persediaan (UP) untuk pagu belanja yang dapat dibayarkan dengan UP sampai dengan Rp2,4 Miliar?',
    optionA: 'Maksimal Rp100.000.000 (seratus juta rupiah)',
    optionB: 'Maksimal Rp200.000.000',
    optionC: 'Maksimal Rp50.000.000',
    optionD: 'Maksimal Rp500.000.000',
    correctAnswer: 'A',
    explanation: 'Ketentuan besaran UP: pagu s.d. Rp2,4 Miliar diberikan UP paling banyak Rp100 juta; pagu di atas Rp2,4 M s.d. Rp6 M maksimal Rp200 juta; pagu di atas Rp6 M diberikan maksimal Rp500 juta.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 43 ayat (1)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'ANALISIS',
    questionText: 'Satker Balai Riset memiliki pagu belanja barang operasional Rp1,8 Miliar. KPA bermaksud mengajukan UP sebesar Rp250.000.000 karena karakteristik geografis kepulauan terpencil. Kepada siapakah KPA harus mengajukan permohonan dispensasi persetujuan UP melebihi batas reguler?',
    optionA: 'Kepala Kantor Pelayanan Perbendaharaan Negara (KPPN) mitra kerja',
    optionB: 'Menteri Koordinator Bidang Perekonomian',
    optionC: 'Direktur Utama Bank Mandiri',
    optionD: 'Gubernur Provinsi setempat',
    correctAnswer: 'A',
    explanation: 'Kepala KPPN atas nama Menteri Keuangan berwenang memberikan persetujuan dispensasi kenaikan besaran Uang Persediaan melampaui batas standar berdasarkan kajian kebutuhan riil satker.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 44 ayat (2)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'MUDAH',
    questionText: 'Berapakah batas maksimal pembayaran belanja secara tunai kepada 1 (satu) rekanan/penerima atas beban Uang Persediaan (UP)?',
    optionA: 'Paling banyak Rp50.000.000 (lima puluh juta rupiah)',
    optionB: 'Paling banyak Rp10.000.000',
    optionC: 'Paling banyak Rp100.000.000',
    optionD: 'Tidak terbatas nilainya',
    correctAnswer: 'A',
    explanation: 'Pembayaran kepada satu rekanan melalui mekanisme Uang Persediaan dibatasi maksimal Rp50.000.000. Pembayaran di atas Rp50 juta wajib menggunakan mekanisme Pembayaran Langsung (LS).',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 43 ayat (3)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'SEDANG',
    questionText: 'Apa perbedaan mendasar antara SPM-GUP Isi Kembali (Revolving) dengan SPM-GUP Nihil?',
    optionA: 'GUP Isi Kembali menambah saldo kas bendahara kembali ke plafon awal UP, sedangkan GUP Nihil hanya mengesahkan belanja tanpa menambah saldo kas (biasanya di akhir tahun)',
    optionB: 'GUP Isi Kembali dibayar oleh rekanan swasta',
    optionC: 'GUP Nihil adalah SPM yang ditolak KPPN',
    optionD: 'Keduanya sama persis tidak ada bedanya',
    correctAnswer: 'A',
    explanation: 'GUP Isi Kembali berfungsi mengisi kembali kas bendahara yang telah terpakai. GUP Nihil digunakan untuk mengesahkan belanja sisa akhir tahun atau saat penutupan UP tanpa menerbitkan aliran kas baru.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 45-46'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'ANALISIS',
    questionText: 'Kapan satker diwajibkan mengajukan SPM-GUP Nihil?',
    optionA: 'Pada akhir tahun anggaran (Langkah-Langkah Akhir Tahun) untuk mempertanggungjawabkan sisa belanja UP sebelum menyetorkan sisa uang kas ke kas negara',
    optionB: 'Setiap tanggal 1 awal bulan',
    optionC: 'Saat bendahara pengeluaran cuti melahirkan',
    optionD: 'Saat satker menerima DIPA baru',
    correctAnswer: 'A',
    explanation: 'Pada penutupan tahun anggaran, seluruh belanja yang dibiayai dari UP wajib disahkan melalui SPM-GUP Nihil, dan sisa fisik kas UP yang belum terpakai wajib disetor kembali ke Rekening Kas Umum Negara.',
    referenceRegulation: 'Perdirjen Perbendaharaan tentang Pedoman LLAT'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'SEDANG',
    questionText: 'Apa yang dimaksud dengan SPM Tambahan Uang Persediaan (TUP)?',
    optionA: 'Uang muka yang diberikan kepada bendahara ketika kebutuhan kas mendesak dalam 1 bulan melebihi pagu UP yang tersedia',
    optionB: 'Bonus kinerja bagi staf keuangan',
    optionC: 'Pembayaran ganti rugi bencana alam',
    optionD: 'Pengembalian pajak lebih bayar',
    correctAnswer: 'A',
    explanation: 'TUP adalah uang muka yang diberikan kepada Bendahara Pengeluaran untuk kebutuhan yang sangat mendesak dalam waktu 1 (satu) bulan melebihi pagu Uang Persediaan yang ditetapkan.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 47 ayat (1)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'ANALISIS',
    questionText: 'Satker ingin mengajukan TUP sebesar Rp300.000.000 untuk kegiatan kunjungan kerja kenegaraan. Syarat utama apa yang wajib dilampirkan dalam surat permohonan persetujuan TUP ke Kepala KPPN?',
    optionA: 'Rincian Rencana Penggunaan TUP (RPTUP), surat pernyataan KPA bahwa dana mendesak dan habis dalam 1 bulan, serta sisa UP saat ini tidak mencukupi',
    optionB: 'Foto bersama seluruh pejabat satker',
    optionC: 'Bukti pembayaran sewa kapal pesiar',
    optionD: 'Surat rekomendasi lurah setempat',
    correctAnswer: 'A',
    explanation: 'Permohonan TUP wajib melampirkan Rincian Rencana Penggunaan TUP, surat pernyataan KPA bahwa TUP digunakan untuk kebutuhan mendesak dan akan dipertanggungjawabkan dalam 1 bulan, serta data sisa kas UP.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 47 ayat (2)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'MUDAH',
    questionText: 'Berapakah jangka waktu maksimal dana TUP harus dipertanggungjawabkan (PTUP) sejak SP2D TUP diterbitkan?',
    optionA: 'Paling lama 1 (satu) bulan sejak SP2D TUP terbit',
    optionB: 'Paling lama 6 bulan',
    optionC: 'Paling lama 1 tahun anggaran',
    optionD: 'Paling lama 3 hari kalender',
    correctAnswer: 'A',
    explanation: 'Dana TUP harus habis digunakan dan dipertanggungjawabkan paling lambat 1 (satu) bulan sejak SP2D TUP diterbitkan oleh KPPN.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 47 ayat (3)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'SEDANG',
    questionText: 'Jika setelah 1 bulan dana TUP masih tersisa Rp15.000.000 yang tidak terpakai, apa yang wajib dilakukan oleh Bendahara Pengeluaran?',
    optionA: 'Menyetorkan sisa uang Rp15.000.000 tersebut ke Kas Negara menggunakan Surat Setoran Pengembalian Belanja (SSPB)',
    optionB: 'Menyimpan uang tersebut untuk belanja tahun depan',
    optionC: 'Membagikan sisa dana sebagai uang saku pegawai',
    optionD: 'Mentransfer dana ke rekening tabungan pribadi bendahara',
    correctAnswer: 'A',
    explanation: 'Sisa TUP yang tidak terpakai wajib disetorkan kembali ke Kas Negara via BPN/Bank Persepsi dengan kode akun pengembalian belanja (SSPB) sebelum atau bersamaan dengan pengajuan SPM-PTUP.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 48'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'ANALISIS',
    questionText: 'Sebuah satker mengajukan permohonan perpanjangan waktu pertanggungjawaban TUP (dispensasi PTUP) karena lokasi kegiatan di pedalaman Papua mengalami banjir bandang. Siapakah pejabat yang berwenang memberikan izin perpanjangan waktu TUP?',
    optionA: 'Kepala KPPN mitra kerja setelah melakukan penelitian atas alasan kahar (force majeure) yang diajukan KPA',
    optionB: 'Bupati setempat',
    optionC: 'Kepala Kepolisian Resor',
    optionD: 'Ketua Pengadilan Agama',
    correctAnswer: 'A',
    explanation: 'Kepala KPPN memiliki kewenangan diskresi untuk memberikan perpanjangan waktu pertanggungjawaban TUP apabila terdapat kondisi kahar atau kendala geografis objektif yang dapat dipertanggungjawabkan.',
    referenceRegulation: 'Petunjuk Teknis Pengelolaan Kas KPPN DJPb'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'MUDAH',
    questionText: 'Akun bagan akun standar (BAS) yang digunakan saat pertama kali mencairkan dana Uang Persediaan pada SPM-UP adalah akun neraca aset lancar...',
    optionA: '111122 (Uang Muka Belanja dari KPPN / Kas di Bendahara Pengeluaran)',
    optionB: '521111 (Belanja Keperluan Perkantoran)',
    optionC: '532111 (Belanja Modal Peralatan Mesin)',
    optionD: '411121 (PPh Pasal 21)',
    correctAnswer: 'A',
    explanation: 'Pencairan SPM-UP awal tidak membebani akun belanja (beban), melainkan mencatat transaksi transito kas pada akun neraca 111122 (Kas di Bendahara Pengeluaran). Akun belanja baru terdebit saat pengajuan SPM-GUP.',
    referenceRegulation: 'Buku Pedoman Bagan Akun Standar (BAS) DJPb'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'SEDANG',
    questionText: 'Apakah dana UP diperbolehkan digunakan untuk membayar uang muka pekerjaan kontrak konstruksi pihak ketiga bernilai Rp500.000.000?',
    optionA: 'Tidak boleh, karena pengeluaran tersebut wajib melalui mekanisme Pembayaran Langsung (LS)',
    optionB: 'Boleh, asalkan bendahara memiliki uang tunai cukup',
    optionC: 'Boleh, jika rekanan berjanji mengembalikan dalam 2 hari',
    optionD: 'Boleh, bila disetujui staf administrasi',
    correctAnswer: 'A',
    explanation: 'UP dilarang digunakan untuk pembayaran yang seharusnya dilakukan dengan pembayaran LS (seperti kontrak pengadaan bernilai di atas Rp50 juta atau belanja modal besar).',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 43'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'ANALISIS',
    questionText: 'Bendahara Pengeluaran melakukan belanja konsumsi rapat senilai Rp8.000.000 menggunakan uang tunai UP. Kuitansi dan bukti pembelian lengkap. Kapan Bendahara dapat mengusulkan pengajuan GUP ke PPK?',
    optionA: 'Dapat dihimpun bersama kuitansi-kuitansi sah lainnya hingga mencapai minimal 50% pagu UP untuk kemudian diajukan SPP-GUP',
    optionB: 'Harus diajukan satu per satu setiap hari',
    optionC: 'Hanya boleh diajukan di bulan Desember',
    optionD: 'Tidak boleh di-GUP-kan selamanya',
    correctAnswer: 'A',
    explanation: 'Kuitansi belanja UP dikumpulkan dan dibukukan dalam BKU. Setelah mencapai akumulasi minimal 50% pagu UP (atau sesuai kebutuhan operasional bulanan), diajukan SPP-GUP untuk pengisian kembali.',
    referenceRegulation: 'SOP Modul Pembayaran & Bendahara SAKTI'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Uang Persediaan',
    difficulty: 'SEDANG',
    questionText: 'Apa yang dimaksud dengan Surat Pernyataan Tanggung Jawab Mutlak (SPTJM) yang dilampirkan pada SPM-GUP?',
    optionA: 'Pernyataan tertulis dari PPK/KPA yang menyatakan bahwa seluruh pengeluaran yang diuji telah sesuai ketentuan dan menjadi tanggung jawab penuh pejabat bersangkutan',
    optionB: 'Surat pernyataan bank bahwa uang kas asli',
    optionC: 'Surat garansi pabrik pembuat komputer',
    optionD: 'Surat izin mengemudi dinas bendahara',
    correctAnswer: 'A',
    explanation: 'SPTJM adalah dokumen legalitas formal yang menegaskan bahwa pengujian materiil belanja telah dilaksanakan secara sah oleh PPK/KPA dan bukti-bukti asli disimpan secara tertib di satker.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Lampiran Format SPTJM'
  },

  // 31-45: Penolakan SPM & Validasi KPPN
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'MUDAH',
    questionText: 'Jika KPPN menolak SPM yang diajukan oleh satker, dokumen resmi apa yang diterbitkan oleh KPPN?',
    optionA: 'Surat Penolakan Penerbitan SP2D / Lembar Konfirmasi Penolakan SPM',
    optionB: 'Surat Pemberitahuan Pajak Terutang',
    optionC: 'Surat Keterangan Bebas Narkoba',
    optionD: 'Ijazah Kelulusan Diklat',
    correctAnswer: 'A',
    explanation: 'KPPN menerbitkan Surat Pengembalian/Penolakan SPM yang mencantumkan secara rinci alasan penolakan (misalnya: pagu minus, rekening bank tidak aktif, ADK tidak valid).',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 58'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'SEDANG',
    questionText: 'Berapa batasan waktu KPPN harus menerbitkan surat penolakan apabila SPM dinyatakan tidak memenuhi persyaratan formal?',
    optionA: 'Paling lambat 1 (satu) hari kerja setelah SPM diterima loket KPPN / divalidasi sistem',
    optionB: 'Paling lambat 30 hari kerja',
    optionC: 'Paling lambat 3 bulan kemudian',
    optionD: 'Tidak ada batas waktu',
    correctAnswer: 'A',
    explanation: 'Sesuai Standar Operasional Prosedur (SOP) KPPN, penolakan SPM wajib disampaikan kepada satker paling lambat 1 hari kerja agar satker dapat segera melakukan perbaikan.',
    referenceRegulation: 'SOP Pelayanan Penerbitan SP2D DJPb'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'ANALISIS',
    questionText: 'SPM GUP satker ditolak oleh SPAN dengan notifikasi: "Tanggal Kuitansi melampaui Tahun Anggaran Berjalan". Apa penyebab mendasar error ini?',
    optionA: 'Operator merekam kuitansi bertanggal tahun lalu atau tanggal di masa depan yang tidak sesuai dengan tahun anggaran aktif',
    optionB: 'Koneksi printer di KPPN terputus',
    optionC: 'Stempel satker belum diperbarui',
    optionD: 'KPPN tidak menyukai jenis kuitansinya',
    correctAnswer: 'A',
    explanation: 'Sistem SPAN menerapkan validasi integritas tahun anggaran (period lock). Bukti transaksi yang bertanggal di luar tahun anggaran berjalan akan langsung ditolak sistem.',
    referenceRegulation: 'Juknis Validasi Bisnis SPAN Ditjen Perbendaharaan'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'SEDANG',
    questionText: 'Manakah di bawah ini yang BUKAN merupakan alasan sah bagi KPPN untuk menolak SPM yang diajukan satker?',
    optionA: 'Warna dasi atau pakaian staf satker yang mengantar berkas tidak seragam',
    optionB: 'Alokasi pagu DIPA pada akun bersangkutan tidak mencukupi (pagu minus)',
    optionC: 'Tanda tangan elektronik PPSPM tidak terdaftar / sertifikat digital kedaluwarsa',
    optionD: 'Data nomor rekening supplier berbeda dengan data pendaftaran supplier di SPAN',
    correctAnswer: 'A',
    explanation: 'Penolakan SPM hanya boleh didasarkan pada ketentuan peraturan perundang-undangan (keabsahan formal, ketersediaan dana, validitas supplier, dan integritas data), bukan atas dasar preferensi personal.',
    referenceRegulation: 'PMK 190/PMK.05/2012 & Standar Layanan WBK KPPN'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'ANALISIS',
    questionText: 'Satker mengajukan SPM-LS Gaji Induk untuk 100 pegawai. Namun SPM ditolak karena terdapat 1 orang NIP PNS yang belum di-update pada master supplier SPAN tipe 3. Solusi apa yang paling tepat?',
    optionA: 'Memutakhirkan ADK Data Pegawai/Supplier ke KPPN melalui SAKTI Modul Komitmen lalu mengunggah kembali SPM Gaji setelah supplier sukses terdaftar',
    optionB: 'Mencoret nama pegawai tersebut dengan pulpen di lembar cetak SPM',
    optionC: 'Mengajukan gaji 99 orang lewat uang persediaan tunai',
    optionD: 'Menghapus data seluruh pegawai dari database gaji',
    correctAnswer: 'A',
    explanation: 'Sebelum SPM diproses, data supplier pegawai harus sinkron antara aplikasi GPP/SAKTI dengan database SPAN. Pemutakhiran supplier tipe 3 harus didaftarkan terlebih dahulu.',
    referenceRegulation: 'Juknis Pengelolaan Supplier Gaji DJPb'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'MUDAH',
    questionText: 'Apakah penolakan SPM oleh KPPN dikenakan biaya denda atau tarif PNBP?',
    optionA: 'Tidak ada biaya sama sekali (seluruh layanan pencairan APBN di KPPN Rp0 / Tanpa Biaya)',
    optionB: 'Dikenakan biaya denda Rp50.000 per lembar SPM',
    optionC: 'Dipotong dari gaji bendahara',
    optionD: 'Dikenakan tarif administrasi bank',
    correctAnswer: 'A',
    explanation: 'Seluruh pelayanan perbendaharaan di KPPN bebas biaya (Zero Rupiah) dalam rangka komitmen Zona Integritas Wilayah Bebas dari Korupsi (WBK/WBBM).',
    referenceRegulation: 'Maklumat Pelayanan Ditjen Perbendaharaan'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'SEDANG',
    questionText: 'Jika SPM dikembalikan oleh KPPN karena kesalahan penulisan uraian pembayaran, siapakah yang berwenang menerbitkan SPM perbaikan di SAKTI?',
    optionA: 'PPSPM setelah dilakukan pembatalan SPM sebelumnya dan perbaikan konsep SPM',
    optionB: 'Petugas Front Office KPPN',
    optionC: 'Auditor Itjen',
    optionD: 'Pegawai satker lain',
    correctAnswer: 'A',
    explanation: 'Koreksi SPM dilakukan secara berjenjang di satker: Operator memperbaiki data, Validator (PPK) memeriksa, dan Approver (PPSPM) menyetujui ulang dan mengirim ADK baru ke KPPN.',
    referenceRegulation: 'User Manual Pembatalan dan Koreksi SAKTI'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'ANALISIS',
    questionText: 'Pada tanggal 15 Desember (periode akhir tahun anggaran), SPM-LS satker ditolak KPPN karena salah memilih akun belanja. Mengapa risiko penolakan di akhir tahun jauh lebih fatal bagi satker?',
    optionA: 'Batas akhir penerimaan SPM (cut-off LLAT) sangat ketat sehingga berisiko melewati tenggat dan tagihan tidak dapat dicairkan pada tahun anggaran berkenaan',
    optionB: 'Satker akan langsung dibubarkan oleh Menpan-RB',
    optionC: 'KPPN akan menghapus DIPA satker',
    optionD: 'Uang APBN otomatis dipindahkan ke kas daerah',
    correctAnswer: 'A',
    explanation: 'Penolakan SPM menjelang cut-off akhir tahun sangat berisiko mengakibatkan tagihan melewati batas waktu (hangus) sehingga harus di lunasi melalui mekanisme tunggakan di tahun anggaran berikutnya.',
    referenceRegulation: 'Pedoman Langkah-Langkah Akhir Tahun (LLAT) DJPb'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'SEDANG',
    questionText: 'Fitur pada aplikasi SAKTI yang dapat digunakan satker untuk melakukan pengujian mandiri atas validitas SPM sebelum dikirim ke KPPN adalah...',
    optionA: 'Fitur Validasi SPM dan Cek Resume Kontrak / Pagu',
    optionB: 'Fitur Game Kuis Online',
    optionC: 'Fitur Live Streaming',
    optionD: 'Fitur Kalkulator Kurs Valas',
    correctAnswer: 'A',
    explanation: 'SAKTI menyediakan menu validasi pra-kirim (pre-validation) untuk mengecek ketersediaan pagu, kelengkapan data supplier, dan keselarasan akun guna meminimalisir reject SPM di SPAN.',
    referenceRegulation: 'Modul Pembayaran SAKTI'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Penolakan SPM',
    difficulty: 'MUDAH',
    questionText: 'Jika terjadi penolakan SPM oleh KPPN, apakah nomor SPM di satker harus menggunakan nomor baru atau tetap nomor lama?',
    optionA: 'Dapat menggunakan nomor SPM baru atau menggunakan penomoran sesuai alur sistem SAKTI dengan status pembatalan SPM sebelumnya',
    optionB: 'Harus menggunakan nomor DIPA baru',
    optionC: 'Nomor SPM diundi oleh KPPN',
    optionD: 'Wajib menggunakan nomor ponsel PPK',
    correctAnswer: 'A',
    explanation: 'Di SAKTI, SPM yang ditolak KPPN dibatalkan terlebih dahulu, kemudian dibuatkan SPP/SPM perbaikan dengan nomor urut baru yang sah.',
    referenceRegulation: 'Tata Cara Pembatalan SPM SAKTI'
  },

  // 46-60: Retur SP2D & Koreksi Transaksi
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'MUDAH',
    questionText: 'Apa yang dimaksud dengan fenomena Retur SP2D dalam perbendaharaan negara?',
    optionA: 'Penolakan/pengembalian pemindahbukuan dana oleh Bank Operasional penerima karena ketidaksesuaian data rekening penerima (nama, nomor, atau status rekening pasif/tutup)',
    optionB: 'Pengembalian barang rusak oleh rekanan',
    optionC: 'Pengembalian formulir pendaftaran satker',
    optionD: 'Pembatalan lelang oleh panitia PBJ',
    correctAnswer: 'A',
    explanation: 'Retur SP2D terjadi ketika SP2D telah diterbitkan KPPN, namun bank tujuan gagal mentransfer dana ke rekening penerima akibat nomor rekening salah, nama tidak cocok, atau rekening pasif (dormant).',
    referenceRegulation: 'Perdirjen Perbendaharaan No. PER-9/PB/2018 tentang Tata Cara Penyelesaian Retur SP2D'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'SEDANG',
    questionText: 'Dana hasil retur SP2D yang dikembalikan oleh Bank Operasional kepada KPPN akan ditampung sementara pada rekening kas negara bernama...',
    optionA: 'Rekening Retur KPPN pada Bank Operasional Mitra',
    optionB: 'Rekening pribadi Kepala KPPN',
    optionC: 'Rekening kas daerah pemerintah provinsi',
    optionD: 'Rekening donasi sosial',
    correctAnswer: 'A',
    explanation: 'Dana retur ditampung di Rekening Retur KPPN yang dibuka secara resmi pada Bank Operasional untuk menunggu penyampaian surat ralat/penyelesaian rekening dari satker.',
    referenceRegulation: 'PER-9/PB/2018 Pasal 4'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'ANALISIS',
    questionText: 'Satker Balai Diklat menerima Surat Pemberitahuan Retur SP2D dari KPPN tertanggal 4 Agustus atas pembayaran honorarium narasumber. Berapa hari kerja batas waktu yang dimiliki satker untuk menyampaikan Surat Ralat Rekening dan Surat Permintaan Penerbitan Kembali SP2D (SPPR)?',
    optionA: 'Paling lambat 7 (tujuh) hari kerja terhitung sejak diterimanya Surat Pemberitahuan Retur dari KPPN',
    optionB: 'Paling lambat 30 hari kalender',
    optionC: 'Paling lambat 6 bulan',
    optionD: 'Paling lambat hari kerja berikutnya sebelum jam 08.00',
    correctAnswer: 'A',
    explanation: 'Berdasarkan PER-9/PB/2018, satker wajib menyampaikan klarifikasi, Surat Ralat Rekening, dan SPPR ke KPPN paling lambat 7 hari kerja sejak pemberitahuan retur diterima.',
    referenceRegulation: 'PER-9/PB/2018 Pasal 8 ayat (1)'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'MUDAH',
    questionText: 'Apa dampak terjadinya Retur SP2D terhadap penilaian Indikator Kinerja Pelaksanaan Anggaran (IKPA) satker?',
    optionA: 'Mengurangi nilai indikator atau menambah rasio deviasi dan catatan kepatuhan negatif pada satker bersangkutan',
    optionB: 'Menambah nilai IKPA satker sebesar 50 poin',
    optionC: 'Tidak ada pengaruh sama sekali',
    optionD: 'DIPA satker langsung dicabut',
    correctAnswer: 'A',
    explanation: 'Retur SP2D merupakan indikator ketidakcermatan pengelolaan data supplier/rekening yang menghambat hak penerima, sehingga dipantau secara ketat dalam evaluasi kinerja satker.',
    referenceRegulation: 'PER-5/PB/2022'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'SEDANG',
    questionText: 'Manakah penyebab paling sering terjadinya Retur SP2D pada pembayaran honorarium dan perjalanan dinas?',
    optionA: 'Rekening pegawai berstatus pasif (dormant), terdapat kesalahan satu digit angka nomor rekening, atau perbedaan nama di buku tabungan dengan KTP',
    optionB: 'Uang di kas negara habis',
    optionC: 'Bank Indonesia menaikkan suku bunga acuan',
    optionD: 'Kantor pos mogok kerja',
    correctAnswer: 'A',
    explanation: 'Penyebab dominan retur adalah rekening dormant (lama tidak ada transaksi sehingga terkunci otomatis oleh sistem bank) atau kesalahan pengetikan nomor rekening oleh satker.',
    referenceRegulation: 'Kajian Monitoring Retur KPPN Semarang I'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'ANALISIS',
    questionText: 'Jika dana retur SP2D di KPPN tidak diselesaikan oleh satker sampai dengan akhir tahun anggaran berjalan, bagaimanakah status dana tersebut?',
    optionA: 'Dana retur yang tidak diselesaikan sampai batas waktu akhir tahun akan disetorkan ke Rekening Kas Umum Negara sebagai Penerimaan Negara Bukan Pajak (PNBP) Lainnya',
    optionB: 'Uang retur dibagi-bagikan kepada pegawai KPPN',
    optionC: 'Uang retur otomatis dikirim ke rekening pribadi KPA',
    optionD: 'Uang retur hangus terbakar',
    correctAnswer: 'A',
    explanation: 'Sesuai regulasi penatausahaan retur, dana retur yang tidak teridentifikasi atau tidak ditindaklanjuti hingga akhir tahun anggaran disetorkan kembali ke Kas Negara sebagai penerimaan negara.',
    referenceRegulation: 'PER-9/PB/2018 Pasal 12'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'SEDANG',
    questionText: 'Langkah pencegahan utama (preventif) apa yang WAJIB dilakukan satker agar tidak terjadi Retur SP2D?',
    optionA: 'Melakukan konfirmasi aktif kepada penerima mengenai keaktifan rekening dan meminta foto buku tabungan/rekening koran resmi sebelum mendaftarkan supplier di SAKTI',
    optionB: 'Membayar seluruh honor dengan cek kosong',
    optionC: 'Menggunakan rekening pribadi bendahara untuk menampung seluruh honor',
    optionD: 'Meminta penerima membuka rekening di luar negeri',
    correctAnswer: 'A',
    explanation: 'Konfirmasi rekening aktif dan validasi buku tabungan sebelum perekaman data supplier di SAKTI merupakan SOP mitigasi paling ampuh untuk mencegah terjadinya retur.',
    referenceRegulation: 'SOP Zero Retur Ditjen Perbendaharaan'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Retur SP2D',
    difficulty: 'MUDAH',
    questionText: 'Aplikasi yang digunakan satker untuk memonitor apakah terdapat transaksi SP2D yang mengalami status retur secara real-time adalah...',
    optionA: 'MonSAKTI (Menu Monitoring Retur SP2D)',
    optionB: 'Google Maps',
    optionC: 'Aplikasi Peduli Lindungi',
    optionD: 'Microsoft PowerPoint',
    correctAnswer: 'A',
    explanation: 'MonSAKTI menyediakan menu khusus Monitoring Retur SP2D yang memberikan notifikasi instan begitu ada SP2D satker yang dikembalikan oleh perbankan.',
    referenceRegulation: 'Petunjuk Operasional MonSAKTI DJPb'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Koreksi Data Transaksi',
    difficulty: 'SEDANG',
    questionText: 'Apakah satker diperkenankan mengajukan Surat Permohonan Koreksi Akun / Koreksi Uraian atas SP2D yang telah terbit kepada Kepala KPPN?',
    optionA: 'Boleh, sepanjang tidak mengubah jumlah total pengeluaran kas dan diajukan sesuai tata cara koreksi pembukuan yang sah',
    optionB: 'Sama sekali tidak boleh dikoreksi selamanya',
    optionC: 'Hanya boleh jika disetujui presiden secara tertulis',
    optionD: 'Boleh jika satker membayar denda ke KPPN',
    correctAnswer: 'A',
    explanation: 'Berdasarkan PMK terkait tata cara koreksi pembukuan penerimaan dan pengeluaran, KPA dapat mengajukan surat permohonan koreksi SPM/SP2D (misal salah kode akun, salah program/kegiatan) sepanjang tidak mengubah nilai total uang yang keluar.',
    referenceRegulation: 'Perdirjen Perbendaharaan tentang Tata Cara Ralat/Koreksi SPM/SP2D'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Koreksi Data Transaksi',
    difficulty: 'ANALISIS',
    questionText: 'Satker telah menerbitkan SPM-LS senilai Rp50.000.000 pada akun 521211 (Belanja Bahan), namun setelah SP2D terbit disadari bahwa akun yang benar seharusnya akun 522111 (Belanja Langganan Daya dan Jasa). Dokumen apa yang harus dipersiapkan satker?',
    optionA: 'Surat Permohonan Koreksi Akun dari KPA kepada Kepala KPPN, melampirkan lembar komparasi data semula dan menjadi, serta SPTJM',
    optionB: 'Kuitansi palsu baru',
    optionC: 'Surat somasi kepada penyedia PLN',
    optionD: 'Laporan kehilangan dari kepolisian',
    correctAnswer: 'A',
    explanation: 'Koreksi akun yang telah terbit SP2D-nya diproses melalui penerbitan Nota Koreksi di KPPN berdasarkan surat permohonan resmi KPA yang memuat rincian data semula-menjadi.',
    referenceRegulation: 'Juknis Koreksi Transaksi Pengeluaran SPAN-SAKTI'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Koreksi Data Transaksi',
    difficulty: 'SEDANG',
    questionText: 'Apakah koreksi data rekening supplier pihak ketiga dapat dilakukan setelah SP2D berhasil cair ke rekening penerima tanpa ada retur?',
    optionA: 'Tidak perlu koreksi jika uang sudah sukses masuk ke rekening yang sah dan dimaksud',
    optionB: 'Wajib ditarik kembali uangnya oleh KPPN',
    optionC: 'KPPN akan menyita buku tabungan penerima',
    optionD: 'Harus diproses lelang ulang',
    correctAnswer: 'A',
    explanation: 'Jika dana telah berhasil terindahbukukan ke rekening yang berhak tanpa kendala, tidak ada koreksi transaksi kas yang diperlukan. Pemutakhiran supplier hanya dilakukan untuk transaksi berikutnya bila diperlukan.',
    referenceRegulation: 'SOP Pelayanan Pengelolaan Supplier KPPN'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Koreksi Data Transaksi',
    difficulty: 'MUDAH',
    questionText: 'Siapakah pejabat KPPN yang berwenang menyetujui Nota Koreksi atas kesalahan pembebanan akun SP2D satker?',
    optionA: 'Kepala Seksi Manajemen Satker dan Kepatuhan Internal (MSKI) / Seksi Bank / Seksi Pencairan Dana sesuai pendelegasian wewenang Kepala KPPN',
    optionB: 'Staf keamanan (satpam) KPPN',
    optionC: 'Pengemudi kendaraan dinas',
    optionD: 'Penyedia katering kantor',
    correctAnswer: 'A',
    explanation: 'Nota koreksi diproses dan diverifikasi oleh Seksi terkait (Seksi Pencairan Dana / Seksi Bank / Seksi MSKI) dan disahkan oleh Kepala KPPN atau pejabat yang ditunjuk.',
    referenceRegulation: 'SOP Pengelolaan Koreksi Pembukuan KPPN'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Koreksi Data Transaksi',
    difficulty: 'ANALISIS',
    questionText: 'Satker mengajukan koreksi akun belanja modal ke belanja barang setelah Laporan Keuangan Tahunan audited selesai diperiksa BPK. Apakah KPPN masih dapat memproses koreksi tersebut pada tahun anggaran yang telah ditutup?',
    optionA: 'Tidak bisa pada tahun anggaran yang telah lewat (closed period); koreksi harus dibukukan melalui jurnal penyesuaian koreksi kesalahan masa lalu pada laporan keuangan tahun berjalan',
    optionB: 'Bisa kapan saja bahkan 10 tahun kemudian',
    optionC: 'Bisa dengan membayar biaya tambahan',
    optionD: 'Bisa dengan membatalkan SP2D 1 tahun yang lalu',
    correctAnswer: 'A',
    explanation: 'Tahun anggaran yang telah ditutup dan diaudit tidak dapat diubah catatan kasnya di SPAN. Koreksi dilakukan secara akuntansi pada periode berjalan sesuai Pernyataan Standar Akuntansi Pemerintahan (PSAP) No. 10.',
    referenceRegulation: 'PSAP No. 10 tentang Koreksi Kesalahan, Perubahan Kebijakan Akuntansi, dan Peristiwa Luar Biasa'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Koreksi Data Transaksi',
    difficulty: 'SEDANG',
    questionText: 'Apa yang dimaksud dengan surat permintaan pengembalian penerimaan (koreksi setoran pendapatan) ke kas negara yang salah disetor oleh satker?',
    optionA: 'Surat Permohonan Pengembalian Pendapatan yang diajukan satker/wajib setor ke KPPN sesuai PMK terkait pengembalian penerimaan negara',
    optionB: 'Pengambilan uang tunai langsung dari brankas bank',
    optionC: 'Klaim asuransi jiwa',
    optionD: 'Gugatan perdata di pengadilan militer',
    correctAnswer: 'A',
    explanation: 'Penerimaan negara yang terlanjur disetor akibat kelebihan bayar atau salah setor dapat dikembalikan melalui penerbitan SPM-PP (Surat Perintah Membayar Pengembalian Pendapatan) oleh KPPN.',
    referenceRegulation: 'PMK tentang Tata Cara Pembayaran Pengembalian Penerimaan Negara'
  },
  {
    topic: 'Mekanisme Pembayaran APBN - Koreksi Data Transaksi',
    difficulty: 'MUDAH',
    questionText: 'Tindakan apa yang pertama kali harus dilakukan operator satker jika menyadari ada kesalahan ketik nominal pada SPP sebelum diterbitkan SPM oleh PPSPM?',
    optionA: 'Membatalkan draft SPP pada Modul Pembayaran SAKTI dan merekam kembali data SPP yang benar',
    optionB: 'Meneruskan saja hingga menjadi SP2D',
    optionC: 'Menutup aplikasi dan membiarkannya',
    optionD: 'Menelepon pihak bank swasta',
    correctAnswer: 'A',
    explanation: 'Selama SPP belum diproses menjadi SPM (belum diterbitkan OTP oleh PPSPM), perbaikan dapat dilakukan dengan mudah melalui fitur pembatalan SPP oleh operator/PPK di SAKTI.',
    referenceRegulation: 'User Manual SAKTI Modul Pembayaran'
  }
];
