import { RawQuestion } from './questionsIkpa';

export const upKkpDigipayQuestions: RawQuestion[] = [
  // 1-15: KKP (Kartu Kredit Pemerintah)
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Apakah landasan hukum utama yang mengatur penggunaan Kartu Kredit Pemerintah (KKP) dalam pelaksanaan Anggaran Pendapatan dan Belanja Negara (APBN)?',
    optionA: 'Peraturan Menteri Keuangan Nomor 196/PMK.05/2018 tentang Tata Cara Pembayaran dan Penggunaan Kartu Kredit Pemerintah',
    optionB: 'Undang-Undang Lalu Lintas dan Angkutan Jalan',
    optionC: 'Peraturan Menteri Perdagangan tentang Pasar Swalayan',
    optionD: 'Peraturan Menteri Pendidikan tentang Kurikulum Merdeka',
    correctAnswer: 'A',
    explanation: 'Penggunaan KKP diatur secara komprehensif dalam PMK No. 196/PMK.05/2018 untuk mewujudkan pembayaran non-tunai yang aman, transparan, dan efisien.',
    referenceRegulation: 'PMK No. 196/PMK.05/2018'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Berapakah proporsi standar besaran pagu Uang Persediaan (UP) yang dialokasikan untuk Uang Persediaan Kartu Kredit Pemerintah (UP KKP)?',
    optionA: '40% untuk UP KKP dan 60% untuk UP Tunai',
    optionB: '10% untuk UP KKP dan 90% untuk UP Tunai',
    optionC: '50% untuk UP KKP dan 50% untuk UP Tunai',
    optionD: '100% untuk UP KKP tanpa UP Tunai',
    correctAnswer: 'A',
    explanation: 'Sesuai PMK 196/PMK.05/2018, proporsi besaran UP satker dibagi menjadi 60% UP Tunai dan 40% UP KKP dari total pagu UP yang disetujui.',
    referenceRegulation: 'PMK 196/PMK.05/2018 Pasal 5 ayat (2)'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Apakah satker diperkenankan mengajukan perubahan proporsi besaran UP KKP (misal menjadi 20% KKP dan 80% Tunai) kepada Kepala KPPN?',
    optionA: 'Boleh, dengan mengajukan surat permohonan dispensasi perubahan proporsi UP KKP disertai alasan objektif (seperti minimnya merchant EDC di lokasi terpencil)',
    optionB: 'Sama sekali tidak boleh dalam kondisi apapun',
    optionC: 'Hanya boleh jika satker tidak memiliki internet',
    optionD: 'Boleh, bila disetujui oleh kasir minimarket',
    correctAnswer: 'A',
    explanation: 'Kepala KPPN atas nama Menteri Keuangan dapat menyetujui perubahan proporsi UP KKP atau dispensasi peniadaan UP KKP bagi satker dengan kondisi geografis minim infrastruktur perbankan/EDC.',
    referenceRegulation: 'PMK 196/PMK.05/2018 Pasal 6'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Manakah dua jenis Kartu Kredit Pemerintah (KKP) yang diterbitkan oleh Bank Penerbit KKP bagi Satuan Kerja?',
    optionA: 'KKP untuk Keperluan Belanja Operasional/Barang dan KKP untuk Keperluan Belanja Perjalanan Dinas Jabatan',
    optionB: 'KKP Platinum dan KKP Eksekutif Swasta',
    optionC: 'KKP Khusus Liburan dan KKP Hiburan Malam',
    optionD: 'KKP Pembelian Saham dan KKP Kripto',
    correctAnswer: 'A',
    explanation: 'PMK 196/2018 membagi KKP menjadi 2 kategori: KKP Belanja Operasional/Barang (pembelian ATK, jamuan, pemeliharaan) dan KKP Belanja Perjalanan Dinas (tiket pesawat, hotel, taksi).',
    referenceRegulation: 'PMK 196/PMK.05/2018 Pasal 7'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'ANALISIS',
    questionText: 'Seorang pejabat perbendaharaan pemegang KKP Belanja Perjalanan Dinas membeli tiket pesawat dinas seharga Rp3.500.000 menggunakan KKP. Kuitansi dan billing statement bank terbit. Siapakah yang wajib melunasi tagihan KKP tersebut ke pihak Bank Penerbit?',
    optionA: 'Bendahara Pengeluaran satker melalui penerbitan SPP/SPM-GUP KKP ke rekening penampungan KKP bank berkenaan sebelum tanggal jatuh tempo',
    optionB: 'Pejabat pemegang kartu menggunakan uang gajinya sendiri',
    optionC: 'Maskapai penerbangan yang bersangkutan',
    optionD: 'Dibiarkan menunggak tanpa perlu dibayar',
    correctAnswer: 'A',
    explanation: 'Pelunasan tagihan KKP resmi dibayar oleh negara melalui penerbitan SPM-GUP KKP oleh PPSPM ke KPPN, sehingga dana SP2D ditransfer langsung ke rekening penampungan KKP bank penerbit.',
    referenceRegulation: 'PMK 196/PMK.05/2018 Bab Pelunasan Tagihan KKP'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Berapakah batasan maksimal limit belanja Kartu Kredit Pemerintah untuk keperluan Belanja Operasional per pemegang kartu secara default?',
    optionA: 'Paling banyak Rp50.000.000 (lima puluh juta rupiah)',
    optionB: 'Paling banyak Rp5.000.000',
    optionC: 'Paling banyak Rp500.000.000',
    optionD: 'Tidak ada batas limit',
    correctAnswer: 'A',
    explanation: 'Batasan limit belanja KKP untuk keperluan belanja operasional adalah paling banyak Rp50.000.000 per pemegang kartu per bulan.',
    referenceRegulation: 'PMK 196/PMK.05/2018 Pasal 8'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Siapakah yang menanggung bunga dan biaya denda keterlambatan pembayaran KKP apabila keterlambatan pelunasan disebabkan kelalaian staf pemegang kartu yang terlambat menyerahkan bukti transaksi?',
    optionA: 'Pejabat/staf pemegang kartu bersangkutan secara pribadi',
    optionB: 'APBN melalui pos anggaran tak terduga',
    optionC: 'KPPN Semarang I',
    optionD: 'Bank Indonesia',
    correctAnswer: 'A',
    explanation: 'Jika keterlambatan pembayaran tagihan KKP diakibatkan kelalaian pemegang kartu terlambat menyerahkan SPBy dan bukti pengeluaran, bunga/denda dibebankan kepada pemegang kartu secara pribadi.',
    referenceRegulation: 'PMK 196/PMK.05/2018 Pasal 29'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'ANALISIS',
    questionText: 'Dalam rangka pengadaan barang darurat, satker membutuhkan transaksi KKP belanja operasional sebesar Rp90.000.000 dalam satu transaksi. Padahal limit kartu saat ini adalah Rp50.000.000. Prosedur apa yang harus ditempuh?',
    optionA: 'KPA mengajukan permohonan kenaikan limit KKP sementara kepada Kepala KPPN dan persetujuan tersebut diteruskan ke Bank Penerbit KKP',
    optionB: 'Memecah tagihan menjadi dua kartu pribadi staf',
    optionC: 'Meminjam kartu kredit milik direktur rekanan',
    optionD: 'Membayar dengan wesel pos',
    correctAnswer: 'A',
    explanation: 'Kenaikan limit KKP sementara dapat diajukan KPA kepada Kepala KPPN dengan melampirkan rincian rencana kebutuhan transaksi pengadaan, yang kemudian disampaikan ke Bank Mitra.',
    referenceRegulation: 'Petunjuk Teknis Kenaikan Limit KKP DJPb'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Apakah transaksi belanja barang menggunakan Kartu Kredit Pemerintah (KKP) dipungut Pajak Penghasilan (PPh) Pasal 22 oleh bendahara pengeluaran?',
    optionA: 'Tidak dipungut PPh Pasal 22 (dikecualikan dari pemungutan PPh Pasal 22)',
    optionB: 'Tetap dipungut PPh 22 sebesar 10%',
    optionC: 'Dipungut dua kali lipat',
    optionD: 'Hanya jika belanja makanan',
    correctAnswer: 'A',
    explanation: 'Berdasarkan PMK tentang pemungutan PPh Pasal 22 oleh instansi pemerintah, transaksi belanja barang dengan Kartu Kredit Pemerintah (KKP) dikecualikan dari pemungutan PPh Pasal 22.',
    referenceRegulation: 'PMK No. 231/PMK.03/2019 jo PMK No. 59/PMK.03/2022 Pasal 12'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Bank manakah yang berhak menerbitkan Kartu Kredit Pemerintah bagi Satuan Kerja kementerian/lembaga?',
    optionA: 'Bank BUMN yang tergabung dalam Himbara (BRI, Mandiri, BNI, BTN) atau Bank Syariah Indonesia (BSI) yang telah menandatangani PKS Induk Kemenkeu',
    optionB: 'Semua koperasi simpan pinjam desa',
    optionC: 'Bank asing yang tidak beroperasi di Indonesia',
    optionD: 'Lembaga gadai swasta',
    correctAnswer: 'A',
    explanation: 'Bank Penerbit KKP adalah bank umum mitra pemerintah yang telah menandatangani Perjanjian Kerja Sama (PKS) Induk dengan Ditjen Perbendaharaan dan PKS dengan Satker.',
    referenceRegulation: 'PMK 196/PMK.05/2018 Pasal 4'
  },

  // 11-25: Digipay Satu & Ekosistem Pengadaan Digital
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Apa yang dimaksud dengan platform DIGIPAY SATU dalam ekosistem belanja pemerintah?',
    optionA: 'Aplikasi marketplace terintegrasi pengadaan barang/jasa pemerintah satker APBN yang menghubungkan Satker, Vendor/UMKM lokal, dan Perbankan secara digital',
    optionB: 'Aplikasi media sosial internal pegawai Kemenkeu',
    optionC: 'Game strategi militer online',
    optionD: 'Aplikasi pemesanan tiket bioskop komersial',
    correctAnswer: 'A',
    explanation: 'Digipay Satu adalah platform marketplace pengadaan pemerintah yang menyatukan seluruh bank Himbara/mitra dalam satu sistem pengadaan, pembayaran non-tunai, dan perpajakan otomatis.',
    referenceRegulation: 'Petunjuk Teknis Digipay Satu Ditjen Perbendaharaan'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Manakah keunggulan utama bertransaksi belanja operasional kantor melalui Digipay Satu bagi bendahara dan satker?',
    optionA: 'Otomasi perhitungan dan pemungutan pajak, bebas risiko uang palsu, pembayaran terjadwal via CMS/KKP, dan pencatatan BKU otomatis',
    optionB: 'Mendapatkan cashback tunai untuk dibagikan ke staf',
    optionC: 'Bisa berbelanja barang pribadi tanpa pertanggungjawaban',
    optionD: 'Menghapuskan kewajiban membuat kuitansi belanja',
    correctAnswer: 'A',
    explanation: 'Digipay Satu mengotomasi proses pengadaan, settlement pembayaran rekening perbankan (CMS/KKP), perhitungan pajak otomatis, dan pembuatan e-Billing terpadu.',
    referenceRegulation: 'Pedoman Implementasi Digipay Satu DJPb'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'ANALISIS',
    questionText: 'Satker Balai Diklat ingin membeli konsumsi pelatihan sebesar Rp12.000.000 melalui Digipay Satu dari UMKM katering lokal yang belum terdaftar di Digipay. Langkah apa yang harus dilakukan satker?',
    optionA: 'Membimbing dan mengajak vendor katering tersebut untuk mendaftar akun vendor di Digipay Satu dan membuka rekening bank mitra',
    optionB: 'Membatalkan pelatihan',
    optionC: 'Meminta vendor meminjam akun vendor lain secara ilegal',
    optionD: 'Membeli konsumsi dari luar negeri',
    correctAnswer: 'A',
    explanation: 'Salah satu peran Satker dan KPPN adalah melakukan on-boarding UMKM lokal ke dalam ekosistem Digipay Satu guna memberdayakan ekonomi lokal di wilayah kerja.',
    referenceRegulation: 'Panduan Onboarding Vendor Digipay Satu'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Metode pembayaran apa saja yang didukung dalam transaksi di platform Digipay Satu?',
    optionA: 'Cash Management System (CMS) Virtual Account / Rekening Giro dan Kartu Kredit Pemerintah (KKP)',
    optionB: 'Uang logam pecahan Rp100',
    optionC: 'Cek mundur perorangan',
    optionD: 'Tukar guling tanah kantor',
    correctAnswer: 'A',
    explanation: 'Digipay Satu mendukung dua saluran pembayaran non-tunai resmi perbendaharaan: CMS Perbankan (debit rekening kas bendahara) dan KKP.',
    referenceRegulation: 'Juknis Transaksi Digipay Satu'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Apakah transaksi belanja di Digipay Satu dikenakan biaya jasa perantara (fee transaksi) yang membebani pagu DIPA Satker?',
    optionA: 'Bebas biaya administrasi bagi satker (Rp0 untuk instansi pemerintah)',
    optionB: 'Dikenakan biaya komisi 20% dari total belanja',
    optionC: 'Dikenakan tarif sewa server Rp1.000.000 per transaksi',
    optionD: 'Dikenakan iuran bulanan wajib',
    correctAnswer: 'A',
    explanation: 'Platform Digipay Satu dikembangkan oleh Kementerian Keuangan bekerja sama dengan Bank Mitra tanpa memungut biaya transaksi dari satker pemerintah.',
    referenceRegulation: 'PKS Induk Digipay Satu Kemenkeu dan Himbara'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'ANALISIS',
    questionText: 'Dalam indikator Kinerja Pelaksanaan Anggaran (IKPA) dan penilaian kinerja modernisasi perbendaharaan, bagaimana pemanfaatan Digipay dinilai?',
    optionA: 'Sebagai indikator akselerasi digitalisasi pembayaran non-tunai dan kontribusi satker dalam mendukung pemberdayaan UMKM lokal',
    optionB: 'Dinilai sebagai pemborosan anggaran kantor',
    optionC: 'Dinilai sebagai pelanggaran etika belanja',
    optionD: 'Tidak memiliki penilaian apapun',
    correctAnswer: 'A',
    explanation: 'Pemerintah mendorong digitalisasi perbendaharaan (cashless payment). Kepatuhan penggunaan Digipay dan KKP menjadi parameter penting dalam penilaian keunggulan satker.',
    referenceRegulation: 'Arah Kebijakan Modernisasi Pengelolaan Kas DJPb'
  },

  // 26-40: Cash Management System (CMS) & Rekening Kas Bendahara
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Layanan perbankan berbasis internet (internet banking korporat) yang digunakan bendahara instansi pemerintah untuk transaksi transfer dana non-tunai disebut...',
    optionA: 'Cash Management System (CMS) Perbankan',
    optionB: 'ATM Bersama',
    optionC: 'Mesin Hitung Uang Kertas',
    optionD: 'Kotak Infak Elektronik',
    correctAnswer: 'A',
    explanation: 'Cash Management System (CMS) adalah sistem perbankan korporasi yang memfasilitasi bendahara melakukan transaksi mutasi kas, pembayaran tagihan, dan transfer secara digital dari kantor.',
    referenceRegulation: 'PMK No. 182/PMK.05/2017 tentang Rekening Milik Satker K/L'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Bagaimanakah pemisahan kewenangan keamanan (multi-user authorization) yang wajib diterapkan pada operasional CMS rekening Bendahara Pengeluaran?',
    optionA: 'Maker (staf penginput transfer), Checker (verifikator), dan Approver/Releaser (Bendahara Pengeluaran)',
    optionB: 'Satu orang operator memegang semua password dan token bank sendirian',
    optionC: 'Password CMS diberikan kepada semua pegawai kantor',
    optionD: 'Dikelola oleh pihak luar kantor tanpa pengawasan',
    correctAnswer: 'A',
    explanation: 'Prinsip Maker-Checker-Releaser pada CMS bank menjamin tidak ada satupun individu yang dapat mengeksekusi pengeluaran uang kas pemerintah secara sepihak tanpa kontrol berlapis.',
    referenceRegulation: 'SOP Keamanan Transaksi Perbankan DJPb'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'ANALISIS',
    questionText: 'Seorang Bendahara Pengeluaran menggunakan akun CMS-nya untuk mentransfer uang kas persediaan APBN ke rekening pribadinya dengan alasan mempermudah tarik tunai belanja di akhir pekan. Bagaimanakah tinjauan regulasi atas tindakan tersebut?',
    optionA: 'Merupakan pelanggaran berat atas larangan percampuran kas dinas dengan rekening pribadi dan berisiko tindak pidana korupsi/penyalahgunaan wewenang',
    optionB: 'Dibenarkan jika bendahara mencatatnya di buku harian',
    optionC: 'Dianjurkan untuk mempercepat pelayanan',
    optionD: 'Boleh dilakukan asalkan dikembalikan dalam waktu 3 bulan',
    correctAnswer: 'A',
    explanation: 'PMK 182/2017 dan UU 1/2004 secara tegas melarang keras penempatan atau transfer uang kas negara ke dalam rekening pribadi dengan dalih apapun.',
    referenceRegulation: 'UU No. 1/2004 Pasal 34 & PMK 182/PMK.05/2017'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Fitur pada CMS perbankan yang memungkinkan pembayaran tagihan belanja langsung memungut dan menyetorkan pajak ke kas negara secara otomatis melalui integrasi Modul Penerimaan Negara (MPN) disebut...',
    optionA: 'Integrasi e-Billing / MPN Pajak pada CMS',
    optionB: 'Fitur Transfer Game Online',
    optionC: 'Fitur Tarik Tunai Tanpa Kartu',
    optionD: 'Fitur Pinjaman Online Otomatis',
    correctAnswer: 'A',
    explanation: 'CMS Bank Himbara/mitra pemerintah telah terhubung dengan Modul Penerimaan Negara (MPN G3) untuk eksekusi kode billing pajak secara instan.',
    referenceRegulation: 'Perdirjen Perbendaharaan tentang Modul Penerimaan Negara Generasi Ketiga'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Berapakah batas waktu pengesahan SPBy (Surat Perintah Bayar) yang dibayarkan oleh Bendahara Pengeluaran sebelum diajukan SPP-GUP?',
    optionA: 'SPBy ditandatangani oleh PPK dan dibayarkan oleh Bendahara setelah kuitansi dan bukti pengeluaran sah terverifikasi',
    optionB: 'SPBy tidak perlu ditandatangani oleh siapapun',
    optionC: 'Hanya boleh ditandatangani oleh staf magang',
    optionD: 'Harus disahkan oleh camat setempat',
    correctAnswer: 'A',
    explanation: 'SPBy (Surat Perintah Bayar) adalah surat perintah dari PPK kepada Bendahara Pengeluaran untuk membayarkan sejumlah uang atas beban UP kepada penerima yang berhak.',
    referenceRegulation: 'PMK 190/PMK.05/2012 Pasal 51'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'ANALISIS',
    questionText: 'Satker Balai Besar memiliki pagu UP Rp200.000.000 (Rp120.000.000 UP Tunai dan Rp80.000.000 UP KKP). Dalam bulan berjalan, satker merevolving UP Tunai sebesar Rp70.000.000 dan UP KKP sebesar Rp50.000.000. Apakah satker telah memenuhi ambang batas perputaran UP minimal 50%?',
    optionA: 'Ya, kedua jenis UP telah berputar di atas 50% (UP Tunai 58,3% dan UP KKP 62,5%) sehingga memperoleh nilai maksimal indikator Pengelolaan UP',
    optionB: 'Belum, karena total belanja harus mencapai Rp200.000.000 penuh',
    optionC: 'Tidak dinilai karena belanja KKP tidak dihitung',
    optionD: 'Satker terkena penalti nilai 20%',
    correctAnswer: 'A',
    explanation: 'Ambang batas perputaran bulanan adalah minimal 50%. UP Tunai: 70/120 = 58,3% (>= 50%). UP KKP: 50/80 = 62,5% (>= 50%). Keduanya memenuhi target.',
    referenceRegulation: 'PER-5/PB/2022'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Apakah bunga bank (jasa giro) yang diperoleh dari rekening kas Bendahara Pengeluaran di bank persepsi boleh digunakan langsung untuk membiayai makan siang staf satker?',
    optionA: 'Tidak boleh, seluruh bunga/jasa giro rekening kas pemerintah wajib disetorkan secara utuh ke Kas Negara sebagai PNBP Jasa Giro',
    optionB: 'Boleh, sebagai dana kesejahteraan internal',
    optionC: 'Boleh, jika nominalnya di bawah Rp1.000.000',
    optionD: 'Boleh, asalkan dibagi rata kepada semua honorer',
    correctAnswer: 'A',
    explanation: 'Sesuai UU 17/2003 dan UU 1/2004, seluruh penerimaan bunga dan jasa giro atas penempatan uang negara pada perbankan merupakan penerimaan negara bukan pajak (PNBP) yang wajib disetor ke kas negara.',
    referenceRegulation: 'UU No. 17/2003 tentang Keuangan Negara & PMK 182/PMK.05/2017'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'MUDAH',
    questionText: 'Berapakah biaya administrasi bulanan yang didebit oleh bank atas rekening giro resmi dinas Bendahara Pengeluaran pemerintah yang berizin?',
    optionA: 'Rp0 (bebas biaya administrasi bulanan berdasarkan PKS Kementerian Keuangan dengan Bank Mitra)',
    optionB: 'Rp500.000 per bulan',
    optionC: '1% dari saldo kas',
    optionD: 'Tergantung negosiasi lisan',
    correctAnswer: 'A',
    explanation: 'Berdasarkan Perjanjian Kerja Sama Induk Kemenkeu dengan Bank Operasional/Persepsi mitra, seluruh rekening resmi pemerintah dibebaskan dari biaya administrasi bulanan.',
    referenceRegulation: 'PKS Induk Layanan Perbankan Kementerian Keuangan'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'ANALISIS',
    questionText: 'Satker kehilangan buku cek dan kartu token CMS bendahara akibat bencana kebakaran kantor. Prosedur mitigasi darurat apa yang harus segera dilakukan bendahara?',
    optionA: 'Melapor segera ke Bank Penerbit untuk melakukan pemblokiran rekening/token, membuat Laporan Polisi, dan melaporkan secara tertulis kepada KPA dan Kepala KPPN',
    optionB: 'Membeli token bajakan di pasar loak',
    optionC: 'Mendiamkan saja hingga tahun anggaran selesai',
    optionD: 'Menyalahkan staf magang',
    correctAnswer: 'A',
    explanation: 'Pemblokiran instan ke pihak bank adalah mitigasi pertama untuk mengamankan saldo kas negara, diikuti pembuatan berita acara kehilangan dan laporan ke KPPN.',
    referenceRegulation: 'SOP Penanganan Risiko Operasional Kas Perbendaharaan'
  },
  {
    topic: 'Pengelolaan KKP & Digipay',
    difficulty: 'SEDANG',
    questionText: 'Apa fungsi utama Berita Acara Rekonsiliasi Bank yang disusun oleh Bendahara setiap akhir bulan?',
    optionA: 'Mencocokkan saldo kas menurut Buku Kas Umum (BKU) dengan saldo kas riil menurut Rekening Koran Bank dan mengidentifikasi penyebab selisih kas (outstanding check / deposit in transit)',
    optionB: 'Meminta kenaikan plafon kredit pinjaman',
    optionC: 'Menghitung laba rugi usaha komersial',
    optionD: 'Memilih pegawai teladan bulan berkenaan',
    correctAnswer: 'A',
    explanation: 'Rekonsiliasi bank bulanan memverifikasi keakuratan pembukuan kas bendahara terhadap catatan mutasi bank penerbit guna memastikan tidak ada transaksi liar atau kelalaian pencatatan.',
    referenceRegulation: 'PMK 162/PMK.05/2013 tentang Kedudukan dan Tanggung Jawab Bendahara'
  }
];
